### ISSUE TITLE
Reverse-Sorting of mails and threads

### ISSUE THREAD

**Issue by sbstnmsch** [nylas/N1#10]
I wonder how i can sort my e-mails reverse-ordered to see the newest at the top.

**Comment by dillonforrest** [comment]
Hey @sbstnmsch, N1 should sort email with the newest mail up top already. I'm alarmed that we're showing your email in the wrong order!

Can you clarify, are you just not seeing your newest mail? Or is your mail sorted with the oldest mail up top, and newer mail following?

**Comment by sbstnmsch** [comment]
Just wanted to see if i got something wrong here. But after restart of nylas i'm nuked out and have to get an invitation now. Requesting that your website tells me "missing CSRF token". Stormy night ;-)
Just drop me one at sbstnmsch at our beloved gmail dot com so i can retest.

Good work though, - that's the e-mail client i was waiting for!

**Comment by dillonforrest** [comment]
hehehe, sorry!!!!

I'll turn this issue into a feature request for the CSRF token. Thank you!

**Comment by sbstnmsch** [comment]
Ok, i'm back in and retested. The e-mail list is indeed reverse-ordered. Love it.
The thread-list on the right is not really reverse-ordered, which is, just my two cents, a bit misleading. Once i click 'x older messages' i have to scroll and scroll down to get recent messages. Is there another way to collapse them back other than selecting another thread?
Maybe i missed the point and there is a visionary new concept ;-) But i don't get it ;-]

**Comment by brothersgroupjsrbd** [comment]
good

**Comment by mbilker** [comment]
The newest are at the top by default in the recent versions. I don't think you can switch it to the other direction where the newest are at the bottom yet.

**Comment by kriskhaira** [comment]
I ended up here so thought I'd leave a message. The feature request to sort the direction of replies in a conversation is this one: https://github.com/nylas/N1/issues/1071

**Comment by Afrowave** [comment]
Aah, I see. my bad. :-)

**Comment by kelleychambers** [comment]
This is quite an old request. Has this been fulfilled yet? I'm having a rough time making the jump without it. :(

**Comment by mbilker** [comment]
Newest messages are at the top already. If you want the replies to a conversation at the top please go to #1071. If you want to have the oldest at the top, post a feature request issue.

**Comment by mbilker** [comment]
@kelleychambers Newest are already at the top.

**Comment by kelleychambers** [comment]
Actually, in conversation view, they are not. I'll check out
"https://github.com/nylas/N1/issues/1071" you sent me in a previous message.  
  

  

![](http://rwpstudios.com/graphics/rwp-logo-130x160.png)

Kindest Regards,

Kelley Chambers, CWD

Runs With Pixels, LLC

[www.rwpstudios.com](http://www.rwpstudios.com)

[www.fb.com/RunsWithPixels](http://www.fb.com/RunsWithPixels)

[www.linkedin.com/in/kelleychambers](http://www.linkedin.com/in/kelleychambers
)

770.744.0334

  

On May 20 2016, at 3:02 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

> [@kelleychambers](https://github.com/kelleychambers) Newest are already at
the top.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/10#issuecomment-220691461)![](https://github.com/notifications/beacon
/ADcITyZLw2soI71Prs_DYqY2w4YXgLSYks5qDgUjgaJpZM4GJPWr.gif)
