### ISSUE TITLE
Feature Request: Add a simple "archive" function for IMAP and Exchange accounts

### ISSUE THREAD

**Issue by jdenoy** [nylas/N1#1015]
For an IMAP account, a simple archive function to move mails to a specified archive folder would be nice.

**Comment by pedrokost** [comment]
+1

**Comment by orschiro** [comment]
Dear all, 

Is this great feature something we can expect to come in the near future? 

It's really annoying that I can't get rid of some of my emails in my Inbox other than having to delete them. 

Archiving has just so much become the default workflow since the dominance of Gmail.

Thankfully,

~Robert

**Comment by KevinMartin** [comment]
You should be able to create an Archive folder in N1. If it doesn't link correctly, then open up Thunderbird (maybe even Apple Mail), go into mailbox settings and set the new Archive folder to act as the archive folder (which adds a `\Archive` flag to the folder). 

You may need to readd the account

**Comment by orschiro** [comment]
Thank you @KevinMartin!

Can I do this from Gmail as well? I don't use Thunderbird, neither Apple Mail.

~Robert

**Comment by jackiehluo** [comment]
Closing because it sounds like what you want is #1457!
