### ISSUE TITLE
Can't change Password

### ISSUE THREAD

**Issue by mzehrer** [nylas/N1#1019]
There is no (obvious) way to change the password for an account. This was already mentioned in #776, which was closed without a real solution.

**Comment by ChristopheLux** [comment]
Indeed +1

**Comment by jdenoy** [comment]
I'd modify to changing "all account parameters" (changing server adress is also an issue)

**Comment by InvisibleOrdinary** [comment]
agreed. There needs to be a way to access all account settings

**Comment by bashok001** [comment]
Combine this #1070 and this qualifies as a bug.

I changed my Gmail password and lost track of emails for a full day. (Didn't realize they are not syncing). When I realized mail sync is not happening, I could not straight away think of password change but rather tried reloading and other things. 

When I did realize that sync should have stopped because of password change (Timestamp of last mail that successfully synced), I could not find a way to re-authenticate / re-connect Nylas to my gmail. @mbilker, fast resolution for this please

**Comment by grinich** [comment]
@jdenoy in what situation do you need to change the server address?

**Comment by jdenoy** [comment]
@grinich in the case we change mail hosting provider. it has occured for some clients more than once..

**Comment by ChristopheLux** [comment]
@grinich or changes in infrastructures with different serversnames/DNS names etc...

**Comment by valtlfelipe** [comment]
+1 I had to change my password on exchange, because it has expired (expires year to year).

**Comment by grinich** [comment]
We're definitely going to add updating password

Changing other account settings opens up a huge class of complex issues related to sync integrity and provider verifications. In the rare situations where a mail host changes domains or a hosting provider is migrated, we recommend unlinking and re-linking the account.

We've had a few users move from Exchange -> Gmail and vice versa, but it currently requires a manual reset since all the UIDs and related sync state end up changing.

**Comment by tartley** [comment]
I need to change it because I entered it wrong.

**Comment by mzehrer** [comment]
This makes the app really unusable for Exchange users. Most Exchange organisations require you to change the password in regular intervals. There should also be a notification for unsuccessful logins.

**Comment by YuriSolovyov** [comment]
Yeah, in organisations there are rules that force you to change pass over time (monthly for me).

**Comment by phytax** [comment]
Hi i tried N1 and i like it very much.
BUT if there's no way to change the passwords, and this issue is "low priority" then I think there are great problems with the development process. 
The lack of such a fundamental feature makes this client unuseable.
The only sane way to handle this is to uninstall.

**Comment by grinich** [comment]
A couple weeks ago we added the ability to update your password if login starts failing. Is that not working for you? We don't allow users to change the password is the system can still successfully connect the account. (Although you can force this by unlinking and relinking.)

**Comment by YuriSolovyov** [comment]
If you mean reconnect warning + button that pops-up an account adding UI, this is hardly an option, we need simpler UI to just enter new pass.

**Comment by bengotow** [comment]
Hey folks—we've aded a button that allows you to update your account settings (screenshot below) and the next release adds IMAP settings autocomplete for the top ~200 providers (4a738602ab21f6593e5bfdcb098634657369c0ca), and pre-populates the name / email fields when updating an existing account.

This means that for 95% of our install base, they'll only have to re-enter their password. We still don't do full IMAP / SMTP auto-discovery, which would make this less painful for the remaining 5% of folks, but we're tracking that separately here: #1045 so I'm going to go ahead and close this. Cheers!

![image](https://cloud.githubusercontent.com/assets/1037212/15694023/18d165a2-274f-11e6-83ec-d039105c82a5.png)
