### ISSUE TITLE
Outlook windowslive.com accounts do not synchronize

### ISSUE THREAD

**Issue by michalpaszkowski** [nylas/N1#1027]
Standard outlook accounts (outlook.com) are working good, but ex. nobody@windowslive.com accounts do not sync with the server.

**Comment by ntwb** [comment]
Microsoft used to offer custom domains for Hotmail, this service was migrated to work with Outlook.com

> Via https://domains.live.com
> If you previously used custom domains with Outlook.com, we still support the ability to log in to Outlook.com with your existing custom domain email address, but admins can no longer manage accounts in the domain. These accounts are still able to send and receive email, and you don’t need to make any changes. To access an account, please log in via Outlook.com.

So essentially any valid domain name e.g. example.com could be used with Outlook.com, accounts do not have to use the Outlook.com domain, eg. example@outlook.com

**Comment by kav-ya** [comment]
Thanks @ntwb! @michalpaszkowski, please let us know if you cannot login using the `@outlook.com` format.

**Comment by ntwb** [comment]
@kav-ya Looks like I explicitly forgot to mention that I am having this same problem, though I only added some background rather than to say "I'm having what I believe to be the same/similar problem :smirk: 

I've just connected successfully using a `example@live.com` email address with the `live.com` domain to N1 via the Outlook.com connector so that is one custom domain that is not the `outlook.com` domain that works correctly :smile: 

I cannot connect though with a custom domain I have, I've just tried with 3 different accounts e.g. `user1@example.com`, `user2@example.com` and `user3@example.com` by trying to connect them to N1 via Outlook.com, Exchange Server, or IMAP and I couldn't get any of those 3 accounts to connect at all.

Each of the accounts work fine here locally via the Outlook desktop (Mac), OS X Mail App or via Webmail.

**Comment by michalpaszkowski** [comment]
No, I can't login to my account replacing windowslive.com with outlook.com. It says that there is no such account.

**Comment by SalahAdDin** [comment]
Ok, i have the same problem, i can login with @live.com via outlook option, but Nylas can't syncronize with my mail. 

I don't know what happen, but, with yahoo i have't problems. Thanks

**Comment by ntwb** [comment]
Likewise, I got an email from N1 to one of the email addresses I had been trying to use with N1:

```text
Hi there-- Michael from Nylas here.

I wanted to let you know that we recently fixed a bug in N1 that was causing auth errors for generic IMAP and SMTP accounts. Our error logs show that your account was affected by this bug.

You should now be able to successfully connect via N1, and you can reply to this message if you have any feedback or issues going forward.
```

The domain that this was sent to is one of the "custom Windows Live domains" I've mentioned and it still does not work.

**Comment by ntwb** [comment]
@SalahAdDin Try setting up your @live.com account as an "Exchange Server" account, my live.com works with this setup :)

**Comment by SalahAdDin** [comment]
Ok:
![add an account_012](https://cloud.githubusercontent.com/assets/5034215/13200616/a6fef964-d81e-11e5-820b-a46d4145922b.png)

**Comment by Zabanya** [comment]
Both Outlook.com and ActiveSync Exchange gives me credential error.
(two way auth?)

**Comment by Kami-no** [comment]
@live.com - last mail in N1 dated Jan 9.
Via web-interface I've 21 letter since that time.

**Comment by arslankhalidch** [comment]
hi, i have the same issue. i can add the @live.com email account but it would not sync

**Comment by SalahAdDin** [comment]
Never sync :'(
