### ISSUE TITLE
Show an error message if nylas can't connect to an account

### ISSUE THREAD

**Issue by LukasLauterbach** [nylas/N1#1070]
I changed the password of my email account and forgot to change it in nylas, so I was wondering why nylas doesn't sync my mails anymore. Nylas should should show a message if it can't connect to an mail account.

**Comment by bengotow** [comment]
Hi @LukasLauterbach — thanks for filing this. This /should/ work, so it must be a regression in a recent release. I'll make sure we get this fixed.

**Comment by emorikawa** [comment]
@LukasLauterbach Unfortunately if you change your password with your email provider, we will no longer be able to authenticate with Nylas. Our API will return 401 unauthorized status codes, and you should see the following message:

![image](https://cloud.githubusercontent.com/assets/489001/12664627/0448ee0e-c5e6-11e5-9b81-b1bc005e306d.png)

This message only displays when you initiate a new API request and we see that its access has been denied, so if nothing is happening in the app, it won't automatically show up.

If you notice that requests are failing due to your account being unauthorized, but still don't see the status bar, please let me know.
