### ISSUE TITLE
Questions regarding privacy and project motivation

### ISSUE THREAD

**Issue by herrbischoff** [nylas/N1#1082]
Having read though a couple of issues here, researching on the net and generally reading news bits about N1, I'm increasingly worried. In most cases, there is absolutely no hint at the fact that Nylas is actually storing all of my email content along with my login credentials. A user just downloading the application and entering user information is not give notice that this is actually happening and where the data is actually stored. This popped up in my mind when I started the software, so it may be possible that somewhere down the road of the setup some notice is given. This has extremely serious implications regarding privacy and self-determined data distribution, not at least because world-wide there are many different legislations regulating what data may be stored, when, how and by whom. Therefore, I have some questions regarding your stance towards those issues, especially considering https://github.com/nylas/N1/issues/38#issuecomment-147115507 where @bengotow repeats that "Long term, we envision folks using our hosted version of the sync engine."

* Is it a business idea that you are eventually going to start charging people for that functionality at some point?
* Why would you be interested in getting access to all my email and login credentials in the first place? Certainly "ease of use" cannot be the main contributing factor here. Storing so much third-party data must be a disaster waiting to happen as long as you don't have the resources of a company like Google. Having so much data centralized at one location creates a *very* compelling target.
* What about people living in other countries, like Germany, where privacy protection laws explicitly prohibit exporting data to other countries without definite user consent. The issue gets even more complicated for a freelancer or small agency, for example, being contracted by a large corporation. Usually NDAs and contractual fine print prohibits transfer of data out of the residing country. I am aware that this also applies to webmail providers like Google Mail and in the real world is treated with a rather cavalier attitude. You certainly don't follow that attitude, do you? So what's your position on this?
* What assurances does a user have regarding the safety of his personal data?
* What reasonable course of action does a EU citizen have for finding out if you were served with a request for access to personal data? It is my impression that being US-based, in most cases you are bound by law to comply with such enforcement requests.
* What is your policy on defending the users' privacy and data against such requests?

I'm looking forward to being enlightened on those topics. The project itself is commendable and I myself would love to use it, however until all of those points have been cleared up, I'm advising against signing up.

**Comment by bengotow** [comment]
Hey @herrbischoff — thanks for checking out N1! You can find information about our security policies here: https://nylas.com/security. We do not sell or ever plan to sell user data or "aggregate email data" (ala Context.io) —there's a bit more information about why N1 is built the way it is here: https://nylas.com/N1/faq.

At the end of the day, we do store your mail data in the same way Mailbox, Accompli, and others have in the past. It allows us to build something better than IMAP / Exchange, and will make some awesome features possible in the future, like priority inbox for Exchange and great search. We tried to find ways around storing mail data, since it's costly for us and needs to be secured with great care, but it's core to building a mail client to rival Gmail and others, and essential for doing anything on mobile. (Someday!)

At the end of the day, N1 will always be free and open-source. We're committed to building a great foundation on modern technologies. Of course, we have to make money eventually - we plan to monetize N1 by building a "plugin store" into the app and selling subscription plugins and extensions. I expect most of these will be serious productivity-oriented plugins that tie N1 to CRMs, mail merge tools, etc.

Hope that helps—

**Comment by grinich** [comment]
Also just to add, if you have specific legal questions related to N1 or Nylas, feel free to email legal@nylas.com.

**Comment by herrbischoff** [comment]
@bengotow: Thanks for the answers so far, which in essence really do resolve just one question. Please see my additions below.

@grinich: why did you close this issue already? Most of my questions still remain unanswered and I believe that this should be something discussed openly. In fact, if your platform is as secure and considerate as you claim, a discussion on this topic should only increase your perceived trust by users. The N1 code, as is, ties into your hosted service and therefore the implications of this behavior need to be laid out.

* Regarding https://nylas.com/security "Nylas is Safe Harbor Compliant for both US-EU and US-Swiss standards[...]". You must be aware that as of October 6th, 2015 the Safe Harbor agreements of 2000 have been declared invalid by the European Court of Justice (see: https://www.ftc.gov/tips-advice/business-center/privacy-and-security/u.s.-eu-safe-harbor-framework). **Are you going to take action to ensure EU users are granted their extended rights to privacy?**
* Since you appear to run your service on AWS, the easiest course of action to get around some of my raised issues would be to enable running instances exclusively in EU data centers, which are located Ireland and Germany. **Is this something you will consider?**

These questions are still open:

* **Why would you be interested in getting access to all my email and login credentials in the first place?** Certainly "ease of use" cannot be the main contributing factor here. Storing so much third-party data must be a disaster waiting to happen as long as you don't have the resources of a company like Google. Having so much data centralized at one location creates a very compelling target.
* What about people living in other countries, like Germany, where privacy protection laws explicitly prohibit exporting data to other countries without definite user consent. The issue gets even more complicated for a freelancer or small agency, for example, being contracted by a large corporation. Usually NDAs and contractual fine print prohibits transfer of data out of the residing country. I am aware that this also applies to webmail providers like Google Mail and in the real world is treated with a rather cavalier attitude. You certainly don't follow that attitude, do you? **So what's your position on this?**
* **What assurances does a user have regarding the safety of his personal data?**
* **What reasonable course of action does a EU citizen have for finding out if you were served with a request for access to personal data?** It is my impression that being US-based, in most cases you are bound by law to comply with such enforcement requests.
* **What is your policy on defending the users' privacy and data against such requests?**

Thanks in advance for taking the time to answer those remaining questions.

**Comment by herrbischoff** [comment]
@bengotow @grinich Any news on this?

**Comment by grinich** [comment]
hi @herrbischoff -- I closed it because we use this repo to track bugs related to the code development of N1

Can you send me a note via support@nylas.com and I can Skype you? I don't have a ton of time and I think taking this synchronous would be way faster at answering your concerns.

**Comment by fridays** [comment]
I am interested in these answers as well! Please keep the discussion public.

**Comment by darius-r** [comment]
@herrbischoff Where you able to speak with Grinich?

The near evasiveness of this overwhelmingly important issue is troubling at best. This should _not_ be closed until the questions are answered or we are pointed towards sufficiently thorough answers somewhere else. 

You offer no public forum, so you might just have to deal with this topic be handled here.

**Comment by nythng** [comment]
I'm as well really interested in this topic and some more insightful answer from the Nylas Team.

Please keep this discussion open!

**Comment by grinich** [comment]
Hi folks. I never got a follow-up from @herrbischoff and found a free hour to write this up. 

Here’s a few answers to hopefully shed light on our cloud sync system. Thanks for your patience! 

We’re planning to start charging people to use our hosted cloud sync, since it costs us money to provide the infrastructure. We're not looking at other business models that sell the data (even aggregate data). The price will be pretty reasonable-- think GitHub for private repos, or a DigitalOcean droplet. Of course, you can always run the sync engine yourself since it’s open source GPL free software.

The Nylas N1 product depends on our cloud sync system in order to provide features like snoozing, send later, and more collaboration tools we plan to launch later this year. You can’t reasonably build these things without having access to the data layer from a server component. It's also the "heavy lifting" part of the system, and allows N1 to be faster and compatible with more providers.

This isn't uncommon. Most modern email apps use a cloud sync component. e.g. Mailbox, Accompli, Cloud Magic, Polymail, and Spark by Riddle.

We know this architecture has different security implications, and we’ve worked from the start to make a secure system. You can read what we've published here: https://nylas.com/security 

Regarding international users: Nylas is an American company based in San Francisco, with our primary data center in the USA. This means we are subject to any and all US laws and regulations. 

We recognize the need for some users to have data stored outside the US, but as a small company we can’t actively manage this right now (for either N1 or the API platform customers). We definitely plan to someday open a data center in Europe (& elsewhere!), but we don’t have the volume right now to justify spending time on it.

We encourage folks who have this as a hard requirement to instead run the open source sync system themselves on a hosting provider they trust. It doesn't phone home or transmit data to us in any way.

We know the cloud sync architecture we’ve picked can’t satisfy everyone’s needs. And that’s fine— there are other products out there with different pros and cons. It’s our hope that by open sourcing our code under a libre license, and also being straightforward about the business we’re building, others who can't use N1 will still be able to benefit somewhat from our work. Even if that's only to experiment with the platform, or check out a reference-implementation of a large JavaScript desktop app. (I think we might be the the biggest React+Flux based app built on Electron!)

I can say right how that we haven’t received any government or law enforcement request for data. This actually makes sense, since we’re not the primary mail store. These requests instead go to the mail provider (i.e. Gmail, Yahoo, MSFT, your ISP, etc.). 

Probably the biggest “assurance” you have for us safely storing  data is that we have the same thing at stake as our users. Any breech would be extremely damaging to Nylas and our future as a company. It’s critically important for us to do everything we can to prevent that.

On the other hand, none of this will matter unless we continue to build a product that people love and want to use every day. The majority of our team spends their time creating new features, improving performance, fixing bugs, and generally working to make N1 the best email app out there. 

Right now we have over 500 issues on GitHub and tens of thousands of developers actively experimenting with the N1 platform. I hope you won’t mistake evasiveness for instead simply not having enough time to talk with everyone. 

And if you know folks who want to work on this, we are actively hiring! :smile:  https://jobs.lever.co/nylas

**Comment by briatte** [comment]
Dear all,

Thanks to @herrbischoff for getting the ball rolling.

I just discovered Nylas, and it looks like a tremendous product.

Here's the exhaustive list of what I would need to stick with it, by order of priority:

1. __Clear privacy statement__
2. Important / Starred / Unread
3. Multilingual (or disabled) spell checking

Please keep the discussion public.

**Comment by grinich** [comment]
hi @briatte -- What questions do you have that haven't been answered above?

We're working on an [important/starred/unread](https://github.com/nylas/N1/issues/200) view and also [multilingual spell checking](https://github.com/nylas/N1/issues/1392).

**Comment by briatte** [comment]
> Thanks for the kind words!

You're welcome.

> What questions do you have that haven't been answered above?

I didn't have any questions in the beginning: I just did not know what I was signing when I started using the app. I found this thread by serendipity. The issues it raises and answers should be shown in a plain-language statement when the app is launched for the first time, or better, every time that a new account is added. At least in my opinion.

Will have a look at the thread you mentioned. Looking forward to the next release in all cases.

**Comment by batkmme** [comment]
I just found Nylan.  It looks great but I am concerned like others.  It would be nice if this was opt in feature.  I am not sure why this issue is closed, that doesn't seem very open.  I am glad I found it before downloading.

**Comment by grinich** [comment]
For other folks referencing this thread, I definitely recommend you also check out our help center article for [Why does Nylas N1 sync email via the cloud?](https://support.nylas.com/hc/en-us/articles/217518207-Why-does-Nylas-N1-sync-email-via-the-cloud-).

**Comment by grinich** [comment]
Just to post a quick update here: our new version of Nylas Mail ([announced here](https://blog.nylas.com/nylas-mail-is-now-free-8350d6a1044d)) now syncs data locally and directly with your mail provider.

**Comment by useretail** [comment]
@grinich but still phones home, right?

**Comment by skywalker89** [comment]
@useretail  does it or not, that is my question! any idea? thx
Dan

**Comment by useretail** [comment]
@skywalker89 of course it does. see (in)complete list at #1849

**Comment by skywalker89** [comment]
ok thx...moved back to TB

**Comment by dtsitses** [comment]
@grinich thanks for taking the time to explain all this.

Accessing user data to enable the described features makes sense. The thing is, there is a ton of users who want to own their data and no matter what features you add, they won't change their mind. Personally I would pay money for an awesome email client that doesn't phone home, I believe many others would. You see, a lot of people feel that giving up their data is actually a cost, a much much bigger cost than paying for software.

If I may propose a solution that would make a lot of people happy: add a switch on the app so people who value their data, can just disable all features that raise privacy concerns. Singing up to the sync engine and giving you personal data and login credentials should be absolutely optional. Search will be less powerful, especially on mobile, but for many this is a tiny price to pay. Give users options that matter to them and they'll love you and the product for it. For every message you get here on this thread, there is a big crowed behind who is less vocal, but still abstains from the product. Why miss out on all these people? Users who value their privacy is a big market, it can pay dividends to address it.

Thanks

**Comment by dtsitses** [comment]
@grinich btw, is there a link by any chance that explains how to run the open source sync system on our own host?

Thank you

**Comment by Razva** [comment]
Installed. Setup 7 accounts. Enjoyed for ~5 minutes. Couldn't empty Trash or Spam. Checked #599 . Facepalmed. Uninstalled. Got back to AirMail.
