### ISSUE TITLE
STARTTLS Support for University of Waterloo IMAP

### ISSUE THREAD

**Issue by andrewparadi** [nylas/N1#1110]
No TLS available that I can find, means I can't hook up to my university email or to other less common email providers. Full settings here: https://www.reddit.com/r/uwaterloo/comments/15lw6w/ Unfortunately UWaterloo is redoing their tech site so the official instructions aren't there anymore but this works in my other mail clients.

**Comment by bengotow** [comment]
Hi @andrewparadi — do you happen to know if your IMAP / SMTP username is the same as your full email address? I think there's a known issue with the sync-engine where it sends the email address as the username, instead of the username you provided. I believe @kav-ya is working on a fix for that.

As far as I know, we try TLS by default so that may not be the issue.

Related: #954

**Comment by andrewparadi** [comment]
Ah that must be the error. The username doesn't include the "@uwaterloo.ca" so when that sync-engine fix gets pushed it hopefully will get resolved. Thanks for the quick reply!
