### ISSUE TITLE
Periods are sometimes missing

### ISSUE THREAD

**Issue by ThePsionic** [nylas/N1#1114]
Occasionally, I come across e-mails where some sentences are missing a trailing period, or web links like http://githubcom instead of http://github.com. It's not a major PITA except when it occurs on links, in which case you need to add the period yourself (meaning that it also happens in the href attribute of a link).

**Comment by grinich** [comment]
And then it shows up like this in the actual message:

![image](https://cloud.githubusercontent.com/assets/92417/12523487/0f49ddba-c10c-11e5-892c-025b6d8e2fd5.png)

**Comment by ThePsionic** [comment]
Well, there ya have it ;D

> On Jan 22 2016, at 10:28 pm, Michael Grinich
&lt;notifications@github.com&gt; wrote:  

>

> And then it shows up like this in the actual message:

>

> [![image](https://cloud.githubusercontent.com/assets/92417/12523487
/0f49ddba-c10c-11e5-892c-
025b6d8e2fd5.png)](https://cloud.githubusercontent.com/assets/92417/12523487
/0f49ddba-c10c-11e5-892c-025b6d8e2fd5.png)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1114#issuecomment-174054153).![](https://github.com/notifications/bea
con/AAzZYEofCjECJHE_Jtk4GLKOb_u47p-Jks5pcpaTgaJpZM4HKsnt.gif)

**Comment by bengotow** [comment]
Wow - looks like we removed three periods? We'll take a look and see if we can track this down.

**Comment by bengotow** [comment]
This has turned out to be quite fascinating. It looks like viewing the corresponding email in Inbox by Google also shows it with no periods:

![image](https://cloud.githubusercontent.com/assets/1037212/12663697/1aa04eec-c5df-11e5-97a8-edc2ae86e52f.png)

(This is the email which was sent to me when you filed the issue.)

I have no idea what's going on, but I think it's safe to say this is an issue outside N1 if it appears broken in Inbox as well. Maybe Github is doing some whacky sanitization? Closing for now.

**Comment by mbilker** [comment]
Does viewing the raw message show the periods?
