### ISSUE TITLE
Bug report: emails duplicate or disappear when using google app password

### ISSUE THREAD

**Issue by scani** [nylas/N1#1123]
As a measure of security, I usually use a specific app password randomly generated by google instead of the actual password of my account (this feature is available by the link https://security.google.com/settings/security/apppasswords if you use two-factor auth. in your account). So when the N1 starts, I choose IMAP SMTP set up, write imap.gmail.com and smtp.gmail.com and use this special password. After that, N1 loads all emails in many copies and if I try to send a new message to myself, it either disappears or copies itself several times. Is this way actually more secure or signing in via browser may be good enough?
Ubuntu 15.10 64bit

**Comment by grinich** [comment]
hi @scani -- we use Google's [OAuth2 mechanism for authenticating Gmail accounts](https://developers.google.com/gmail/oauth_overview?hl=en) which actually does not require sharing a user password with us. When when you click the "Gmail", the app will switch to your browser and prompt you to grant permissions for Nylas to sync your mailbox. 

We think this is a more secure way to authenticate an account, since it's faster than creating app-specific passwords and allows you to easily revoke the OAuth token at any date. Are you able to connect your account by clicking "Gmail" in N1? Again, your actual password is never shared with Nylas here.

(Relatedly, I think our sync engine has some bugs related to syncing a Gmail account with non-OAuth since we have special sync code for Gmail.)

**Comment by scani** [comment]
Of course I can connect to my account the usual way, but I just had to try.
Thanks for quick reply.
