### ISSUE TITLE
Exchange / Debian Client : Download mails to the pc

### ISSUE THREAD

**Issue by jrcolroadom** [nylas/N1#1132]
it could be very nice, ( i dont know if n1 has it alredy) download the arriving mails to a folder or something like a outlook pst, the company exchange mailbox has a poor space limit.

edit: a feature to download the mails to a offline/directory/folder file in order to do not saturate the mail space from the server site; like Thunderbird and Evolution does

**Comment by bengotow** [comment]
Hi @jrcolroadom — thanks for checking out N1! Right now, N1 is backed by the sync-engine, a separate open source project that interfaces with Exchange, IMAP, Gmail, etc. The sync-engine caches mail data so that we can index it for our own endpoints, but it's built on the assumption that the mail data will still be available on the remote server.

I think we could potentially extend N1 so you could view emails not on your mail server or on the sync engine anymore, but since everything in the app (including search) is powered by the sync engine, you wouldn't be able to do much of anything with the mail! We'll definitely try to revisit this in the future, but I'm going to close it as a wontfix for now.
