### ISSUE TITLE
config.cson gets wiped when running specs from main window

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1133]
I have had issue, #1019 because I changed the password on gmail. I wanted to unlink and relink the account to start the sync again. When I did that, nylas removed all other email accounts as well and reset to getting started screen.

Reproduction Steps:

0. Have multiple email accounts setup on N1. (I had gmail and Microsoft Exchange accounts, personal and work)
1. Manage accounts -> Select Gmail account -> click on - button at the bottom of the screen.

(2. My system turned off (lost power) after this step)

When I restarted, I got welcome to N1 screen.

**Comment by mbilker** [comment]
Just so you know. All my accounts were removed after I forcefully stopped the spec tests.

**Comment by bashok001** [comment]
That might be another reason. I was running spec tests just before doing this account management.

**Comment by emorikawa** [comment]
We just changed a bunch of the account creation / deletion logic with recent unified inbox changes. We'll look into this issue in our testing to make sure it's not still around.

**Comment by jstejada** [comment]
Hey @bashok001 , I haven't been able to reproduce this on the latest master. Anything else I should look out for?

**Comment by bashok001** [comment]
@jstejada Did you try to forcefully stop N1 specs? as observed by Matt

**Comment by mbilker** [comment]
It seems it corrupts the `config.cson` sometimes. I actually watched this happen when upgrading to the latest beta with unstable internet. The DB was intact, but the `config.cson` was gone.

**Comment by jstejada** [comment]
Hey, so I've also noticed that config.cson gets wiped on occasion when running the specs from the window, so I'm going to rename this issue. 
In the meantime you can run the specs via `./N1.sh --test`.

**Comment by dani-z** [comment]
Hi guys, this happened to me too. I had to force restart my computer and when I logged back in I had to do the first time setup wizard. Any way I can get back the accounts / preferences without creating them again? Thanks

**Comment by mbilker** [comment]
@dani-z Sorry for responding so late (I have been busy). Unfortunately, the config file is wiped and cannot be restored unless you have backups enabled and could go back to an earlier revision.

**Comment by tino** [comment]
I had the same problem: I removed an account after I was given a warning that the credentials were invalid, the N1 screen disappeared and after clicking on the Dock icon the getting started wizard appeared. `config.cson` is gone. Version `0.4.5-b0ec335`

**Comment by mbilker** [comment]
@tino That is not the same issue. This is referring to running `Developer -> Run N1 Tests`

**Comment by tino** [comment]
@mbilker ah all right. I responded to the original post from bashok001, I guess this took off on a tangent though (and I see the issue was renamed from "nylas reset to zero accounts on removing one"). So should I file a new ticket being about  "nylas reset to zero accounts on removing one"?

**Comment by bengotow** [comment]
Hey folks! Just wanted to post an update here. After a bit of digging, it turned out that some application state wasn't being set properly when you ran specs within the app (running from the command line works fine, which is why our team didn't notice for a while!) When the specs covering preferences and account management run, they were actually wiping your real account preferences.

I've pushed a small patch that ensures specs always run with a different "configDirPath", ensuring that they can't stomp all over your settings.

Sorry to everyone who was impacted by this issue—re-linking accounts really sucks. In the future, we'll see about more completely mocking the filesystem so that specs don't ever actually write to disk. (I'm actually surprised to find that they do, but that may be a broader fix.)
