### ISSUE TITLE
Option to open attachment directly (rather than download them to file system)

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1141]
Would be nice to 1 click open attachments.

**Comment by bengotow** [comment]
Hey! Hmm—does it work if you double-click them?

**Comment by jweinstein** [comment]
Ah, yes. I'm just stupid. When I saw the highlight state I thought it was 1 click I guess. Close issue.

**Comment by orschiro** [comment]
Dear all, 

I faced a similar confusion. 

May I suggest to add another visual button (besides "Download") that shows an eye symbol to indicate that the file can also be viewed directly instead of be downloaded before.

![image](https://cloud.githubusercontent.com/assets/170947/14775504/f4a43246-0abf-11e6-8b87-267eaa73515e.png)

Thankfully,

~Robert
