### ISSUE TITLE
Email rules does not work properly [mail rules]

### ISSUE THREAD

**Issue by jvanz** [nylas/N1#1162]
The email rules does not work properly, label are being applied in wrong emails. See:

![rules](https://cloud.githubusercontent.com/assets/1514798/12693608/d5a2cd0c-c6f5-11e5-84ff-5631fee2699b.jpg)

![email](https://cloud.githubusercontent.com/assets/1514798/12693610/da559e24-c6f5-11e5-8950-5342e31d9eda.jpg)

The `Social` label is being applied in a wrong email

**Comment by bengotow** [comment]
Hey @jvanz — we haven't been able to track this down yet, do you know if there's any particular combination of rules that causes the problem?

**Comment by jvanz** [comment]
Hi @bengotow 

Sorry for delay. I tested in the newest N1 version (0.4.5-b0ec335) and the issue still exists. I do the following test:

1. Create a new "Update" label
2. Create a rule filtering email which the "from" field ends with "stackexchange.com". As the action, it applies the label "Update" 
3. Process all mail

Many email messages were filtered incorrectly
![email_rule](https://cloud.githubusercontent.com/assets/1514798/12944605/54367f06-cfcf-11e5-8bd6-2f5d99b0f8e3.png)

**Comment by bengotow** [comment]
Hey folks! We identified a big issue with the "Process All Mail" action in 0.4.19 and below, where the app was advancing through your mailbox by "page", but the pages would change underneath it as it modified mail. This caused it to skip some threads. Classic `for (i = 0; i < x.length; i++) { delete x[i]; }`  issue :-). 

Should be fixed in 0.4.25.
