### ISSUE TITLE
Feature Request - Plugin without sync-engine

### ISSUE THREAD

**Issue by gautamsi** [nylas/N1#1187]
Hi N1 community,

I am developer of [ews-javascript-api](https://github.com/gautamsi/ews-javascript-api). This library is written in TypeScript and can be used in Node/Electron/Browser/ I would like to build a demo app for my library. it will also serve as showcasing its capabilities. I came across N1 and when looking for Electron based email clients, Instead of writing whole new App on itself I would like to create N1 plugin which would work with Exchange Web Service directly without the need of sync-engine.  

Can you provide some guidance on how can I start working on such plugin which can bypass sync-server and provide data by calling directly through server? 

What other option I have? I do see several requests for EWS, may be this one can help.

**Comment by grinich** [comment]
You probably need to write your own API-compatible sync engine that uses EWS and run it locally, since the entire app's flux stores are powered by SQlite3 databases. 

We're not planning to add this to N1, so I'm going to close it as an issue. But please feel free to fork the project and go after this! Sounds very interesting. :+1:
