### ISSUE TITLE
Onboarding doesn't include box for invite code

### ISSUE THREAD

**Issue by jackiehluo** [nylas/N1#119]
I've tried expanding the window, scrolling, pressing tab and entering the code in the dark, and more, but I can't access the box for the invite code. After I press through the third onboarding panel, the whole window minimizes, and I can see the invite code box for a split second before it's out of reach. Below is all that I can see:

![screen shot 2015-10-21 at 11 26 13 pm](https://cloud.githubusercontent.com/assets/8452682/10656279/31fbec22-784b-11e5-8877-614932540f41.png)

**Comment by aganzha** [comment]
same here

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - it looks like it's a timing issue,
and happens when the server responds right as you proceed to the invite
screen (when the page is animating).

We're working on a fix - in the meantime, if you launch the app and wait
for ~5 seconds before moving through the welcome screens, it should work
fine.

Hope that helps!

**Comment by jackiehluo** [comment]
It still doesn't work if I wait five, ten, seconds between each screen, but I'll wait for a fix!

**Comment by bengotow** [comment]
Hi folks—sorry for the hassle. We pushed out a fix for this a few minutes ago. Try downloading the latest release and let me know if it resolves the problem for you!

Mac: https://edgehill.nylas.com/download?platform=darwin
Win: https://edgehill.nylas.com/download?platform=win32
Linux: https://edgehill.nylas.com/download?platform=linux

**Comment by jackiehluo** [comment]
Perfect. Loving it so far. :100:
