### ISSUE TITLE
Removing /.DocumentRevisions-V100 removes all nylus settings

### ISSUE THREAD

**Issue by serieseight** [nylas/N1#1193]
I removed /.DocumentRevisions-V100 to clear some cache issues with Sketch App https://medium.com/@thomasdegry/how-sketch-took-over-200gb-of-our-macbooks-cb7dd10c8163#.uvr82zrxy and this caused all my mail settings to wipe out.

I know you're not suppose to delete that file but removing this file to clear cache does't have the same effect on other mail clients

**Comment by emorikawa** [comment]
@serieseight which mail settings? Did it have to re-sync all of your mail.
I can't off hand imagine how removing that folder would affect Nylas.
We store all of our data in `~/.nylas`. As long as you don't remove that folder we should keep all of your data.

**Comment by serieseight** [comment]
I had to re-sync google mail. Wierd it did that for me. All I did was sudo rm -R /.DocumentRevisions-V100

**Comment by emorikawa** [comment]
Ah, so `/.DocumentRevisions-V100` is tied to Apple's version control system. It's possible that deleting that caused the version control system to revert or update other files that it was tracking (including Nylas files). Since we're pretty heavily dependent on the file system to store your offline cache, and since it should automatically restore itself, and since `sudo` removing a core Apple system file is a pretty rare event, I'm inclined unfortunately to files this as a "wontfix". If this continues to happen for other reasons, please let me know and re-open this issue.
