### ISSUE TITLE
Changing the font in the compiled binary version

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1228]
I've been compiling the source version of N1 to try out new features and change the font. I prefer using the San Francisco system font over Fakt (a fine font – I just prefer my email in SF UI). However, having to run N1 from the terminal and keeping up with upstream changes is a bit of a hassle.

Is there any way to change the font in the compiled binary version? I can't seem to find the stylesheet that I've been editing in the compiled package.

(Low priority)

**Comment by mbilker** [comment]
The locations of the Nylas-Pro font are at:
[internal_packages/screenshot-mode/assets/font-override.css](https://github.com/nylas/N1/blob/d61becc549a1cb6aedcac6891d328f3b63f65601/internal_packages/screenshot-mode/assets/font-override.css)
[static/email-frame.less](https://github.com/nylas/N1/blob/58ded66962435878debbebb4c326a5de363ce2c9/static/email-frame.less)
[internal_packages/print/static/print-styles.css](https://github.com/nylas/N1/blob/bdfd96fed2a936faaf614628da4358e235c2f78f/internal_packages/print/static/print-styles.css)
[static/variables/ui-variables.less](https://github.com/nylas/N1/blob/ceb9e2cdb1fc574dfd748cfd403502fa4449fd2e/static/variables/ui-variables.less)
[src/canvas-utils.coffee](https://github.com/nylas/N1/blob/3a16484d7dd530b0b618cd079ac54d68b1428554/src/canvas-utils.coffee)

The font declaration is in `nylas-private-fonts`, which is only part of the compiled binary version.

**Comment by mbilker** [comment]
If you override these, you can in `~/.nylas/styles.less` (from [src/style-manager.coffee](https://github.com/nylas/N1/blob/51602f69a54ee11b72e624ba7e63503f329a75d1/src/style-manager.coffee#L162-L167)).

**Comment by markbao** [comment]
Fantastic! Thank you.

**Comment by cfriedline** [comment]
@markbao would you mind providing an example of your styles.less file?

**Comment by romantolkachyov** [comment]
@cfriedline you can start from any theme you want (I choose ui-ubuntu) following https://github.com/nylas/N1-theme-starter

To change font-family globally you must add this lines to your themes index.less:

```
body {
	font-family: Helvetica !important;
}
```

But it doesn't affect font in message view because it is in iframe. Trick is to create file styles/email-frame.less in your new theme with iframe font styles (I'd copy original file https://github.com/nylas/N1/blob/master/static/email-frame.less and had change font-family in it). To make this file work you must add this line in your themes package.json:

`  "styleSheets": ["email-frame"],`
