### ISSUE TITLE
Allow mass archive

### ISSUE THREAD

**Issue by borisrorsvort** [nylas/N1#126]
Would be nice to be able to mass archive after a search or just multi selection

**Comment by bengotow** [comment]
Hey! Thanks for downloading N1. We're working on abstract selection concepts so that it's easier to implement actions like "select these 20,000 messages". You can currently multi-select items by shift-clicking them, command/ctrl clicking them, and also using the shift+arrow keys. We'll definitely add additional multi-selection controls once we support select-all.

I've added a ticket to our open-source roadmap so you can track the progress on this—feel free to upvote it there if you have a Trello account! https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by borisrorsvort** [comment]
:+1:  but what about archiving ? Would that go with the addition of shortcuts ? Or drag and drop to archive box (not there right now)?

**Comment by tommydangerous** [comment]
Has this been implemented?
