### ISSUE TITLE
Feature request: be able to archive in All Mail

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1295]
I use All Mail as a way to see all my mail across my labels, and sometimes there are emails that are in my inbox that I'd like to archive. So it would be good to allow archiving while in All Mail. I think this is something that other clients do, but I can't be totally sure.

**Comment by bengotow** [comment]
Hi @markbao —I think the behavior of All Mail is pretty confusing currently, and we might be doing it wrong. Opening this up to a bit of a broader conversation about that. Here's the behavior as far as I know:

In Gmail:
- Inbox and All Mail are exclusive. All Mail is defined as "all the email /not/ in your Inbox."
- If you're looking at a thread in your Inbox and click "Archive" it goes to All Mail. There is no Archive label.

In N1: 
- The unified "All Mail" perspective shows you the contents of "All Mail" in Gmail, combined with any "Archive" folders from other accounts.
- All Mail does not actually show you all of your mail.
- You cannot archive from All Mail, because archiving moves mail **to** "All Mail" in Gmail or "Archive" in other accounts.
- The sidebar only shows "All Mail" as the name of the unified folder if your first account is a Gmail account. If you re-order your accounts so that an Exchange / IMAP account is first, you'll see "Archive". This is sort of a bug.

I'm not totally sure what we should do about this. Here are some ideas: 

- I think that we should change the unified "All Mail" item in the sidebar to read Archive, since it is where things go when you archive them.
- I think the perspective you really want is a true "All Mail", which shows all of your mail no matter where it is (spam + trash + inbox + everything?). This perspective does not exist, but adding it and calling it All Mail would be super confusing.

**Comment by bengotow** [comment]
(cc @grinich)

**Comment by bengotow** [comment]
Hey! The issues above have been largely resolved in the latest release, thanks to improved logic that decides which actions are possible for given thread(s), and better handling of spam and trash, which are folders in Gmail and not actually labels.

Give version 0.4.14 a try and feel free to re-open if the issue persists.

**Comment by markbao** [comment]
@bengotow Excellent! Had no idea this was one of the changes in 0.4.14. I can confirm that this is resolved. Thank you for your attention to this.

**Comment by kareem** [comment]
Hi @bengotow Not sure if the fixes you talk about about in the 0.4.14 release resulted in this: 
* "Archive" no longer removes the label you are currently viewing.

IMHO this is undesirable.  I use Sanebox which algorithmically chooses certain emails to skip the inbox and applies a "Sanebox" label to them.  In previous versions I was able to hit `e` to archive the email and they'd have the label removed and would indeed be archived.  But after 0.4.14 it's a multi-step process to remove the label.  Any thoughts on a better way to approach this?  

(BTW not sure if this should be a new issue or not; happy to create one.  Thx)
