### ISSUE TITLE
Feature request - "Delete" email with gmail accounts

### ISSUE THREAD

**Issue by mchiang0610** [nylas/N1#13]

**Comment by dillonforrest** [comment]
Hey @mchiang0610, thanks for downloading N1 and sharing this issue! We still have implementing Gmail delete on our backlog!

Just to clarify, if you wanted to archive your mail and remove it from your inbox, our current UI is set up so that you have to select a thread or threads first. After that, action buttons appear up top for you to archive, apply a label, etc. Hope that helps as well!

**Comment by bengotow** [comment]
Hi @mchiang0610 I've added this as an open issue to our roadmap Trello board (https://trello.com/b/hxsqB6vx/n1-open-source-roadmap) and we're working on it now. Thanks - stay tuned.

**Comment by hugorodgerbrown** [comment]
+1 for this - I prefer to delete junk mail rather than archiving / moving out of inbox.
