### ISSUE TITLE
Getting .deb on ArchLinux

### ISSUE THREAD

**Issue by prog666** [nylas/N1#130]

**Comment by bengotow** [comment]
Hi there—thanks for filing an issue. Can you clarify the problem you're running into? I'm not familiar with ArchLinux, but we do provide a `.deb` version of the installer.

**Comment by prog666** [comment]
ArchLinux cannot use .deb packages, arch uses AUR (arch user repository) for this kind of purposes

**Comment by bengotow** [comment]
Ahh gotcha—that makes sense. Is it possible to build AUR packages on non-ArchLinux machines? If we could get the packaging working on our existing linux CI server, I think it'd be straightforward to maintain.

If you want to give it a shot and submit a pull request, it might not be too hard to adapt the https://github.com/nylas/N1/blob/master/script/mkrpm to create a "mkaur" script we can run!

**Comment by pebs74** [comment]
.deb packages can be installed with a workaround using either "debtap" (AUR) or "alien_package_converter" (AUR), although some problems with other .deb package dependencies occur. Even so, I've been able to install and run N1 correctly in Arch.

**Comment by prog666** [comment]
I've installed from source already too

**Comment by shibumi** [comment]
@prog666 I am currently working on a PKGBUILD for N1. I will upload it to the AUR soon.

**Comment by PlugaruT** [comment]
Will be awesome to have this very very nice app available on Arch!

**Comment by shibumi** [comment]
It would be awesome if someone of the Nylas people could send me an invitation code for testing purposes:

christian.rebischke@tu-clausthal.de

**Comment by oblitum** [comment]
@shibumi please update this thread when you do it? I'm currently waiting for a pacman package to show up, I'm not willing to build from sources at the moment.

**Comment by stouf** [comment]
@oblitum Not sure "pacman" is what you wanted to type, but don't expect a N1 package to land on the official repositories anytime soon (well, who knows but...). You probably wanna have a look at [AUR](https://aur.archlinux.org/) for the moment ;-)
And talking of which, it apparently landed yesterday on AUR :) 
==> https://aur.archlinux.org/packages/n1/
@shibumi Is that you? 

I'll try it as soon as I get my hands on a compuer (in a few hours)

**Comment by shibumi** [comment]
@stouf nope, my package is named n1-git. seems like the other maintainer is using the .deb package. It would be nice if somebody could check that package. I get X.org errors while executing it (mentioned here: https://github.com/nylas/N1/issues/183)

**Comment by oblitum** [comment]
@shibumi going to try it now thanks. (By the way I meant AUR)

**Comment by oblitum** [comment]
@shibumi it took a gigantic time to install (js is sooo slow to compile...), but after that I'm left with no idea where it was installed. I can't execute it simply calling N1.sh nor can Gnome find anything N1/Nylas related.

**Comment by stouf** [comment]
@oblitum @shibumi 

Same for me; a lot of time to install, and it required a lot of resources as well. In the end, I couldn't find the command supposed to launch the app either.

Regarding the package [`n1` on AUR](https://aur.archlinux.org/packages/n1/), it worked just fine on my environment.
One issue though: I wanted to run the server locally (see [here](https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine)); I could get it done, but it seemed like the client was still using the server(s) hosted by Nylas instead of the local one. I don't know yet if it's code related or package related, need time to investigate.
Also, sorry to say so, but installing the `n1` package was way faster and lighter than installing `n1-git`... =/

**Comment by shibumi** [comment]
@oblitum normally it should work with executing n1.sh seems like I have some bugs.. didn't really tested it. I also recommend https://aur.archlinux.org/packages/n1/ . Although extracting from a .deb package is maybe not the best way. There is also no 32bit support. 

@stouf of course is the `n1` version faster. It' a binary package. `n1-git` is downloading all js dependencies and is building the binary first. My `n1-git` package is also only a prototype.  I must modify it a lot.

**Comment by mbilker** [comment]
@shibumi I am willing to take over both packages.

**Comment by sergeyklay** [comment]
Installing a .deb package on ArchLinux - http://unix.stackexchange.com/questions/83540/installing-a-deb-package-on-arch-is-it-possible

**Comment by shibumi** [comment]
@mbilker  I have orphaned the package just adopt it. Be fast or someone else will do it.

**Comment by mbilker** [comment]
Hey. Since we have a `n1` AUR package at https://aur.archlinux.org/packages/n1. I am going to close this issue as that package uses the official deb.

I have `n1-git` at https://aur.archlinux.org/packages/n1-git which uses the official master to build the open source version (missing proprietary sounds, fonts, and analytics).
