### ISSUE TITLE
Zoom levels - could we maybe add 70% too, or custom values?

### ISSUE THREAD

**Issue by darrenkenny** [nylas/N1#1322]
On my screen (a small one these days) I find that 80% zoom is too big, and 60% is too small (at least in the message view area). 70% would probably be a better value - but it seems that I can't
specify that value in the config.cson file since the schema doesn't permit it, and it keep defaulting to 100% then :(

I'm only starting with N1, but so far, really liking the interface and the ability to configure my own
private sync since my company doesn't permit using external servers for e-mail.

**Comment by molstrangler** [comment]
I think a slider would be better.  I now have an issue after a recent update reduced the size of the fonts to fit the overall design.  I had to go to 140% which is just too much for my laptop, the message list becomes too big for my liking and the message smaller and should be the focus.

**Comment by bengotow** [comment]
Hey folks! We've decided to remove this option from N1's preferences UI and make it strictly a configuration option. It causes small visual issues we don't have the bandwidth to support (for example, the underline beneath misspelled words becomes invisible beneath a certain zoom level, causing users to think spellcheck is broken!)

In the next release, we'll be making it accept any integer value (default: 1), so that you can get it just right, and documenting it here: https://github.com/nylas/N1/blob/master/CONFIGURATION.md#other-config-options

Hope that helps! Cheers,

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!

**Comment by JotaC** [comment]
Hi @bengotow, modifying this line (core.workspace.interfaceZoom:) doent´s work anymore. Everytime you select a message, the scale resets.
