### ISSUE TITLE
Forward message from different account with attachment causes error

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1341]
1. Receive message with an attachment
2. Click forward
3. Change "from" address to a different account
4. Click "send"
5. See 400 error in activity console

**Comment by bengotow** [comment]
Hmm I don't think we should actually allow you to choose another from address in this scenario—maybe we need to check for the presence of a `threadId` rather than `replyToMessageId`? We could also add support, but we don't currently guarantee that all the original attachments have been downloaded...

**Comment by bengotow** [comment]
This commit fixes #1341, but places two additional restrictions on switching accounts while drafting to protect against us needing to download attachments we don't necessarily have and re-upload them. Perhaps we could write code for this someday.

- You cannot switch From: accounts if the draft was retrieved from the sync engine (authored via Gmail or via another copy of N1. The sync-engine gives drafts a non-null threadId)

- You cannot switch From: accounts if the draft is a forward from an existing thread.
