### ISSUE TITLE
Nested labels missing (gmail)

### ISSUE THREAD

**Issue by bellebethcooper** [nylas/N1#1346]
In version 0.4.5-b0ec335 (0.4.5-b0ec335), my nested labels have disappeared. I see the top-level labels, but any labels nested under those aren't showing up at all in Nylas. I've trying disconnecting and reconnecting my Gmail account with no luck.

I can add those labels to messages—I just can't see them in the sidebar.

**Comment by bengotow** [comment]
Hi @bellebethcooper — are there small disclosure triangles to the left of the labels? I think in v0.4.5 we changed it so that these are collapsed by default. You might need to click the triangles to open them.

**Comment by bellebethcooper** [comment]
@bengotow Nope, not that I can see. Screenshot attached.

<img width="199" alt="screen shot 2016-02-17 at 8 26 36 am" src="https://cloud.githubusercontent.com/assets/4826241/13091646/50b74690-d550-11e5-9c7d-e676bc654ec7.png">

**Comment by bengotow** [comment]
Thanks @bellebethcooper — I'm going to file this with our platform team and we'll see what's going on.

**Comment by bengotow** [comment]
Hi @bellebethcooper — I talked to our team about this and it looks like our backend imported your labels correctly, so the issue is probably in N1. Can you choose `Developer => Toggle Developer Tools` from the menu? It'll open the standard Chromium Developer Tools. At the bottom of that panel, there should be a small console. Can you run this command there and copy out the list of label names it gives you?

`$n.CategoryStore.categories().map(cat => cat.displayName)`

I expect that many of your labels will be missing here, but it narrows things down quite a bit!

**Comment by cdolle** [comment]
This is a problem with the Taiga theme.  The labels are there, but there are no arrows to expand them when using Taiga.

**Comment by bellebethcooper** [comment]
@cdolle Confirmed. In the bundled version of Taiga this is the same. It also affects the Berend theme.

If I switch to a theme without this problem and click the arrows, the nested folders remain visible in Taiga and the Berend themes.

**Comment by bellebethcooper** [comment]
@bengotow Apologies! I didn't see your last message. I've confirmed this is a theme issue, though, so feel free to close/move the issue if appropriate.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
