### ISSUE TITLE
Spellchecker: Investigate checking in all available languages - Resolve inconsistencies

### ISSUE THREAD

**Issue by bengotow** [nylas/N1#1392]
There are many, many complaints about spell checking in N1. It currently spell checks in the currently selected system language on Mac OS X and Windows 8+, and only in English on Linux. There's not much we can do about Linux because we have to ship dictionaries ourselves.

However, on Mac OS X and Windows the spellchecker API is very fast and available in many languages. Rather than pick one, we should try to instantiate many spellcheckers and spellcheck in all languages all the time. I believe this is what Slack is doing, and would address #1388  #1046 #1011 #670

**Comment by oldhickory30** [comment]
Appreciate the fact your investigating the issue as far as #1388 w/ MAC OS. Again it works briefly then Nylas will no longer underline the misspelled word. Appears though if I choose a misspelled word it will provide me with the correct version. Just can't have that with my emails being mostly for business. Fix this, and' I'll be back on board!

**Comment by mbilker** [comment]
Slack Native is an Electron application and uses `node-spellchecker` as I noticed the `node-spellchecker.node` file in its `app.asar.unpacked` directory.

**Comment by mbilker** [comment]
The following are details about Linux usage of Slack Native, but this should not differ from Windows or OS X because Slack Native uses `electron.app.getPath('userData')`, which evaluates to `/home/mbilker/.config/Slack`. This is where Chromium stores its content like `Cache  Cookies  Cookies-journal  'DevTools Extensions'  GPUCache  IndexedDB  'Local Storage'  Preferences`.

Slack Native stores its dictionaries in `~/.config/Slack/dictionaries` and by default contains `en_US.aff  en_US.dic`. From its binary it checks the standard Linux locations for Hunspell: `/usr/share/hunspell' '/usr/share/myspell', global.loadSettings.fallbackDictionary` and pick the first directory that exists to search for dictionary files.

It also has the ability to **force** Hunspell usage on Windows where the native spellchecker is not reliable. This is through `process.env.SPELLCHECKER_PREFER_HUNSPELL`. If the user is not on Linux and wants to force Hunspell, Slack Native will download dictionaries from http://slack-ssb-updates.s3.amazonaws.com/dictionaries. The logic for downloading dictionaries is extensive but easy to follow in the code.

**Comment by mbilker** [comment]
It contains no logic for Mac OS X as its multi-language spellchecker integration with `node-spellchecker` is very good.

**Comment by link0802** [comment]
Make multi language spellchecker on linux and N1 will be my primary email client :wine_glass: :wink:

**Comment by mbilker** [comment]
@link0802 I shall work on it from Slack's decompilation, but I must watch to not violate their license

**Comment by link0802** [comment]
@mbilker I don't know if it will help but in the past atom has similar problem too. 
But @ihatetothink solve(ish) it in this issue - https://github.com/atom/spell-check/issues/21

**Comment by mbilker** [comment]
Atom still has the issue, and `node-spellchecker` cannot do this by itself.

The only way I can think to fix this is to have one instance of `node-spellchecker` for each language you want to check if correct. If the word is correct in at least one of the spellcheckers, then the word is correct. The word is incorrect if it is deemed incorrect by all the spellcheckers.

Slack does not face this issue because communication between team members is done in the user's native language.

**Comment by link0802** [comment]
https://github.com/brrd/Abricotine solve this problem with manual switch. They add manual switch for spellcheck language and ship app with dictionaries.

**Comment by mbilker** [comment]
@link0802 Slack actually downloads the dictionaries on Windows 7 only. It relies on the distribution installed dictionaries on Linux. I am working on this type of integration.

**Comment by mbilker** [comment]
If you want Slack's spellcheck method for initializing many Spellcheckers, review #1807. The only issue is that the Spellchecker is loaded in unwanted window types including `worker`.

**Comment by HenriqueNunes** [comment]
Hi! I am really enjoying Nylas N1, but this limitation of the spellchecker is **driving me nuts!**
Having to copy/paste text from a word processor whenever I need to send an email in Portuguese (as my Mac OSX is in english) is frustrating, time consuming and can only be a short term solution.
Do you have any idea of the timeframe involved in fixing this behaviour in Nylas N1 ?
Regardless, Please keep up the excellent work!
Thanks

**Comment by geronimo750** [comment]
Hello!

Just discovered Nylas N1 and I really like it. Nevertheless, it seems that the issue with the spellchecker has not been resolved yet. I Installed N1 on both a windows 7 machine and an Ubuntu 14.04 machine and in both of them the spellchecker is not working. Any hint on what I should do.

**Comment by jakubfiala** [comment]
The very easiest and most immediate fix to this annoying issue would be to add an option to disable the spellchecker altogether. I don't need it, but I can't turn it off and it really disrupts my writing.

**Comment by mattkennedynz** [comment]
Hey all, another Arch Linux user with a preference for British English coming to the table. My current workflow is copy and pasting into a untitled Google Doc to squash the couple of spelling mistakes I tend to make. This is obviously not ideal.

Hi @mbilker, regarding #1011 would switching to American English as my default system language enable some form of spell checking?

I'm _really_ digging N1, which is why I'm putting up with my Google Docs workflow. But I'm definitely open to ways I can improve this in the short-term :-)

**Comment by mbilker** [comment]
Yes it would enable some sort of spellcheck if I recall correctly. I am
still working on improving the performance of my multispellchecker.

**Comment by RicardoEPRodrigues** [comment]
When can we expect to have different languages spellchecked in Linux?

For me it's still a major problem to have only English correctly underlined, even when I have Portuguese keyboard selected.

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/4385

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/4344

**Comment by adriaanmol** [comment]
Any news on this?

**Comment by RicardoEPRodrigues** [comment]
This should be considered a `bug`, not an `enhancement-request`.

If it works on Windows and Mac, then not working on Linux is bug in my opinion.

And still no news?

**Comment by Muurtegel** [comment]
If this was the case, I would agree. But the spellchecker doesn't work on a Mac either.

**Comment by adriaanmol** [comment]
Ah wow! Can't wait!

**Comment by RicardoEPRodrigues** [comment]
![FINALLY](https://cdn.meme.am/instances/9868712.jpg)

**Comment by bengotow** [comment]
Hey folks, we shipped the spellchecker improvements to all users this morning in v0.4.59. This release switches N1 to the same spellcheck wrapper developed for Slack, which detects the language you're writing in and spellchecks in that language. On Linux and older versions of Windows, it downloads Hunspell dictionaries on-the-fly, because shipping them all would be costly.   This should resolve ongoing spellchecker issues!

**Comment by RicardoEPRodrigues** [comment]
N1 still can't detected my switch of languages on Linux, is that normal?

I have two default keyboards layouts, PT and EN, but N1 only detects English.

**Comment by renat-magadiev** [comment]
Hi a I have the same problem on Linux. N1 can't detect Czech language (i write messages largely in czech), but if you used the same solution as Slack, then is your implementation bad. I love N1, but without spell checking in 2017 it's very problematic to use it.

I believe that you can fix it and we all can use N1 with love.

**Comment by cribari** [comment]
Same problem here. Nylus cannot detect Brazilian Portuguese in Manjaro Linux. Spell checking is not working.

**Comment by Noslle** [comment]
This is unfortunately the case for a long time now. Nylas will definitely become my favorite and number one email client on Linux once multi language spell checking is supported.
