### ISSUE TITLE
Feature Request: Keyboard shortcut to snooze a thread

### ISSUE THREAD

**Issue by fuJiin** [nylas/N1#1424]
Bonus: keyboard navigation for the snooze options.

**Comment by Haar** [comment]
:+1: on this, I currently have 'right': 'application:archive-item', and something along the lines of 'left': 'application:snooze-item' with keyboard focus on the snooze options would be perfect.

**Comment by laughedelic** [comment]
:+1:

**Comment by devonzuegel** [comment]
:+1:

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!

**Comment by devonzuegel** [comment]
Thanks for the update @bengotow! 😃 

To save people time digging through the docs, the relevant shortcut is: `"core:snooze-item"`.

Here is my entire `keymaps.json` file to see it in action:
```
{
  "core:archive-item": "right",
  "core:delete-item": "shift+right",
  "core:snooze-item": "left",
  "core:reply-all": "r"
}
```

**Comment by eibrahim** [comment]
Awesome.  The default shortcut is "z".  But that just pops the snooze pop-up and then I have to us the mouse to choose one of the canned options.  

Is there a way to map a shortcut to "snooze tomorrow" or "snooze until weekend" etc...

**Comment by kriskhaira** [comment]
In Airmail, its Snooze shortcut (Cmd-D) opens a popup with "Tomorrow" already selected. Then all you have to do is hit Enter.
<img width="295" alt="screen shot 2016-06-16 at 3 14 49 pm" src="https://cloud.githubusercontent.com/assets/80577/16108350/31911ad2-33d5-11e6-8666-1ea4ab12adb3.png">

**Comment by Haar** [comment]
👍  For the default being to focus on today with the option to navigate with the arrow keys, currently there's no way to get from the text field to the quick options above.

**Comment by manicmarvin** [comment]
But you can just type 'tomorrow'.  Which involves no mouse movement since text
field is in focus on cmd-z  
  
Sent from [Nylas N1](https://link.nylas.com/link/8uwzmkccj87k9zx4fmexa3m9c
/local-
55c574c4-84f5/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1&r=cmVwbHkrMDBhNzIzZThlZGIwNzRmMDIyZjcwMjc2YTNiZDFhNjlkYzZkYTg3ZTBhODAzYTc3OTJjZjAwMDAwMDAxMTM3YTI4NjE5MmExNjljZTA4MjQ4NWYwQHJlcGx5LmdpdGh1Yi5jb20=),
the extensible, open source mail client.  

On Jun 16 2016, at 2:12 pm, Robert White &lt;notifications@github.com&gt;
wrote:  

> ![](images/composer-emoji/apple/1f44d.png) For the default being to focus on
today with the option to navigate with the arrow keys, currently there's no
way to get from the text field to the quick options above.

>

> —  
> You are receiving this because you are subscribed to this thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/1424#issuecomment-226424036&r=cmVwbHkrMDBhNzIzZThlZGIwNzRmMDIyZjcwMjc2YTNiZDFhNjlkYzZkYTg3ZTBhODAzYTc3OTJjZjAwMDAwMDAxMTM3YTI4NjE5MmExNjljZTA4MjQ4NWYwQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AKcj6KzG0ZnZ8-sxGAMyMrol7tgFgMT1ks5qMQxhgaJpZM4HjhO2&r=cmVwbHkrMDBhNzIzZThlZGIwNzRmMDIyZjcwMjc2YTNiZDFhNjlkYzZkYTg3ZTBhODAzYTc3OTJjZjAwMDAwMDAxMTM3YTI4NjE5MmExNjljZTA4MjQ4NWYwQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AKcj6KpMNe1G9GgCUhwCk7az3NcNuPNVks5qMQxhgaJpZM4HjhO2.gif)

**Comment by Haar** [comment]
Having to type `later today`, `this evening`, or `tomorrow` is not a nice way to have keyboard interaction. Without the ability to apply the actions across multiple emails at a time (there's an existing issue requesting that feature) it adds a lot more effort per-email compared to pressing return or direction-return (which can easily become muscle memory).

As it stands at the moment it's less effort using a mouse to interact with N1 which defeats the purpose of having these key binds in the first place, hence why in my original comment I specified "with focus on the snooze options".

**Comment by manicmarvin** [comment]
Snoozing multipel messages at once woudl be a boon. You refer to an already open github issue. Can you reference it here, I'm unable to find it. 

> the ability to apply the actions across multiple emails at a time (there's an existing issue requesting that feature)

**Comment by Haar** [comment]
Ah sorry - it appears we can currently snooze multiple messages at once via the hot-key, it's only via swipe actions that aren't supported. (#1638)

At least that makes it less painful if we're able to select multiple then type e.g. `tomorrow` at least. 👍
