### ISSUE TITLE
Reverting the toolbar sizing back to pre-0.4.9

### ISSUE THREAD

**Issue by paper9oll** [nylas/N1#1427]
Hi Developer,

Is it possible to introduce a option to revert the toolbar sizing back to pre-0.49?
v0.49 introduces new slimmer toolbar but the design looks inconsistent on OS X even though there is interface scaling option.

**Comment by bengotow** [comment]
Hi @paper9oll — thanks for reporting this. The toolbar sizing, button height should match standard Mac apps like Safari - could you post a screenshot? Unfortunately our team feels that this design is consistent with Mac OS X 10.11 and we won't be maintaining multiple toolbar sizes, since it makes things harder for theme developers.
