### ISSUE TITLE
Feature Request: Forget, exclude or delete contacts

### ISSUE THREAD

**Issue by cperryk** [nylas/N1#1445]
Is there a way to make N1 forget a contact so that it does not appear in recipient autofill? Removing the contact both from my local Contacts app as well as my Outlook account does not seem to make N1 forget it. This is a huge headache because it's a coworker's personal email address, and unless I'm careful I'll send work material to it because it's the first address that appears in autofill.

**Comment by bengotow** [comment]
Hey! Thanks for filing this, I can definitely imagine this is really annoying. Right now, N1 scans through emails to build the contact autocompletion database, rather than looking at Outlook's or Mac OS X's address book. This is something we'll definitely be fixing in the future.

In the meantime, if you want you can open the Developer Tools in the app (from the menu Developer => Toggle Developer Tools) and paste this command on the console to remove a contact from the app entirely - just edit the string email address in there. It should only impact contact autocomplete.

Depending on how often you use the email address, it may be part of the in-memory cache - to be safe, restart the app after you run the command. Cheers!


```
$n.DatabaseStore.inTransaction((t)=> { t.findBy($n.Contact, {email: "ben@foundry376.com"}).then((contact)=> { t.unpersistModel(contact); console.log("Removed contact ID: "+contact.id); })})
```

**Comment by bengotow** [comment]
(Updating the title to include more keywords for issue search)

**Comment by cperryk** [comment]
:clap: Thanks! I ran that command and it worked after restarting the app.

**Comment by jackiehluo** [comment]
I think we can probably bundle into #1031!

**Comment by jeromecovington** [comment]
Tried this fix in the console but got this error:
```
Uncaught SyntaxError: Unexpected token :
```

**Comment by randy-shults** [comment]
The Developer tools console snippet fix worked perfectly for me. thanks.
