### ISSUE TITLE
Dark color scheme has dark text

### ISSUE THREAD

**Issue by mbolivar** [nylas/N1#145]
![nylas-dark-background](https://cloud.githubusercontent.com/assets/35088/10680303/69e611de-78ec-11e5-8610-59f4c127f6ea.png)

As shown above, when reading a plain text email with the dark background option set in the split view, the email content is in a black font, making it very hard to read.

The inbox itself has light colored text -- it's just the mail that's hard to read.

64-bit Ubuntu 14.04.

**Comment by mbolivar** [comment]
I checked -- HTML emails have a light colored text. The issue appears restricted to when the email contains a plain text body.

**Comment by bengotow** [comment]
Ahh interesting—you're definitely right. It looks like we're caching the CSS that is injected into each email iFrame, so you need to click away from the email and click back to see the updated CSS. Shouldn't be too hard to fix.

Also you're definitely right about HTML emails. We've tried all sorts of things to adjust the styling of them, but many of them hardcode text colors, background colors, etc., so they still display against white in dark mode.

**Comment by sss4r** [comment]
In general it's difficult to read HTML-formatted emails because the sender assumes a white background; therefore, images frequently render poorly and text can be unreadable. Is it possible to at least make it an option to default the background color of the message body to white? I mean, keep the rest dark, just change the frame that contains the message to white. Thanks.

**Comment by johncch** [comment]
Similarly, when you switch color schemes when a mail is open in the reading pane, it doesn't switch the font colors even though the rest of the UI does.

![image](https://cloud.githubusercontent.com/assets/331432/11194826/371c7484-8c63-11e5-82ca-83e627137a03.png)
