### ISSUE TITLE
Can't archive/trash (via shortcut or swipe) when viewing all accounts, if one of the accounts doesn't allow it.

### ISSUE THREAD

**Issue by robxu9** [nylas/N1#1460]
On OS X 10.11.3 with version 0.4.9-575c091 and 0.4.10-4e3595b of N1, swipe actions only partially work on the All Accounts Inbox screen. I can swipe right to left to snooze, but I can't swipe left to right to archive.

If it helps, I have like four different Gmail accounts, an Exchange account, an iCloud account, and an IMAP account.

It should be noted that if I select an individual account, swiping to archive works.

**Comment by jstejada** [comment]
Hi @robxu9 , thanks for reporting this. This is due to to the fact that probably either your IMAP or Exchange account doesn't have an "Archive" folder so you can't archive in that account. However you should definitely be able to archive any other mail while viewing all your accounts so this is definitely a bug. The same will happen for trash if you enable swipe to trash and one of your accounts doesn't have a trash folder.

We are working on a fix for this, in the meantime, if you create an `Archive` folder for the account that doesn't have one it should work. Let me know if this helps.

**Comment by robxu9** [comment]
Hi @jstejada - I've actually had Archive folders in my various accounts (and/or "All Mail") from previous mail clients that added them before I migrated to Nylas N1. I've managed to confirm that all of them have some sort of Archive folder.

If I swipe in the individual accounts, they work; so I think it's mainly the "all accounts" view that seems to be failing in general. Let me know if I can provide any more information.
