### ISSUE TITLE
Difference between read & undread email (default theme)

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#1467]
I've noticed unread email have three indications, the more obvious being the blue bullet next to unread emails and the subject is in bold.  For unread emails background colour is changed and the subject is no longer in bold with the blue bullet removed.

The change in background colour for read emails is very slight and just noticeable and it's on the edge of the subconscious vision to be very annoying.

It the shares same colour as the mouse pointer hovers over read & unread email. Also when you have the pointer hovering over a read email next to an unread email it's not useful at all as both have matching background colours.

It serves no real purpose as the blue bullet and bold subject does the job very well.  There is no need to change the background colour in the email list.

This is for the default theme, the theme all new (potential paying) users will experience when trialing N1.

**Comment by bengotow** [comment]
Hey! Thanks for the feedback — it sounds like we might need to tune the theme colors a bit for your display since the grays appear very similar. N1 follows Gmail's read / unread background colors, and our team wants to keep the gray / white distinction along with the unread dot. Feel free to use one of the other themes!
