### ISSUE TITLE
[Feature Request] Unsubscribe link parser > Button

### ISSUE THREAD

**Issue by agustifernandez** [nylas/N1#149]
Unsubscribe Button, ala Gmail.

Unsubscribe links could be parsed to detect SaaS's like Mailchimp and the like, would also be nice to add one unsubscribe mannually and be able to share your list of unsubscribes easily

**Comment by colinramsay** [comment]
I've created an extension which detects the unsubscribe link and pops up a browser window to show the resulting page. Sometimes this'll be a "success" page, sometimes it's a form requiring further action. 

With Gmail, if it "knows" that there's a special unsubscribe action page, then it'll offer to take you there, otherwise it does it automatically. This seems to indicate that Gmail might maintain a list of various things it can unsubscribe from.

Any thoughts on how this should behave and where the button should appear?

**Comment by colinramsay** [comment]
The project is available at:

https://github.com/colinramsay/nylas-unsubscribe/tree/master

It's probably better to discuss this issue there.

**Comment by grinich** [comment]
Hi @colinramsay -- this plugin sounds awesome. Want to list it here? https://github.com/nylas/n1-plugins

**Comment by grinich** [comment]
gonna close this but i'd be happy to talk more in slack about design decisions for the plugins :) http://slack-invite.nylas.com/
