### ISSUE TITLE
[Windows] Initial launch will not progress past "Explore Plugins" screen.

### ISSUE THREAD

**Issue by CameronHall** [nylas/N1#152]
![image](https://cloud.githubusercontent.com/assets/7316093/10686942/efb27618-79b4-11e5-977b-f840a608b05b.png)

**Comment by CameronHall** [comment]
If you restart Nylas it appears to resolve the issue.

**Comment by bengotow** [comment]
Hi folks—we've been investigating crash logs coming in from this screen. It looks like the plugin installer is failing (it's actually a separate tiny process). If you continue past this screen by relaunching, you should be good. If you run into any trouble, delete the folder at `~/.nylas/packages`. I expect we'll have this fixed in the next day or so. Stay tuned!

**Comment by bengotow** [comment]
This has been fixed and will be going out shortly in `0.3.18`
