### ISSUE TITLE
Any way to use TLS certificate file for IMAP/SMTP account?

### ISSUE THREAD

**Issue by mishoboss** [nylas/N1#153]
Seems there is no way to chose a TLS certificate file when setup IMAP/SMTP account. Is this feature available somehow or it is not yet implemented? It is a show-stopper for me.

**Comment by grinich** [comment]
What do you mean a TLS certificate file? What are your IMAP/SMTP settings?

**Comment by semsphy** [comment]
+1
My configuration on Thunderbird is work well. But it didn't on N1 (I got request timed out.). Here is my configuration.

![selection_113](https://cloud.githubusercontent.com/assets/423396/10720093/ed9ab724-7bc5-11e5-8a65-530f82aa5875.png)

**Comment by mishoboss** [comment]
I experience exactly the same behaviour - "Request timed out". On Apple Mail it works like a charm with exactly the same credentials. I have a personal certificate that is used for email encryption (is N1 supporting email encryption). In Apple Mail it is set in the account settings. There is a TLS Certificate dropdown field. However I think it shouldn't be used for IMAP/SMTP authorisation, but the issue is a fact. :( Any ideas?

**Comment by Delagen** [comment]
+1

**Comment by mishoboss** [comment]
My credentials are correct too. Triple checked.

**Comment by Delagen** [comment]
Added custom CA certificate as trusted in Windows. No changes.

**Comment by semsphy** [comment]
My configuration was on Ubuntu.

**Comment by hughwilliams94** [comment]
I am having a similar issue trying to add an institutional (.ac.uk) Office365 account.

**Comment by schade** [comment]
I am also suffering from this issue running N1 under Windows 10 connecting to a private mail-in-a-box server for my own domain. Verified working with same settings with Opera Mail on same OS. Could this be a self-signed ssl certificate issue?

**Comment by spang** [comment]
We're working on a better method for checking certificates which is basically a trust-on-first-use model that allows self-signed certificates for non-major providers. (Right now, we check certificates strictly and do not allow accounts to be connected that are using self-signed certificates.) Should land in the next week or two.

**Comment by mishoboss** [comment]
Thank you! This is really a "must-have". One additional question that is related to this one - are you planning to implement email sign/encrypt with certificates?

**Comment by schade** [comment]
Thanks for the info, @spang. Look forward to seeing the fix.

**Comment by mishoboss** [comment]
Is this fixed in version 0.3.25? I see other related issues are closed. But I still get "Request Timeout" when try to connect.

**Comment by benr77** [comment]
I am running 0.3.26 and I cannot get past the initial setup wizard. It simply will not accept my SMTP credentials.

Originally my SMTP was via a self-signed certificate on my own server. I read about these issues when I could not connect, so I created an SMTP account with MailJet and tried that. 
This account does not use self-signed certificates and still it does not allow me to create an account as it will not accept the SMTP credentials.

So still I cannot get past the setup wizard due to SMTP credentials not being accepted.

One thing that might help - the Mailjet credentials are long strings - username and password are both 32 characters. Is there any limit N1 imposes on user/pass string length?

**Comment by mishoboss** [comment]
Same situation as @benr77 here. I'm unable to finish the account setup wizard because of "bad" credentials. Seems this is not fixed yet?

**Comment by reanimastudios** [comment]
Whoever said there is a TLS pull down is mistaken. TLS over SMTP encrypts outgoing emails for a reason. Running one's series of domains with TLS on port 587 instead of SSL is a no-brainer.

The option for TLS or STARTTLS that is there in Thunderbird is not in Nylas latest, nor has it ever been in it. There is no way I'll use this tool, and it is a tool, over Thunderbird. It's got a long way to go for the basics to convince me it's nothing more than a javascript attempt at Mail.app; and a very inferior product to boot.

If you want people to take you serious, then you must match T-Birds options or just hang it up.

**Comment by grinich** [comment]
This is mainly an issue with the Nylas sync engine, which was developed and tested extensively for enterprise customers (Google Apps, Exchange, etc.) and not much on self-signed certs. 

The most useful thing for us would be to have a test matrix of all the different auth mechanisms available for IMAP/SMTP servers, so we can ensure comparability across the map. 

As for Thunderbird, maybe you can cut us some slack. 😛 N1 was developed by 2 people in only 6 months, and has been released now for less than 90 days. Thunderbird was first released in 2003. We've obviously got a way to go, but one reason the app is lacking features is because we focused on other things. Like building our own custom view later on Electron with React that supports rich plugins, rather than forking the old XUL cruft. 

When GitHub shipped Atom, they didn't ask folks to abandon Emacs. It certainly wasn't a replacement for anyone initially. Likewise, we don't expect power users to switch from Thunderbird right now-- nor have we ever demanded it. N1 has different goals, different constraints, and a different community. We hope people can still take us seriously, perhaps only based on the amount of code we've shipped and the attention we've received on GitHub. 

Thanks for your feedback! And if anyone can make that auth compatibility matrix, it would be super useful to us!

**Comment by spang** [comment]
We now accept self-signed certificates. If you're still having issues, it's likely to be #322—please follow up there. :)
