### ISSUE TITLE
[UI Problem] - Toolbar

### ISSUE THREAD

**Issue by paper9oll** [nylas/N1#1547]
Hi Developers,

I believe this issue is related to UI. The issue is with the toolbar not displaying properly or not sizing properly when multiple mails are selected.

How to reproduce?

- Resized your Mail Panel (center one) to the narrowest
- Ctrl+Left Click or CMD+Left Click two or more mails
- You would see that Clear Selection is not fitted properly inside the Center Panel, the * threads selected is also not displayed (except Trash where only * will be displayed) — * is number, e.g. 2 threads selected

Here is a picture of what i mean
![screen shot 2016-03-03 at 2 25 49 pm](https://cloud.githubusercontent.com/assets/7237114/13486451/33c6f276-e14c-11e5-8fb8-3aaafe375ee9.png)

**Comment by jstejada** [comment]
thanks for reporting this @paper9oll! For a moment there I thought the entire app was borked because the text was removed! this is a known issue, and we are working on figuring out the best way to handle overflowing buttons in that region -- stay tuned!

ps. you can also use screenshot mode via the menu: `Developer -> Toggle Screenshot Mode`

Thanks!

cc @sdewith

**Comment by paper9oll** [comment]
@jstejada Okay sure and Thanks you for screenshot tips

**Comment by bengotow** [comment]
Going to merge this into https://github.com/nylas/N1/issues/370 - this is on the roadmap and we'll probably get it fixed next month. Stay tuned!
