### ISSUE TITLE
Broken symlink in /usr/local/bin (MacOS)

### ISSUE THREAD

**Issue by ridem** [nylas/N1#1553]
I just figured out that the symlink that N1 creates in `/usr/local/bin` is broken
`/usr/local/bin/N1` points to `/Applications/Nylas\ N1.app/Contents/Resources/app.asar/N1.sh` where it should point to `/Applications/Nylas\ N1.app/Contents/Resources/app/N1.sh`

Nylas N1 overrides that symlink at every startup.

MaxOSX El Capitan
Nylas N1 0.4.10-4e3595b

**Comment by bengotow** [comment]
Hi @ridem — thanks for posting this, I think this is actually left over from when we forked Atom to create the N1 project. We're going to remove those symlinks and the code that creates them at launch, since creating symlinks to desktop apps on Mac OS X is a bit unusual and the symlink doesn't allow you to do much other than launch the app.

**Comment by ridem** [comment]
Thanks! I actually ran over it while running `brew doctor` on my mac, and getting the warning about it every time N1 restarts. Not a biggie.
