### ISSUE TITLE
Min window width isn't respected when set on >100% zoom mode

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1647]

**Comment by bengotow** [comment]
I've been wondering if we should just get rid of the zoom mode thing - made more sense before we supported retina linux displays and had the giant top bar...

**Comment by grinich** [comment]
it's definitely nice for taking high-res screenshots :P

might be better as a config file or runtime flag




On Mar 11 2016, at 11:39 am, Ben Gotow <notifications@github.com> wrote:

I've been wondering if we should just get rid of the zoom mode thing - made more sense before we supported retina linux displays and had the giant top bar...

**Comment by bengotow** [comment]
Hey folks! We've decided to remove the `zoom` option from N1's preferences UI and make it strictly a configuration option. It causes small visual issues we don't have the bandwidth to support (for example, the underline beneath misspelled words becomes invisible beneath a certain zoom level, causing users to think spellcheck is broken!)

In the next release, we'll be making it accept any integer value (default: 1), so that you can get it just right, and documenting it here: https://github.com/nylas/N1/blob/master/CONFIGURATION.md#other-config-options

Hope that helps!

**Comment by molstrangler** [comment]
When you do this change can you also add under the 'developer' menu an entry to 'edit config file...'

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
