### ISSUE TITLE
[Windows] Themes

### ISSUE THREAD

**Issue by di48l069** [nylas/N1#1649]
Hi, 

Great work on N1 but please fix Light and Dark default themes they look shocking on Windows.

**Comment by jackiehluo** [comment]
@di48l069 Design-wise, we're reworking the Dark theme right now. If there's anything broken in your default themes, want to post a screenshot so that we can see what's wrong?

**Comment by Zeklandia** [comment]
The title bar doesn't change to match the themes, either.

**Comment by di48l069** [comment]
@jackiehluo When hovering over message the icons on right are not clear have black outline have to strain my eyes trying to see it 

I would show screen grab of issues but don't want to display my personal mails.

I will try post some images tommorrow

**Comment by jackiehluo** [comment]
@di48l069 We have a screenshot mode you can use! `Developer -> Toggle Screenshot Mode` should help.

**Comment by di48l069** [comment]
@jackiehluo Thanks

I have circled the problem
- [ ] Compose new message (Should be white icon on hover and dark background on hover)
- [ ] Settings (Same as compose message
- [ ] Highlighted icons on selected message i have to strain my eyes to try find delete icon eg trash should out line in white on hover
- [ ] Select theme form should be same color as current theme
- [ ] Selected message icons under search bar should not have the white background its tedious and hard to see icon

See image below
![n1](https://cloud.githubusercontent.com/assets/7794777/13718116/8af37b7e-e7ef-11e5-8438-636875e12b11.JPG)

**Comment by jackiehluo** [comment]
@di48l069 Just pushed some fixes for the button issues. The theme picker is explicitly hardcoded to look the same in all themes, so that one probably won't change, but I'm not sure why it looks different in your view. It should look like:
<img width="256" alt="screen shot 2016-03-12 at 11 41 12 am" src="https://cloud.githubusercontent.com/assets/8452682/13724879/08c34efa-e848-11e5-8a98-c131e5f24bab.png">
Going to close this issue for now, since the Dark theme issues on Windows are fixed.
