### ISSUE TITLE
Removing label doesn't move to next thread

### ISSUE THREAD

**Issue by findjashua** [nylas/N1#17]
If I'm currently viewing list of emails in label 'foo', and remove the label 'foo' from the email I'm currently viewing, I expect the next email with 'foo' to show up.

**Comment by bengotow** [comment]
Hi @findjashua — this should be fixed in the "Split" layout mode in 4f34c8403fdf312ef4e5ff8efd1b6f7117bfd1bb, but in Gmail-style list mode it's still happening. You have to press "back" to return to the list of threads and click another one. I'm not sure whether we want to pop the sheet or move you to the next thread.

**Comment by grinich** [comment]
@findjashua what does Gmail do here?

**Comment by findjashua** [comment]
@bengotow i'd expect the same behavior in list view as the split view
@grinich i'd expect the view to show the next newest email w the label 'foo'

**Comment by grinich** [comment]
Closing as stale. Please re-open if you have steps to reproduce!
