### ISSUE TITLE
Outlook.com accounts added as Exchange and fails to sync

### ISSUE THREAD

**Issue by jadchaar** [nylas/N1#171]
Hello, whenever I try to add my Outlook.com account, N1 sees it as an exchange account for some reason: (![screen shot 2](https://cloud.githubusercontent.com/assets/7388203/10708428/1296a3c2-79d6-11e5-86e8-963db8fae3d4.png)).
<br>
<br>
Furthermore, my account fails to sync for some reason. Instead, I am given this "error" in the bottom left corner: 
![screen shot 1](https://cloud.githubusercontent.com/assets/7388203/10708437/50363cc4-79d6-11e5-936d-a90ef724baf6.png).
N1 did not prompt me to input my **Two-Factor Authentication** code, so I think this is the issue behind the syncing failure.

**Comment by mrpatiwi** [comment]
+1

**Comment by PlugaruT** [comment]
+1

**Comment by ilkerkorkut** [comment]
same problem with no error alert on Ubuntu 14.04.

**Comment by QuiZr** [comment]
+1

**Comment by rodmoreno** [comment]
+ 1

**Comment by jadchaar** [comment]
Still occurring on the latest build, Version 0.3.20-6bbe930.

**Comment by Honason** [comment]
+1

**Comment by hrwebasst** [comment]
+1 for local

**Comment by yannickglt** [comment]
+1

**Comment by seekr** [comment]
+1

**Comment by Chinney** [comment]
+1

**Comment by rista404** [comment]
+1

**Comment by spang** [comment]
Folks, Outlook.com is Exchange behind the scenes—which is why Outlook.com accounts appear as Exchange accounts to N1. (I realize this might be a bit confusing!) We've heard that Microsoft is migrating Outlook.com accounts to Office365 infrastructure, so it's unlikely that we're going to implement  a different authentication or syncing method here.
