### ISSUE TITLE
Option to restore email to inbox

### ISSUE THREAD

**Issue by pulka** [nylas/N1#1717]
**Feature Request?**
in gmail there's an option to restore an email to previous place.
For example, if i delete a email, if i go to trash, i have a option to restore it

**Comment by bengotow** [comment]
Hi @pulka — thanks for reporting this. This is only possible on Gmail because labels are a subset of All Mail. We probably won't be able to implement this in a way that works for all mail providers, so I'm closing it as a wontfix for now. On Gmail, you can actually do this currently by dragging the thread from your Trash / Spam to "All Mail".
