### ISSUE TITLE
Massive memory usage (1.4GB)

### ISSUE THREAD

**Issue by scratchfive** [nylas/N1#178]
N1 if left open will eventually consume about 1.4 gigs of my RAM which is quite excessive. This is collective and includes the electronJS processes that are spawned.

**Comment by shawnzvinis** [comment]
+1 on "doesn't quit" and "manual sync".

**Comment by bengotow** [comment]
Hey @scratchfive — have you updated to 0.3.19? There was a pretty bad memory leak in earlier versions which was fixed in ad5274049de1ecb7cb7f1edebb467fe48a0252ee.

If you run into that memory issue on 0.3.19, it'd be great if you could run a Heap Snapshot in the Chrome Developer Tools and post the output here. It provides some pretty amazing detail and we can see specifically what we need to fix.

To submit a heap snapshot, do the following in the app's main window, and also in the work window (which you can show via `Cmd-Option-W`):

Press Cmd-Opt-I to open the Developer Tools, then choose "Profiles" from the top menu. Click "Take Heap Snapshot" and then "Take Snapshot".  In the sidebar it'll say "Snapshot 1". Choose "Save" and send it our way!

**Comment by bengotow** [comment]
(The other parts of this ticket are duplicates of #173 and #167 so I'm going to edit it to just address the memory issue)

**Comment by scratchfive** [comment]
Currently running build 0.3.19-de7d1bb. I've attached a link to an archive containing the heap snapshots requested as they are rather large. https://www.dropbox.com/s/bgryu8uc2aexqbl/heapfiles.7z?dl=0

**Comment by PlugaruT** [comment]
I am running the latest version and here is what I have under Windows:
![1](https://cloud.githubusercontent.com/assets/6437932/10712792/df8ac44a-7aac-11e5-867a-669302e9b103.PNG)

**Comment by jadchaar** [comment]
Can corroborate that this issue is not only present on Windows, but also on OS X 10.11 (probably earlier versions also). The "Electron Helper" process is sucking up huge amounts of memory when the app is kept open for a while. The N1 process only takes up about 50-100mb though, so that is not the issue.


This is the "Electron Helper" process usage after a complete restart of Nylas N1: ![screen shot](https://cloud.githubusercontent.com/assets/7388203/10717199/b9374c08-7b26-11e5-984a-1bf43a4b4b52.png). It is way too much memory usage for a dormant task.

When I see the memory leaks occur again, I will post a screenshot.

**Comment by bengotow** [comment]
Hey folks,

Thanks for the heap trace @scratchfive — I should be able to diagnose the problem based on that. Unfortunately, 1.4+ GB is an issue, but 300-400MB of RAM is the expected memory usage. I agree that 400MB or RAM is /also/ a crazy huge amount, but N1 is built on Chromium and is equivalent to running Chrome with 5 tabs open. Chrome unfortunately uses about 60-100MB of RAM per tab:

![image](https://cloud.githubusercontent.com/assets/1037212/10717213/fe58f3c2-7b0d-11e5-85d1-9ab18dff3a71.png)

Chromium has been working to reduce this, and Chromium 45 uses less memory. We haven't moved to it yet, but we plan on doing so as soon as it's stable.

**Comment by jadchaar** [comment]
Ah, the Chromium core is definitely the issue. 400mb is the usage at startup, but it was reaching a monumental amount after being open for a while (it was open for about 2 days, with a few computer sleeps in between). I'll post a screenshot when it occurs again.

Funny thing is that I just noticed that a NYT infographic/animation article on Hurricane Patricia was open in the background (minimized) and when I closed it, my memory usage went from about 5.2Gb to 2.8Gb! Insane memory leak on Chrome's end; good I just reported it to them.

**Comment by bengotow** [comment]
Yeah—we have plans to cut memory usage within the app by being smarter about how we hold your contacts in memory, fixing leaks found in heap files, etc...  Fixing leaks is totally doable and the app should never use 1.4GB of RAM. At the end of the day though, I think we'll get memory usage down to about ~350MB all the time, but it's unlikely it'll go any lower because it's Chromium under the hood.

**Comment by jadchaar** [comment]
Totally understandable! Hopefully Chromium will continue to improve its memory usage also.

**Comment by caloon** [comment]
I also came along this issue. Just to let you know: On my Macbook 12" the Electron Helpers are taking up a total of 643MB and additionally the Nylas N1 process about 76MB. Sums up to a total of 719MB. Still a lot of memory usage, especially when you consider the lower hardware specs of my model. 

By the way, I have four email accounts connected - how big is the effect on memory usage when adding additional accounts, do you know that? I might delete some otherwise.

**Comment by patrickheeney** [comment]
As another data point, I have 2 accounts setup. Electron helper uses just over 1GB. Nylas is using 61MB.

**Comment by mbilker** [comment]
Is still an issue?

**Comment by patrickheeney** [comment]
@mbilker I am seeing about 450MB with Electron Helper and Nylas with 2 accounts setup. Definitely seems to be an improvement for me and close to the goal of "~350MB all of the time".

**Comment by mbilker** [comment]
@patrickheeney well that is better. Under my Linux setup I see around that, but I am not always sure because of shared memory, GPU memory maps, `mmap`-ed files, and copy-on-write memory.

**Comment by caloon** [comment]
It's also down for me. Around 500MB.

**Comment by cfblaeb** [comment]
On Ubuntu 15.10 there are 7 threads open with a combined memory usage of almost 1 GB.
N1 version 0.4.5-b0ec355

**Comment by mbilker** [comment]
That is normal since N1 uses Chromium's process model.

**Comment by cfblaeb** [comment]
While it may be normal, is it really desirable that an email client requires a gb of memory?

**Comment by mbilker** [comment]
It is being worked on, but the focus currently on features and bug fixing.

**Comment by bertrand47** [comment]
Hi,
For me under linux: 365M with 3 acounts. Version 0.4.14 it's better :)

![captureecrandeepin20160312140539](https://cloud.githubusercontent.com/assets/606949/13723145/0ac9f032-e85c-11e5-98fb-ffda0989194f.png)

**Comment by mbilker** [comment]
That's good @bertrand47. I notice the same under `htop` where I get similar readouts by subtracting shared memory from reserved memory. The virtual memory size is very large at around 5 GB, but virtual memory is always out of proportions with the actual memory used.

**Comment by fabriziodicandia** [comment]
It's also like that on windows now (it should use even less RAM than your screenshot).
To the devs: is there a way you could improve the ram usage even more? Why is it even based on a browser (chromium)?

**Comment by ginfuru** [comment]
I know this was closed but the latest build is still using, 1GB+ of RAM on my MBPr anything else I need to provide?
