### ISSUE TITLE
Allow for customization of integrated themes.

### ISSUE THREAD

**Issue by rittbys** [nylas/N1#1789]
As you may know, Darkside, one of the newly-added integrated themes that I had been using for a long time independently, features several customization options in its standard download. Is it possible to customize the theme (i.e. switch color schemes) in the integrated version?

**Comment by jackiehluo** [comment]
Hey, @rittbys! Before, the customization options were just changing the colors in the LESS file, right? You can still do that, of course. Just copy the directory from `internal_packages` and change the colors in `darkside.less`. Then, install it as a third-party theme.

**Comment by rittbys** [comment]
What about editing from inside the client? It would be nice to still have the
auto-update function. Requesting this as a possible feature.  
![](https://link.nylas.com/open/8yes9y8yh2im0hno0nz2dlbjq/130f41ad1cef48489b90
089f0d3a80b0)

**Comment by jackiehluo** [comment]
Unfortunately, I don't think building our theme manager to allow themes to be edited inside the client will really make sense, just because it's really difficult to say how that would work from theme to theme and not a standard interaction people have.

What link did you just send? Looks like there's a problem with link tracking for GitHub replies.

**Comment by rittbys** [comment]
Sorry, I think that was a result of me replying to the notification from N1.
