### ISSUE TITLE
MessageStore Subscription - Timing Issue

### ISSUE THREAD

**Issue by colinramsay** [nylas/N1#180]
I've created a plugin which has its own store, and inspired by the Message-View-on-Github plugin, I've used the following code:

```
_onMessageStoreChanged: ->
    return unless MessageStore.threadId()
    itemIds = pluck(MessageStore.items(), "id")
    return if itemIds.length is 0 or _.isEqual(itemIds, @_lastItemIds)
    @_lastItemIds = itemIds

   # I never get here
```

However, this always returns early because `MessageStore.items()` is always empty. However, if I debug into the github-store which fires direct after, `MessageStore.items()` is populated.

I wonder if this is a timing issue; it's not populated by the time my store's listener is firing, but by the time the github store's listener fires, it's had time to populate.

I can probably reduce this to a simple testcase if needed.

**Comment by bengotow** [comment]
Hi @colinramsay — hmm, this is interesting... I think the MessageStore's event emitter should fire all the listeners synchronously (without any `process.nextTick` or `setTimeout` calls which would allow other code in the app to run between one listener and the next.) I'm not actually 100% sure though.

One interesting way to test this—maybe you could wrap the code in your package's `activate` method in a `setTimeout`, ensuring that your package's listener is added after all the others?

It's also possible that an exception is being thrown in your snippet above and it's not being dumped into the console for some reason (which would also be something we should fix!) I think you might have meant `_.pluck` instead of `pluck`?

**Comment by colinramsay** [comment]
I defined my own pluck so it's not that but the rest sounds interesting, I'll check tomorrow.

**Comment by colinramsay** [comment]
Ok, the simple check of wrapping my `activate` code in a half-second `setTimeout` gave me the same results. Perhaps more interestingly, that didn't affect the fact that the listener for my store still fires before the listener for the github store...

**Comment by colinramsay** [comment]
I was. My `pluck` implementation was broken :)
