### ISSUE TITLE
Inherit Gmail's label colours

### ISSUE THREAD

**Issue by snarfen** [nylas/N1#1804]
##### Are there any related issues?
Haven't found a similar request. If so, I do apologize in advance.

##### What operating system are you using?
OS X El Capitan (10.11.4 Beta)

##### What version of N1 are you using?
Version 0.4.16-8cb7748 (0.4.16-8cb7748)

**Feature Request?**
Inherit Gmail's label colours and hierarchy. Seems to be random colours as of today thus rendering this application unusable as work mail client.

**Comment by jakedeg** [comment]
Yeah. this is the same as closed https://github.com/nylas/N1/issues/510
But according to the comments on that one, it's not possible due to limitations in google's API. 
And I tend to believe its impossible as I have never found a non-Google mail client able to read existing label colors. But short of that, let's keep hoping for the next best thing: user-changeable label colors https://github.com/nylas/N1/issues/808 so we can at least manually make them match our gmail colors.

**Comment by snarfen** [comment]
@jakedeg thanks for the quick reply. Looking thru the Google API, it seems you're right. Google doesn't seem to provide label colour information. 

With that said, perhaps I should re-phrase my request and ask of a label colour picker to be added that can be synced locally or iCloud and/or N1 servers / MW?

**Comment by jakedeg** [comment]
Right. Yeah. That's definitely what I'm hoping for. I think that is what https://github.com/nylas/N1/issues/808 is all about.

**Comment by snarfen** [comment]
Ah, there we go. Thanks again!

**Comment by snarfen** [comment]
Limitations in Google API ([#510](https://github.com/nylas/N1/issues/510)).
Closed this due to duplicate / solution ([#808](https://github.com/nylas/N1/issues/808)).
