### ISSUE TITLE
Github Sidebar Plugin missing repositories

### ISSUE THREAD

**Issue by mxstbr** [nylas/N1#1991]
##### What operating system are you using?

OSX

##### What version of N1 are you using?

Version 0.4.25-a22631a

--

**Bug?**

##### Description

The Github Sidebar Plugin is showing my repositories, but a bunch of them are missing. If you take a look at my Github Profile you'll see my most popular repositories (as of today):

![screen shot 2016-04-18 at 10 44 59](https://cloud.githubusercontent.com/assets/7525670/14598499/b19fd2c4-0552-11e6-8ecc-7e8f22a9cf2c.png)

But when N1 loads my profile from Github, this is the list it shows:

<img width="278" alt="screen shot 2016-04-18 at 10 44 14" src="https://cloud.githubusercontent.com/assets/7525670/14598448/8a759468-0552-11e6-97d9-f7d5f9622786.png">

As you can see that's a very incomplete list, which is annoying because I love that feature.

##### Do you have any third-party plugins installed?

Cypher

**Comment by bengotow** [comment]
Hey! Thanks for filing this @mxstbr. To populate that sidebar, N1 is querying the GitHub API for a user based on the email, and then loading /repos for that user. I did some testing, and it looks like the problem is probably that it's only loading page one of the results:

```
curl https://api.github.com/users/mxstbr/repos | jq .[].name

"ama"
"awesome-css"
"awesome-react"
"awesome-redux"
"belle"
"blockinhole"
"Blogolio"
"books-to-read"
"brand"
"component-playground"
"convertr"
"cypher"
"debug.css"
"documentation"
"draft-js"
"emoji"
"enzyme"
"eternalpad"
"fasttrack"
"foundation.nodejs.org"
"generator-keystone"
"github-markdown-tricks"
"hackercouch"
"hoodie-client-account"
"jekyll"
"jobs"
"keystone"
"login-flow"
"memory"
"mxstbr.github.io"
```

If you're interested, we'd love a pull request to fix this. We could either load all the pages, or  load a single page but sort by # of stars, if the API allows that! The relevant code in N1 is here: https://github.com/nylas/N1/blob/master/internal_packages/github-contact-card/lib/github-user-store.es6

**Comment by mxstbr** [comment]
Good catch, that indeed seems to be the problem!

Looking at the code, what you do is use the `search/users` endpoint to find users by email and taking the repos from there. You then load the repositories of the username, but we can't sort those by most-starred: "sort string Can be one of `created`, `updated`, `pushed`, `full_name`. Default: `full_name`" *([src](https://developer.github.com/v3/repos/#list-user-repositories))*

What we could instead do is use the search API, which **allows us to search for repositories by a specific user and sort by most starred**. This is a tiny bit hacky, but works perfectly fine. E.g. this is the URL for my most starred repos: `https://api.github.com/search/repositories?q=user:mxstbr&sort=stars&order=desc`
