### ISSUE TITLE
Feature Request: Filtering to show just Unread messages

### ISSUE THREAD

**Issue by BuKinoshita** [nylas/N1#200]

**Comment by slash686** [comment]
+1

**Comment by mamantoha** [comment]
:+1:

**Comment by gilbitron** [comment]
:+1:

**Comment by laughedelic** [comment]
+1

**Comment by jorosmtz** [comment]
+1
This wll be good. Maybe between «Inbox» and «Starred»,for quickly change of view.

**Comment by guyeiny** [comment]
+1

**Comment by royts** [comment]
+ 1

**Comment by mfiume** [comment]
+1

**Comment by harismahmood89** [comment]
+1

**Comment by tabascoterrier** [comment]
+1 - having to scroll through my inbox looking for unread messages is a real pain

**Comment by jsvini** [comment]
+1

**Comment by dubbe** [comment]
+1

**Comment by askdesigners** [comment]
+1

**Comment by jcuenod** [comment]
+1
In terms of implementation, I would be happy with an advanced search option like "is:unread" (it would be easy to turn that into a shortcut of some kind).
It would be handy to be able to filter columns more generally though as well.

**Comment by aly006** [comment]
+1

**Comment by Labutin** [comment]
+1
Show only labels with unread messages is a super useful feature!!!

**Comment by matteobelfiore** [comment]
+1

**Comment by jamesaspence** [comment]
+1

**Comment by raknerak** [comment]
+1

**Comment by kallecarlkde** [comment]
+1

**Comment by pamirwang** [comment]
Would love it if this was added as a feature!!

**Comment by arbitist** [comment]
+1

**Comment by michalkopanski** [comment]
+1

**Comment by jbpin** [comment]
+1 it seems obvious...

**Comment by koenpunt** [comment]
:+1:

**Comment by richpollen** [comment]
+1

**Comment by mjaverto** [comment]
+1 this would be great for the unified inbox too to see all of our unread unified inbox messages.

**Comment by tur-nr** [comment]
+1

**Comment by aamirtharaj-rpx** [comment]
:+1:

**Comment by eimarfandino** [comment]
+1

**Comment by LeonLiber** [comment]
+1

**Comment by georgewritescode** [comment]
+1

**Comment by unodelostrece** [comment]
+1

**Comment by FabioFleitas** [comment]
+1

**Comment by Westie1012** [comment]
+1

**Comment by thiruthink** [comment]
+1

**Comment by saqebakhter** [comment]
+1

**Comment by Wikunia** [comment]
Come on guys! It can't be that hard...

**Comment by koenpunt** [comment]
@Wikunia seriously? Why don't you build it yourself? :)

**Comment by Wikunia** [comment]
Sry @koenpunt It's sometimes hard to imagine that such a simple feature is requested for a long time and nobody really answers.

**Comment by ginfuru** [comment]
:+1:

**Comment by lshreyas** [comment]
+1

**Comment by lucasnota** [comment]
+1

**Comment by fmnoise** [comment]
+1

**Comment by Eugenevik** [comment]
+1

**Comment by benjaminb10** [comment]
+1
Nobody answers !

**Comment by jdiegomdq** [comment]
+1

**Comment by caiotarifa** [comment]
:+1:

**Comment by adriangrantdotorg** [comment]
+1

**Comment by zombxx** [comment]
Definitely need. I have 6 unread emails and they must be buried because I can't find them. :+1:

**Comment by caiotarifa** [comment]
@zombxx, I have 2 like that.

**Comment by patrickjscott** [comment]
One of my accounts also shows as having two emails unread, and I can't find them.  For the same account if I search is:unread on gmail.com, there are no unread emails.

**Comment by koenpunt** [comment]
Until this is available as a feature, you can make the same search in N1 as you would do on gmail.com:

> is:unread

**Comment by jstejada** [comment]
hey @patrickjscott , you are probably experiencing issue #759. We are working on a fix.

**Comment by joshhopkins** [comment]
Filter logic would be amazing. Would love to great, 'Unread' and 'Waiting on Reply' (replied+not-archived) filters and just keep emails that are Unread/Read/New in Inbox.

**Comment by elledienne** [comment]
👍

**Comment by TyagoNeres** [comment]
+1

**Comment by iamjaredwalters** [comment]
+1

**Comment by koenpunt** [comment]
Guys, stop +1'ing, you can leave a "reaction" to the issue. More on that here: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by isaplan** [comment]
:+1:

**Comment by hanhha** [comment]
Yes, please support this. I'm sure that I marked all read in web app but N1 still shows 2 unread messages and I can not find out them.

**Comment by estebanprimost** [comment]
:+1:

**Comment by benjamindahl** [comment]
+1

**Comment by alphashuro** [comment]
lol since 26 Oct this feature is till being requested and +1d. I think we can consider this a much needed feature.

**Comment by eimarfandino** [comment]
i already removed the app. without this feature is a no go.

**Comment by tehranchi** [comment]
+1

**Comment by ksikka** [comment]
+1

**Comment by denseflux** [comment]
+1

**Comment by AdnanHodzic** [comment]
+1

If it could be implemented the way it's done on i.e: Gmail "label: unread". To show all unread email that would be great!

**Comment by koenpunt** [comment]
@AdnanHodzic see here: https://github.com/nylas/N1/issues/200#issuecomment-195956688

**Comment by bengotow** [comment]
Hey folks! Sorry for the delay, I'm building this into the next release and want to make sure we're on the right track. There are a few different ways that other apps implement an "unread" view, so I wanted to poll the crowd.

We're planning to add an "Unread" item to the left sidebar, beneath Inbox. In the future, we may add an unread filter to all views, but it's tricky because a simple filter would cause emails to disappear from view as you read them, which most likely isn't desirable.

What should "Unread" show?
- 👍  All of your unread mail, across all folders and labels (except spam and trash)
- 👎  Just unread mail in the inbox

When I mark a message as read:
- 😕  It should disappear from view immediately
- 😄  It should remain there until I leave the "unread" view, and N1 should give me a way to "refresh" the view.

When I view a message in the "unread" view:
- ❤️   It should mark it as read following my normal settings.
- 🎉  It should not mark it as read automatically.

Please use the new "Reactions" feature to vote on this comment (don't want to spam everyone subscribed to this thread!) Also keep in mind that we try to incorporate everyone's feedback into N1, but the final behavior may not be just right for everyone. Plugins and pull requests are always welcome!

**Comment by joshhopkins** [comment]
Ideally flags for all these options in preferences :)  
  
Josh Hopkins  

On Apr 19 2016, at 1:40 am, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey folks! Sorry for the delay, I'm building this into the next release and
want to make sure we're on the right track. There are a few different ways
that other apps implement an "unread" view, so I wanted to poll the crowd.

>

> We're planning to add an "Unread" item to the left sidebar, beneath Inbox.
In the future, we may add an unread filter to all views, but it's tricky
because a simple filter would cause emails to disappear from view as you read
them, which most likely isn't desirable.

>

> What should "Unread" show?

>

>   * ![](images/composer-emoji/apple/1f44d.png) All of your unread mail,
across all folders and labels (except spam and trash)

>   * 👎 Just unread mail in the inbox

>

>

> When I mark a message as read:

>

>   * 😕 It should disappear from view immediately

>   * 😄 It should remain there until I leave the "unread" view, and N1 should
give me a way to "refresh" the view.

>

>

> When I view a message in the "unread" view:

>

>   * ❤️️ It should mark it as read following my normal settings.

>   * 🎉 It should not mark it as read automatically.

>

>

> Please use the new "Reactions" feature to vote on this comment (don't want
to spam everyone subscribed to this thread!) Also keep in mind that we try to
incorporate everyone's feedback into N1, but the final behavior may not be
just right for everyone. Plugins and pull requests are always welcome!

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/200#issuecomment-211493559)![](https://github.com/notifications/beaco
n/AK7BAkgnq9mhsOlprVmpyG4QK9lgnOnVks5p48ImgaJpZM4GV0i_.gif)

**Comment by koenpunt** [comment]
@joshhopkins I agree on that, otherwise people's preferences will still be left out

**Comment by adriangrantdotorg** [comment]
I agree with @joshhopkins please have these be preferences a user can adjust :)

**Comment by alphashuro** [comment]
Agreed preferences work best.

**Comment by michalkopanski** [comment]
I'm surprised most are voting option 2 for "What should "Unread" show?". While "put it in the preferences" is a common response for everything, there still has to be a sensible default, and "put it in the preferences" is ignoring the issue altogether.

For what it's worth, Gmail and a few others that support this view show all of your unread mail, across all folders and labels. If you'd like to see Unread emails only in your inbox, you should be able to click on Inbox, and filter by Unread, the same way you would filter using the search: `is:unread label:inbox`.

PS: Gmail doesn't let the user decide what `is:unread` does, but what does Google know, right?

**Comment by cjmosure** [comment]
+1

**Comment by bengotow** [comment]
Hey folks! Thanks for all the feedback and ideas. We really appreciate it. We've shipped an "Unread messages" view in `0.4.32` with the most popular behaviors from the survey above. We'll definitely consider adding options for other behaviors in the future, especially for "What should unread show" (now Issue https://github.com/nylas/N1/issues/2110), since opinions were most divided about that. I also love the idea of implementing all of this via search and just letting users create "smart folders" in the sidebar to save queries.

Options are always a bit of a tradeoff because they increase the surface area of code that needs to be tested, and if you're not careful, you end up with something like this: DragThing's preferences panel - the result of an incredibly dedicated team doing everything users ask for almost a decade. (Impressive, but also a bit of a disaster!)

Cheers—feel free to open new tickets if you run into anything in the update,

![drag-thing](https://cloud.githubusercontent.com/assets/1037212/14989123/2a74e810-110b-11e6-8b5d-6f343bca712f.png)
