### ISSUE TITLE
All-in-one N1 distribution

### ISSUE THREAD

**Issue by alex** [nylas/N1#2066]
I'd really like to use N1, it looks amazing. Unfortunately the place I want to use it is at work, and I can't put my emails on Nylas's servers. Luckily the Nylas server is open source!

To lower the barrier to setting up a "sandboxed" install, it'd be awesome if there were an N1 installer which included a bundled local server and set N1 up to point at that.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. Maybe this docker container would help? https://github.com/nhurel/nylas-sync-engine

We don't plan to make an official installer for both packages because we don't want to encourage less technical folks to run the entire stack themselves. Getting it set up isn't so bad, but updating it as new features are released, closing port 5555 to avoid exposing your mail to others on the local network, etc. are exercises left to the reader.  Running the whole platform locally also takes a ton of RAM, CPU, etc., so we're not sure it's appropriate for our broader audience. Hope that helps a bit—thanks for your interest in N1!
