### ISSUE TITLE
Feature request: Email body formatting

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2082]
I would like to see formatting options for email:

- Bullet points
- Numbered lists
- Different (web) fonts (esp fixed width), Maybe allow the user to add any Google webfont!
- Font size options
- Left, right, centre & right justified

**Comment by enoversum** [comment]
@molstrangler Some of these things were already there, using Markup or when selecting text (which is still present). At the moment, in the current version automatic lists with 1.,2. or * do not work anymore. Font-size options are debatable, since many clients do not follow them & make text possibly hard to read on some devices (like smartphones, tablets).

**Comment by runofthemill** [comment]
Bullet points and numbered lists work for me, but font-size & alignment options would be good, though I understand your point @molstrangler re: client support. Still, almost all desktop mail clients allow font-size + alignment adjustments. 

One thing to add: need "quote" formatting. Super common use case is to quote one or more parts of a previous email in the thread, and being able to visually distinguish makes the resulting message much more readable:

> Here's something I said in a prior message

And here's my response
> Here's something else I said

Okay, I get it, can I stop talking to myself now?

> Never.

**Comment by enoversum** [comment]
@runofthemill I think formatting is really, really a matter of discussion. I am happy not receiving much mail where I get huge (or tiny) text, written in light yellow on white background (because the sender put a black background, which most of the times gets stripped off e-mails on the receiving side) and possibly each paragraph aligned individually, with bold, underlining and italic combined and wasted :wink: . 
What is really needed is a styling for quotes and inline replies, i.e. I expand the message body of the sender's e-mail and write in there. Many e-mail clients allow for inline replies like you just demoed above, and that's something I really miss, too!

**Comment by molstrangler** [comment]
I think its a very bad idea to start wholesale manipulation of received email formatting to suit the client.  I think you need to display the email as it was intended by the sender as best as you can.

Though you, me and many others have good eyesight who's to say the sender is using specific formats because the know the person reading the email is colour blind or has other sight problems.  Just because it isn't pleasing the our eyes does not mean its the same for everyone.

```

I would like to see a code box option in N1 just as GitHub and many others provide.
Of course getting it correctly display in other email clients correctly is essential

```

**Comment by runofthemill** [comment]
@enoversum I'd be happy too not to receive such poorly formatted emails :P but to @molstrangler's point, it's a bad idea to do wholesale manipulation of received emails. I think if you really want to avoid formatting, maybe look into a way to have Nylas render the plaintext instead of HTML formatting? Either a feature request or plugin? If you're getting lots of emails w/ light yellow text and black backgrounds, might be time to have a good chat with the sender! 😛

There's sort of already a style for quotes/inline replies - N1 correctly renders `<blockquote>`, there's just no way to apply that to text during email composition.

Re: codebox - I think that'd be a great option, especially for an open-source project who's demographic largely consists of developers/designers/interweb-people. A [Markdown Here](https://github.com/adam-p/markdown-here) plugin might be pretty awesome. Not sure how consistently/accurately the styles are rendered in various email clients, but could be a good solution.

**Comment by molstrangler** [comment]
@runofthemill As you have just stated 'demographic largely consists of developers/designers & Interweb-people'.  So you need to think seriously how do these kinds of people like/need to share with each other.

So a conversation is needed on what kinds of information these people need to communicate and how they would want to present them to others:

1. HTML, design features & code
2. Code, PHP, Phython, C++ etc... (fixed fonts!!!!)
3. Images
4. Web Fonts (huzzzarrr!!!!)
5. more......

Afterwards come the task of how.

Remember not everyone is working on an OpenSource project so may not be able to refer to a public URL linking to some code snip or example online.  Also they (a contractor) maybe communicating with a company who is using Outlook or another email client (moan!!).

**Comment by jackiehluo** [comment]
Merging into #1087!
