### ISSUE TITLE
Small bug: Gmail shortcut (gi) not working on an open e-mail in inbox

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#2125]
When an e-mail is open, the Gmail shortcut for going to the inbox (gi) isn’t working anymore when opening an e-mail from the inbox :laughing: . Switching to starred mails etc. still works as expected. I love the feature and often switched from an e-mail I replied to back to the inbox with this shortcut. I sincerely hope this had not been featured away.

**Comment by bengotow** [comment]
Hey! Thanks for posting this - looks like it was a side effect causing it to work previously. Since you're technically already looking at the Inbox perspective, the shortcut doesn't do anything. We can make it always return you to the thread list, though which will make this behavior intentional. Stay tuned.

**Comment by bengotow** [comment]
Will be fixed in 4c00cccbee14b00690f04d596d188f88058f9c0c. There will be a patch today so this will be in a release soon!

**Comment by enoversum** [comment]
@bengotow Hi there, I believe this was real wonderful, and I miss it dearly - so thanks for taking care of it :+1: !

**Comment by bengotow** [comment]
Hey! The `0.4.33` release is out this evening and this should be fixed. Enjoy—
