### ISSUE TITLE
Cannot delete mail using 'delete' key

### ISSUE THREAD

**Issue by nabot93** [nylas/N1#2126]
Since the last release (4.32 on ubuntu), I cannot remove a mail using the 'delete' key. However, it is still working using 'backspace' and 'y'.

**Comment by rouzbeh84** [comment]
I'm having the same issue which I didn't notice until recently.

I've tried adding 
`
{  
  "core:delete-item": ["delete", "del"],
}
`

to keymap.json and then 

`
'body':
  'delete': 'core:delete-item'  
`

to keymap.cson with many other variations but have not had any luck so far.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—it looks like you're right. The mapping needed to be `del` and not `delete`. Sorry for the hassle - it looks like this slipped through code review because our team tests on Mac OS X and other platforms within VMs, which mapped delete to backspace. Will be shipped in a patch, most likely today! a2faa9b83bce20946bb28888d1772511e43b62d1

**Comment by rouzbeh84** [comment]
Sorry @bengotow I should have mentioned I'm on a Mac running 10.11.4. Could be because I'm using a Logitech K750 keyboard though but I will let you know after I update! 👍

**Comment by bengotow** [comment]
Hey! The `0.4.33` release is out this evening and this should be fixed. Enjoy—
