### ISSUE TITLE
Hide internal plugin buttons when plugin is disabled

### ISSUE THREAD

**Issue by lazyatom** [nylas/N1#2146]
When running against a self-hosted version of the sync engine, a number of features aren't available (link/open tracking, send later, etc). It would be nice to be able to hide the buttons for these features in that case.

**Comment by KevinMartin** [comment]
When you pull directly from the github repo, those buttons should not be there. They are only added by the bundle in the releases section

**Comment by bengotow** [comment]
Hey folks - I think we could definitely add a check for `env != production / staging` in the main file of each of those packages and hide them. I'm a little worried that folks would file GitHub issues saying "I can't see the button for Send Later" though, and it'd be tricky to track down that the issue was they were hosting the sync engine themselves. In the long run, showing them but making them prompt when you click them may be the best way to communicate the limitations...

**Comment by lazyatom** [comment]
I'd be happy for the hiding to be opt-in...

**Comment by KevinMartin** [comment]
Maybe a checkbox on the bundled releases to toggle the visibility of these Pro plugins (visible by default).

**Comment by jackiehluo** [comment]
Now done in the latest release!
