### ISSUE TITLE
Integrate with Cinnamon System Tray and Notify-Send

### ISSUE THREAD

**Issue by 0v3rth3d4wn** [nylas/N1#217]
I'm using Linux Mint and it would be nice if we have a minimize and close to tray feature and also integrate with the notification system so have a popup when we receive a new mail. I think they use ubuntu's Notify-Send package.

**Comment by PlugaruT** [comment]
+1

**Comment by iRay** [comment]
Yep, +1 for integration with system tray in linux (not only cinnamon)

**Comment by Israphel** [comment]
System tray is a must have

**Comment by slash686** [comment]
+1 for system tray integration for various linux distributions.

**Comment by dszmaj** [comment]
+1

**Comment by jtflynnz** [comment]
+1

**Comment by bengotow** [comment]
Hey folks—this is definitely on the roadmap. We're planning to use Electron's Tray API (https://github.com/atom/electron/blob/master/docs/api/tray.md) to add a system tray for Mac/Win/Linux in an upcoming release. I'm not 100% sure whether the API supports cinnamon / mint mate, but I believe it should.

I've added a card for this on our open source roadmap - feel free to upvote it there if you have a Trello account: https://trello.com/c/fasAWG8X/44-windows-linux-tray-mac-os-x-status-bar-item

**Comment by waldito** [comment]
Just a question here for win7/8/10 users out there. 

![cue](https://cloud.githubusercontent.com/assets/1649188/11892627/43862eca-a56a-11e5-90df-0e922ed9fe0c.jpg)

Is that blue dot over the tray icon the only visual cue is supposed to show everytime we get new email? I was expecting a 'balloon-show' or a toast slidein message, a là outlook. Am I missing something here?

**Comment by mbilker** [comment]
@waldito When you say toast, you mean like a box with a short previous of the message and who the message was from?

**Comment by waldito** [comment]
Yes. I dont happen to see anything on incoming mail but the small blue dot.
Notifications are on for n1 on win7 taskbar settings... So...

**Comment by mbilker** [comment]
@waldito Aha. According to the Electron [documentation](https://github.com/atom/electron/blob/d08b7fdb5d31fd3942f8a81200635b7100b722d1/docs/tutorial/desktop-environment-integration.md) on Windows 7 and below only balloon notifications work, not the Native Notifications that N1 uses.

The N1 Notification handling is implemented [here](https://github.com/nylas/N1/blob/281e458d3949ce239359a263aee4856163ebc0b8/internal_packages/unread-notifications/lib/main.coffee#L47-L63).

**Comment by mbilker** [comment]
Also, notifications are handled under `libnotify` and `libappindicator1` for Linux notifications and tray icons. Zenity is an implementation of `libnotify` which is why it works on my computer.

**Comment by mbilker** [comment]
My previous statement is **incorrect**! I am so sorry. I researched [Desktop notifications](https://wiki.archlinux.org/index.php/Desktop_notifications) a little more on the Arch wiki. I realized I am running the MATE Notification Daemon because it is the only notification daemon I installed on my laptop.

Zenity is the frontend and displays the notifications from the notification daemon.

**Comment by bengotow** [comment]
Hey folks—I /think/ everyone's feedback has been addressed in recent builds, so I'm going to go ahead and close this ticket. Feel free to open a new one if there are any issues. Here's a quick breakdown:

- N1 supports desktop notifications / toasts on Windows 10 via the new built-in notification center. On older versions of Windows, there isn't a system standard way of presenting notifications and we haven't implemented anything custom (unfortunately our core team doesn't use Windows <10. PRs are welcome though!)

- N1 supports desktop notifications on Linux when you have Zenity installed (and the preferences screen in the app displays a note about installing Zenity now!)

- We register a system tray item on all platforms. N1 is based on Electron, and they note that on Linux:
  - the app indicator will be used if it is supported, otherwise GtkStatusIcon will be used instead.
  - for distributions that only have app indicator support, you have to install libappindicator1 to make the tray icon work.

Hope that helps. Enjoy N1!

**Comment by mbilker** [comment]
Actually, I diagnosed this further. I have the MATE Notification Center installed and, apparently, it starts at my login and is probably dependency of something. Zenity is the component that displays the message. I am going to test this under Fedora Gnome, which I do not have Zenity installed.

**Comment by waldito** [comment]
Well. I'd like to think you guys are interested in making N1 useful for win7 users. 
All in all, they seem to be the biggest group out there.

I am nowhere close to a coder, but I can understand Electron does provide a tray event named 'balloon-show', what leads me to think electron does provide at least a balloon feature, that should suffice to round up the experience.

N1 not having a prominent email notification for win7 seems to me an important feature left out. I understand migration to win10 is likely happening within 3-5 years, but the current market share is still big to be ignored, right? (40% to 50% of the whole market share). 

Could anyone create a feature wish on Trello maybe? Or this issue should be plugin territory?
