### ISSUE TITLE
Invitation code - cursor positioning

### ISSUE THREAD

**Issue by lukehefson** [nylas/N1#219]
Hey all! Absolutely loving the app so far!

I noticed on first launch that the cursor positioning for the invitation code field is centrally placed, which feels pretty odd to me. I would expect it to be trailing the `Invitation code` placeholder. Or better yet, the field shouldn't be active until clicking within it, which would then clear the placeholder.

<img width="500" alt="screen shot 2015-10-27 at 09 12 15" src="https://cloud.githubusercontent.com/assets/1469659/10758662/bfbffaae-7caa-11e5-8357-0bb0650312a9.png">

**Comment by CameronHall** [comment]
I'd agree that the field shouldn't be active until clicked however the window is centered so from a UI design perspective it kind of makes sense? Each to their own I guess.

**Comment by bengotow** [comment]
Hey folks! At the moment the placeholder behavior (visible until you start typing, centered because the text is centered) is just standard Chromium behavior. We could write left-justify the input, which I think would make it feel better, but we'll probably be finished with the invitation code system this week so it won't be around much longer!

Thanks for the feedback—design suggestions always welcome :-)

**Comment by lukehefson** [comment]
> but we'll probably be finished with the invitation code system this week so it won't be around much longer!

Makes sense!

> design suggestions always welcome :-)

Wonderful to hear. Thanks!
