### ISSUE TITLE
Thank you but it is too much - Nylas PRO

### ISSUE THREAD

**Issue by Cu8eR** [nylas/N1#2195]
Hi guys,

thank you for your hard work. However 7 USD per month is quite much. I am disappointed, you just started with an open source project and now you wanna money. Shame on you! 

I am returning to Outlook, it is 9 USD/month but you have all features and Office for one price. I hope you will understand after one year... maybe I am wrong, who knows. 

You should consider one time payments for a fully licence. Better than pay every month

**Comment by enoversum** [comment]
@Cu8eR I am not affiliated with Nylas or alike, just to let you know. But still, as they stated, the app as well as the sync engine will stay open source. The 7 US$ are for 'hosting' the sync engine — you could otherwise get your own server and run your own Nylas sync engine. The engine is responsible for links like link tracking and the send later feature, and possibly other things as well. So, what you are paying for is some kind of (extra) e-mail hosting, and a one-time purchase/license wouldn’t cover the cost of it, since it creates cost continuously. 
I would possibly think that a) some users who are attracted to free and possibly don't use e-mail professionally will stop using Nylas N1 and b) the cost will be reduced. People like me already pay for web and e-mail hosting, so these 7$ are on top of the normal e-mail costs I already have, and I still don't know if I'll stay with Nylas for 7$/month after our extended trial of Pro for 1 year (as announced in an e-mail some weeks ago).

**Comment by Cu8eR** [comment]
I fully agree with you. However I read lately, that Airmail will be there for Windows platform soon :)

**Comment by enoversum** [comment]
Of course, they have to make a living, and would it only be a product that wasn't hosted, but built solely by a community, it would possibly work the free way :smile: .
Airmail? Wasn't it just Outlook that you wanted to use :laughing: ?

**Comment by Cu8eR** [comment]
I have Outlook at work because we use Windows, so I have to wait. At home no problem, have Mac so Airmail is used.

Nylas client is not bad, I like it but thats too much. I will stick with Nylas, one year is a quite long time. Then I hope there will be Airmail released for Windows. If not, Outlook is an alternative. My 0,02 $

**Comment by jackiehluo** [comment]
@Cu8eR As @enoversum said, a one-time payment wouldn't be sustainable for us. We really love that N1 is an open-source project, and that's not going to change, but it's not possible for us to continue paying the (high!) infrastructure costs for our users—doing that would put us on the path of the many, many email companies that no longer exist today. That's why the sync engine is open-source and always there for you to run on your own. The other financially viable option would be to mine email data for ads (i.e., Gmail), and that's not what we want to do as a company. You can read more about the decision in our [blog post](https://nylas.com/blog/nylas-pro). It means that N1 isn't going to be for everyone, but we're excited about everything that we're going to be able to build now, and we hope our users will be, too!

**Comment by llllllllx** [comment]
fuck nylas

**Comment by aes512** [comment]
I installed it a few months ago, now that I'm off Office 365 I was going to use it as my primary mail client. I put the kabash to one subscription modeled product, I'll be damned if I subscribe to another - especially one without a calendar?! 

Oh well, I guess I'm back on the hunt for an "ok" main client. Mail continues to "suck".

**Comment by ivanarnold** [comment]
FWIW.

I just discovered Nylas, and am very impressed with it's UI and feature set. But.....

$9 a month is ridiculous for this service. Mailbird is $6 a year. EM Client is free (but ad supported) and offers a lower cost Pro upgrade. Thunderbird is still completely free.

As a casual, desktop user I would use Nylas over other clients. I might even pay a small fee for the service, or a one time pro upgrade fee. But $9 a month is too much, particularly when there are so many low-cost/free alternatives.

Just my two cents. No disrespect intended to the developers, who seem to have provided a very good product.

PS: It seems to make very good sense to charge business class users for the extra sales features and support your product provides, but why pass this cost on to the basic email user, who has no need for these things?
