### ISSUE TITLE
Loading... crash... loading... crash...

### ISSUE THREAD

**Issue by oojacoboo** [nylas/N1#2244]
I have the latest version of Nylas as of today.  I'd check if I could get the app open.

When opening the app, it says "please wait while we're preparing new features", then it opens to what appears to be the main app, only to close within 1 second later.  It keeps repeating this while throwing the CPU into a tailspin.

I've tried clearing out all the Application Support files for Nylas as well as the Preferences in the ~/Library and /Library.  I just downloaded the latest version, whereas the previous version I had was from around 6 months ago.

Console shows the following line item for logging details, but a quick tail on the log file doesn't yield anything...

5/16/16 9:02:53.335 PM Nylas[85968]: Streaming log data to /var/folders/6q/fv2jv43s0_l70vb2jh7tyd3c0000gn/T/Nylas-N1-85968.log

Please advise.  Thanks!

**Comment by jstejada** [comment]
Hi @oojacoboo, thanks for reporting this. So you can't tell which version of N1 you are running right? This should be fixed in 0.4.38, could you try downloading it from https://github.com/nylas/N1/releases and see if you still have trouble? This seems to be the same issue as #2036, so I'm going to merge it in. You can also try the fix that and I mention in that issue and let me know if you keep having trouble.
Thanks!
