### ISSUE TITLE
Idea: Global Signatures

### ISSUE THREAD

**Issue by Maggew** [nylas/N1#2291]
**Feature Request?**

Right now I have six accounts and that means six separate signatures. Would be pleasant to just have global signature so I don't have to copy / paste across all accounts. If I had ten, twenty or even forty accounts, that would be a "fml moment" to have to create a macro and copy / paste after clicking each dropdown.

**Comment by MaxKorlaar** [comment]
+1
I'd also like to suggest multiple signatures to make it a proper competitor to OS X' Mail.app. It has global signatures, signatures per account and multiple signatures per account from which you can choose when composing an email. Since I write emails in multiple languages, this would be a feature that might encourage me to switch from Apple's Mail.app.

**Comment by bengotow** [comment]
Thanks - merging this into https://github.com/nylas/N1/issues/1047
