### ISSUE TITLE
dead image in draft

### ISSUE THREAD

**Issue by willwhitney** [nylas/N1#23]
I added an image and then removed it again, then closed the email and forgot about it. Then when I reopened the draft, the image was back, but dead.

<img width="912" alt="screenshot 2015-10-05 22 24 28" src="https://cloud.githubusercontent.com/assets/597829/10298728/060d428e-6bb0-11e5-8e1c-d24676e829e5.png">

**Comment by dillonforrest** [comment]
Hey @willwhitney, thank you for downloading N1 and sharing this bug!

I couldn't reproduce this unfortunately. Can you clarify your steps to reproduce the draft's dead image?

Here's what I attempted:

1. Open the draft composer
2. Click the paper clip to prompt a file selector
3. Click an image to attach to the draft
4. Click the "x" in the upper right corner to remove the image
5. Click the trash can icon in the lower right corner of the draft composer
6. Open another draft composer --> no dead image

I also tried closing the composer (clicking the red OSX button in the upper left) rather than clicking the trash icon in the lower right in step number 5, and that didn't repro the bug either.

Were you doing something that I wasn't to see the bug?

**Comment by willwhitney** [comment]
It wasn't when I opened a new draft composer, it was when I reopened the saved draft. I also can't repro it right now, so I'll just close the issue.
