### ISSUE TITLE
Request Aborted

### ISSUE THREAD

**Issue by alirezaafkar** [nylas/N1#2309]
I can not login with my email (Exchange)
I get "Request Aborted" error! I'm sure my config is right and it's working in Mozila Thunderbrid

**Comment by RaiseFree** [comment]
me too? any luck?

**Comment by bengotow** [comment]
Hey folks do you know how long it takes for Request Aborted to appear?

**Comment by pierre000** [comment]
the same for me

**Comment by alirezaafkar** [comment]
@bengotow About 2 minutes

**Comment by bengotow** [comment]
We're doubling the amount of time we wait for Exchange auto-discovery in the next release... I think that'll take care of this: eb3b26deb7804a68e42937df4edfa8350cb572c2

**Comment by faheem** [comment]
I'm having this issue and no idea how to fix it... 
the first time i set it up it works fine for a few hours.. 
another thing is 
* the vm seems to run into an OOM error when the RAM is 1 GB. increasing it to 2 GB seems to fix it for me.
* emails dont appear in N1 unless i start the inbox-api. Is that by design?
* once this happens it never seems to work again for me. the N1 Ui gets stuck and no new mails appear.
* N1 shows this in the console 
"Backing off after sync failure. Will retry in 3 seconds.", source: /home/fa/src/N1/internal_packages/worker-sync/lib/nylas-sync-worker.coffee (38)
[23141:0902/155944:INFO:CONSOLE(178)] "Error: socket hang up", source: /home/fa/src/N1/src/flux/nylas-long-connection.es6 (178)

Any idea what that means.?
