### ISSUE TITLE
Gmail Important folder disappears with multiple accounts

### ISSUE THREAD

**Issue by stutters** [nylas/N1#2328]
When adding multiple Google Mail accounts, the Important folder disappears from the folder list. 

I have 2 Google Mail accounts. Both have the Important folder available if added to N1 in isolation. However, the folder disappears if both accounts are added.

OS X 10.11.5
N1 Version 0.4.40-85cf726 (0.4.40-85cf726)

Cheers!

**Comment by bengotow** [comment]
Hey! It sounds like the issue is that the app is switching to the Unified sidebar view, and we don't offer a unified "Important" item. So for example, I have these two accounts:

![image](https://cloud.githubusercontent.com/assets/1037212/15559326/15140482-2296-11e6-9e9f-b832744bca7f.png)


And I only see Important when I pick one individually from this dropdown, or via Cmd-1, Cmd-2 , etc. 

![image](https://cloud.githubusercontent.com/assets/1037212/15559337/23078d3e-2296-11e6-9c80-e9517f1d260c.png)

Does that sound right? I think we can probably add a unified Important view.

**Comment by stutters** [comment]
That sounds exactly right Ben - thanks.

I hadn't realised you could switch out of unified view, which is probably better for me anyway. But having Important in unified view would probably be useful for some users, I would think.

**Comment by bengotow** [comment]
Thanks! Also updating the unified inbox view to include Important when a Gmail account is present here: 94b59f2562dc2f5e39cc0a939f62af62fb900e7e
