### ISSUE TITLE
UX request: no Github contact card when 'no matching profile'

### ISSUE THREAD

**Issue by OJFord** [nylas/N1#2344]
##### Are there any related issues?
No.

##### What operating system are you using?
OS X 10.11.5

##### What version of N1 are you using?
0.4.40

--

**Feature Request:**

It seems silly to me [to display "No matching profile"](https://github.com/nylas/N1/blob/master/internal_packages/github-contact-card/lib/github-contact-card-section.jsx#L91) in the Github contact card.

I'd like to suggest that instead the card is simply not displayed when a matching profile cannot be found. I doubt that there are many users for whom everybody they contact is expected to be a Github user - especially considering it presently only looks at the sender, and doesn't, for example, pull a username out of a thread sent from `notifications@github.com`.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - we currently do this just so that folks who enable the GitHub plugin know that it's turned on. (We had some reports of people saying "it's broken", when in reality we just couldn't find a GitHub user for the email address.) I'll see if we can improve this in the future but we'll probably leave it on for now. Cheers!
