### ISSUE TITLE
new version lost in restart loop, and never stop

### ISSUE THREAD

**Issue by Duan112358** [nylas/N1#2346]
**Platform**: Mac OSX 10.11.6 Beta

**Issues**: New version N1 lost in restart loop, and never stop.

![image](https://cloud.githubusercontent.com/assets/1957818/15646000/f45d47d4-268d-11e6-9a26-e27d67b8964f.png)

![test](https://cloud.githubusercontent.com/assets/1957818/15646016/03aaec96-268e-11e6-818d-0df4a761ffd9.gif)

But, old version is OK, and has sync problem.

![image](https://cloud.githubusercontent.com/assets/1957818/15646190/ecfde2c2-268e-11e6-8c06-aff1b6254a0c.png)

**Comment by azurefang** [comment]
+1 here.

**Comment by bengotow** [comment]
Hey folks! That's really strange. Can you open the file `~/.nylas/config.json` in a text editor and see if there's a line that says `"cursor": "<XXX>"`? If you remove that line, it should fix the problem. N1 should take care of that itself, but I think this may be a bug that was fixed in 3fdffb4b8178a4248a6f09b340a49044baf18d1a and won't be released until later this week.

**Comment by Duan112358** [comment]
![image](https://cloud.githubusercontent.com/assets/1957818/15695072/09019e80-27d6-11e6-9c20-9911be49a191.png)

Yeah, it works. Thks
