### ISSUE TITLE
Bug or just very slow syncing on N1 server ?

### ISSUE THREAD

**Issue by reyman** [nylas/N1#2355]
Hi,
I just installed (less than 2 hours) N1 on Linux Ubuntu 16.04, i sync with my email reyman64[at]gmail[dot]com .

Actually i have very very few messages which appear in my inbox ... I have 2363 inbox message, and only ten appear in N1. I try to remove the db and resync, without any changes.

Slow sync or just a bug on my account ?

##### Are there any related issues?
Possibly https://github.com/nylas/N1/issues/2317 ?

##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
0.4.40-85cf726

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
gmail

**Comment by TheRojam** [comment]
+1 (also with exchange)

**Comment by c0fe** [comment]
I have also seen this occur, not sure if it is related to the issues I have been having but unfortunately doesn't seem the developers care.

**Comment by wickles** [comment]
I was very excited to find a new open source email app, but I added an Outlook account and it barely synced a fraction of my inbox in the 20 minutes or so that I had it open. It takes a long time to get each message and then stops altogether and starts syncing again a minute later, still slowly. 

It's also not handling nested folders correctly. :(

**Comment by jackiehluo** [comment]
Merging into #1004.
