### ISSUE TITLE
Attempting to add attachment (gmail + .ai) is failing on a filename starting with _

### ISSUE THREAD

**Issue by danodm** [nylas/N1#238]
As the title indicates. I'm attempting to send an email (setup as Gmail) with a illustrator attachment (.ai). The file itself is a 1.6mb Adobe Illustrator CC 2015 file and is named with a _ prefix (eg: _file-name.ai). 

The attachment 'uploading' indicator starts and get's about 80% of the way through before disappearing entirely. If I zip up the file it does the same thing, only this time reaches the complete end of the 'uploading' indicator, hangs for a bit then disappears.

When I remove the underscore at the beginning of the file name, it uploads perfectly and attaches itself fine. So based on that I'm lead to believe it's an issue with the file name.

**Comment by bengotow** [comment]
Hi @danodm — thanks for filing this. I tried to reproduce this with Gmail and an Adobe Illustrator CC 2015 file (side note: why is an .ai file with one square in it 1.6MB?!) but I haven't been able to track it down yet.

What platform are you on? Shouldn't matter, but it'd be interesting to check. Any chance the filename contains emoji, special characters, or path separators like `.` or `:`?

I'll see if we can get some error messages into the next release so that things like this are easier to report.

**Comment by bengotow** [comment]
Hey @danodm — just wanted to follow up on this. We found a critical bug in the file upload process that made it time out after 15 seconds. So if your connection was slow, it would upload for 15 seconds and then cancel. I think it was most likely the issue here. We've fixed this in `0.3.23`. Enjoy!
