### ISSUE TITLE
Archive fails & keeps snapping back (Gmail)

### ISSUE THREAD

**Issue by searls** [nylas/N1#2398]
Archive isn't working for me. Whenever I archive an e-mail it just pops back in (the bottom of the client says changing labels). Here's a GIF:

![ugh](https://cloud.githubusercontent.com/assets/79303/15887576/47aef2a8-2d63-11e6-8295-ca4dca9c1c45.gif)

##### Are there any related issues?
No

##### What operating system are you using?
OS X

##### What version of N1 are you using?
Version 0.4.40-85cf726 (0.4.40-85cf726)

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Same for all emails

**Comment by systemeintegratedsolutions** [comment]
I have the same issue.

Windows 10.1 x64 (all Windows updates installed up to date as of today)
Nylas version 0.4.45 (downloaded and installed from Nylas.com site3 days ago)
Email provider: Gmail (google apps)

No 3rd party plugins.

Same happens when I delete an email. Seems to happen on most but not all emails.

**Comment by systemeintegratedsolutions** [comment]
It seems to happen on emails with attachments. I just received a few emails without attachments and it worked fine without a problem, but the ones with attachments are still doing the same.

**Comment by jackiehluo** [comment]
Merging into #781!
