### ISSUE TITLE
Feature Request: Buttons for selection shortcuts like Select All, Select Unread, etc.

### ISSUE THREAD

**Issue by lukefiji** [nylas/N1#2405]
Love using Nylas N1, but just wanted to put this idea out there for those who use the mouse more and for others who aren't so computer-literate and prefer using buttons rather than shortcuts.

##### Are there any related issues?
Not really.

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.40

##### Does this feature exist in another mail client or tool you use?
G-mail, lined right above the checkboxes on the top

**Comment by emorikawa** [comment]
@lukefiji We have Edit -> Select all and it's a good idea to add on that that's select unread. Not sure about buttons just due to the real estate it takes on the UI. Unfortunately we're having an ongoing issue with select all you can see here: https://github.com/nylas/N1/issues/886

I'm going to close this issue since it's highly related to the select all case and we'll be able to see this reference from there.

Thank you!
