### ISSUE TITLE
Select all is not working on mac

### ISSUE THREAD

**Issue by dimitriacosta** [nylas/N1#244]
I sent a feedback a few days ago and I got a response from Brett Gerry and he told me to open an issue and this is what I found.

I've been using N1 and it's great, but when I try to use the cmd + A shortcut to select all the emails currently listed, nothing happened, that function is not working on mac and it could be a little annoying when I need to delete a bunch of emails or move them to a folder or something.

**Comment by Ruto8** [comment]
I'm experiencing the same issue, pretty annoying.

**Comment by bengotow** [comment]
Hi folks—unfortunately, Select-All is a real challenge, because it allows for mass mail actions on potentially millions of threads. We've added basic support for select all in the next release—it selects all in the underlying "page" of thread data you're viewing (which is several hundred threads). I'll close this issue when we release that update. Cheers!

**Comment by visar** [comment]
Is this resolved? And what's the shortcut for select all? Ctrl-A doesn't work in Linux yet.

**Comment by kg4lod** [comment]
Mac: 0.4.16-8cb7748 

Cmd-A only selects text on the screen; Menu "Select All" doesn't do anything

Can't even select multiple e-mails manually, with shift, cmd-click, or shortcut keys

It seems like multiple selection is just not an implemented feature at this point. Is that correct?

**Comment by jstejada** [comment]
hi @kg4lod , this should be addressed with #886
