### ISSUE TITLE
Office 365 folders not fully synced.

### ISSUE THREAD

**Issue by NeySlim** [nylas/N1#2442]
##### What operating system are you using?
Ubuntu 16.04, Manjaro, Windows ...

##### What version of N1 are you using?
0.4.45-7637265

--

**Bug?**
##### Do you have any third-party plugins installed?
nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange (office 365)

The inbox folder of my office 365 is fully synced, but it is not the case of all folders and subfolders in my account. One foler doesnt have mail since april 11th. Another from march 24th ...
Tried on several installs and it is the same. I think the problem is not in the client.

Thanks

**Comment by mtaki14** [comment]
I actually do think that there is a problem in the client. Since the latest update (0.4.45) I get an error that "Nylas N1 can no longer authenticate with <email address>. Click here to reconnect".

Even when I try to reconnect or re-input the correct credentials and server settings that worked before I can't connect to the account.

This is a showstopping bug for me so I'll have to move back to the Opera Mail client until this gets fixed.

**Comment by Omeryl** [comment]
Hey @NeySlim,

There's a few ways you can go about trying to fix this: 
1. Delete and readd the account in your preferences in N1.
2. If that fails to work, close the entire N1 mail client and remove your cache by deleting `.nylas` in your home folder. 
3. If all else fails, it's probably easiest to email support@nylas.com from the email in question. It looks like it could be a Sync Engine-related issue.

**Comment by amilajack** [comment]
@NeySlim so that would be:

```bash
rm -rf ~/.nylas
```

**Comment by jackiehluo** [comment]
Closing this issue for now—if you still have issues, email us at support@nylas.com so we can debug more specifically!
