### ISSUE TITLE
With new N1, can't connect to sync engine

### ISSUE THREAD

**Issue by elbamos** [nylas/N1#2468]
After upgrading N1 to the new 0.45 release, I can no longer connect to my locally installed sync-engine. Launching N1, I get a dialog to sign-up for a Nylas ID, and then an error that N1 can't connect to an onboarding page at localhost:5009.  I've tried updating the sync-engine, but no luck.  

Also, it continues to be impossible to change a password if you're using the local sync engine. You end up creating an entirely new account entry.  Besides re-downloading everything, that also means there are then multiple account entries in the database with the same name, and API calls begin to fail for that reason. 

##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
.45

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Comment by xyNNN** [comment]
My Nylas N1 client receive mails and I can send it to another recipients. But currently it will not sync it to my google mail account. I think this issue is related with the reported issue from @elbamos :) Anyone have a solution for that?

**Comment by Omeryl** [comment]
Hey @xyNNN this is specifically with regards to a user hosting their own Sync Engine in Vagrant, etc. Are you doing that too?

**Comment by xyNNN** [comment]
No, then I will create my own issue. My problem is that I read, label or archive a mail and on my mobile client or dssktop google mail client it will show up the mails as unread and unlabled, anyone have this issue?

**Comment by elbamos** [comment]
The issue I raised seems like it may be universal for those of us who sync locally.  Hello?

**Comment by jackiehluo** [comment]
@elbamos We're working on it—we thought that people could add pretend Nylas IDs in `config.json`, but it's going to be a more complicated fix. For now, could you try rolling back to the last version of N1?

**Comment by elbamos** [comment]
@jackiehluo Well, its good to know you're working on it. 

Going back to the old one isn't a great option.  The reason I was so eager for the new one, is that I hoped it would fix the duplicate-account bug, where if you change a password you end up with two accounts with the same name, and then the API breaks, etc.

**Comment by systemeintegratedsolutions** [comment]
I am LOVING Nylas!!! You guys are my HEROES!!! I have to run it locally though (because we are a small startup and can't afford the hosting fees yet), but thats ok cause we are technical enough to set it all up :) (well mostly :P) 

Anyway, we are also experiencing the same issue. I'm using the pro trial for now. It's free so can't complain or tell you to hurry, but would love to be able to run the local version as soon as we can. We are developing an internal system to manage ourselves i.e. work orders, support, sales staff and integrating with google calendar and mail etc. via the API looks so much simpler than trying to do it directly. Great work guys!!!

**Comment by ersinpw** [comment]
I am experiencing the same problem. @jackiehluo I hope it will fixed very soon :worried:

**Comment by ersinpw** [comment]
Is this fixed? Because I am still getting this error
<img width="425" alt="screen shot 2016-07-15 at 11 40 49" src="https://cloud.githubusercontent.com/assets/8781415/16870286/1ec78e82-4a81-11e6-82a1-efb7f8a8f9af.png">
Even when I change the ip address in config.json
<img width="287" alt="screen shot 2016-07-15 at 11 42 44" src="https://cloud.githubusercontent.com/assets/8781415/16870332/562199b8-4a81-11e6-984d-321da992e892.png">
It does not work

**Comment by miedzinski** [comment]
Still doesn't work.

**Comment by happydemic** [comment]
@miedzinski @ersinpw Which commit are you running? The fix is in #2485, and you'll get it if you build from source. The releases still seem to be at 0.4.45.

**Comment by throrin19** [comment]
I have the same problem here :(
