### ISSUE TITLE
On Mac, Page up and Page down keys do not work in thread list

### ISSUE THREAD

**Issue by zpearce** [nylas/N1#249]
I'm using the split view, and have emails that run past the bottom of the viewport of this element:

```
<div style="height:100%;min-width:300px;max-width:3000px;position:relative;flex:1;" name="Threads:1" class="column-ThreadList" data-column="1" data-reactid=".0.2.$0=2Threads.0.$Threads=21">...</div>
```

I would expect pressing page down to either 1) scroll to the next "page" of content and select the email at the top of the "page" or 2) scroll without changing the selection.

Possibly related: scrolling that same div with the arrow keys is weird. If you scroll slowly, everything works as expected. If you hold down the down arrow (my key repeat rate is artificially high, mind) the viewport does not scroll but the selection changes, leaving you in a state where you've selected an email that is not currently showing in the viewport.

This is Version 0.3.19-de7d1bb (0.3.19-de7d1bb)

**Comment by bengotow** [comment]
Thanks for filing this and providing all the necessary detail!

Page up and page down aren't currently tied to anything—I'll see if we can fix that in the next update. It looks like in Mail.app on the Mac, page up/down actually move you through the currently focused conversation, but once we've set up bindings we can make the behavior customizable.

I was able to reproduce the second issue you mentioned by increasing my key repeat speed. It seems to only happen when you're in split-pane mode, probably because we're attempting to update the message column and can't keep up. I'll see if we can get that fixed.

**Comment by bengotow** [comment]
Quick update—6170b34 resolves the issue with the key repeat speed, and I added new keymappings in 6bee127134f3a38efe1344fd508dd21ecefb71c3. In the next release:

- pageup/pagedown move you up and down in page increments the message list
- shift pageup/pagedown move you up and down in page increments in the thread list

Enjoy!

**Comment by zpearce** [comment]
Awesome. I'll check it out. Thanks!
