### ISSUE TITLE
Availibility extension

### ISSUE THREAD

**Issue by Wikunia** [nylas/N1#260]
Hey guys,

I installed the availability extension but it doesn't work as expected.

It looks like this
![nylas-availability](https://cloud.githubusercontent.com/assets/4931746/10814198/9324168a-7e24-11e5-87ee-c2509b0c3ccc.png)
 
and a click on `Done` doesn't do anything.

Thanks in advance

**Comment by vansieleghemstijn** [comment]
I just wanted to add that I'm having the same issues with this plugin.
I'm using version 0.3.23 on Ubuntu Linux and the developer console lists the following problems: 

Failed to load resource: net::ERR_FILE_NOT_FOUND
nylas://send-availability/fullcalendar/lib/moment.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
nylas://send-availability/fullcalendar/fullcalendar.js Failed to load resource: net::ERR_FILE_NOT_FOUND
nylas://send-availability/node_modules/electron-safe-ipc/guest-bundle.js Failed to load resource: net::ERR_FILE_NOT_FOUND
calendar.html:27 Uncaught ReferenceError: electronSafeIpc is not defined

However the files are included in ~/.nylas/packages/N1-Send-Availability/

**Comment by dregitsky** [comment]
Thanks guys for reporting this! The plugin was indeed broken by updates elsewhere in N1. We just shipped some fixes to this plugin, and deployed a backend server to make it actually work (previously it was just there as an example, since without a backend the event scheduling wouldn't work). If you pull the latest code it should now be fully functional.

**Comment by bengotow** [comment]
This plugin has been fixed and has been renamed "QuickSchedule" in recent releases. Enjoy!
