### ISSUE TITLE
Trial expiration throws "Nylas N1 can no longer authenticate" error

### ISSUE THREAD

**Issue by KyleKing** [nylas/N1#2617]
##### Are there any related issues?

There don't appear to be any identical issues reported on Github. The closest thing was an issue with 2FA, but 2FA is off for all of my accounts: https://github.com/nylas/N1/issues/1092 and this is the error message I'm getting if that counts: https://github.com/nylas/N1/issues/1070.

##### What operating system are you using?

Mac OS 10.11.5

##### What version of N1 are you using?

v0.4.45

--

**Bug?**

##### Do you have any third-party plugins installed?

Only N1-Unsubscribe (I tested deleting the plugin and restarting Nylas just to be sure)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

It affects both Gmail and iCloud

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I can check on a second computer later tonight.

##### Troubleshooting Steps

Nylas suddenly stopped working. I was using Nylas, then five minutes later I went back to read an email and suddenly saw this red error banner:

<img width="1320" alt="nylas n1 nylas n1 today at 8 37 41 pm" src="https://cloud.githubusercontent.com/assets/3784339/16825305/89f11688-4941-11e6-9ee5-dcf1d5ce7f7b.png">

Reconnecting an account works until the page is refreshed. I also tried removing the account and then adding the account back anew. I uninstall and reinstalled Nylas. I also checked the console, but there were no error messages. I'm not sure what else to try?

**Comment by jackiehluo** [comment]
@KyleKing Could you send us an email at support@nylas.com? We can look into your account.

**Comment by AndPlagueFlowers** [comment]
I have this same issue on my PC instance of Nylas too!

**Comment by THPubs** [comment]
Same issue here in my Windows PC

**Comment by jackiehluo** [comment]
Hey, all! The issue is likely that your trial for N1 has ended—we need to add better messaging around that, but you can check it in `Preferences -> Subscription`!

**Comment by AndPlagueFlowers** [comment]
Jackie: mine says my subscription will renew 07/12/2017..... 

I only just upgraded to Nylas Pro the other day

**Comment by jackiehluo** [comment]
Got it, that was the problem for the person who opened the issue—you should email us at support@nylas.com as well! We can't debug much without your email address/more information!

**Comment by AndPlagueFlowers** [comment]
I have emailed support@nylas.com already


--
Regards,

Jainash Prakash

**Comment by jackiehluo** [comment]
Another incidence: https://nylas-chat.slack.com/files/glebovsky/F1RKC8YG2/pasted_image_at_2016_07_14_11_11_am.png

**Comment by tenleftfingers** [comment]
Having the same issue with my Gmail account suddenly (other accounts are okay) on Ubuntu. I'll contact support.

**Comment by elwadi** [comment]
Same issue :(

**Comment by orourkek** [comment]
Same issue for my Gmail accounts.
Version 0.4.40.85cf726 on Ubuntu 16.04

**Comment by pyr02k1** [comment]
Issue also appears for mine as well, but only on Linux Mint. Version 0.4.40 on Mint 18. Laptop and Work PC both show the same. Windows PC works fine on 0.4.45. Upgraded the work pc to 0.4.45-7637265 and the issue remains.

**Comment by tiagohm** [comment]
Same issue

**Comment by julianorafael** [comment]
Same issue with hotmail and self-hosted email. I'm on a Ubuntu.

**Comment by jxj24** [comment]
Same here. How do you go back to a non-pro account. I can find no way.

**Comment by frenchie4111** [comment]
Also having the same issue here, 3 Gmail accounts and 23 days remaining on my trial

**Comment by annielcook** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5001

**Comment by jackiehluo** [comment]
Hey, everyone! The error means that your trial has expired for at least one of your accounts!

**Comment by prashu20** [comment]
I am using nylas from launch and suddenly reconnect message started coming from last 2 days on my ubuntu 15.04.It doesn’t tell if I have to upgrade my nylas account or anything.Please tell what I have to do to resolve this issue.I am using the latest nylas version.

**Comment by orourkek** [comment]
@jackiehluo Understandable, but I can't find any way to continue using Nylas without a pro account, despite no mention of this limitation anywhere in the documentation. How do we continue using N1 without a pro account?

**Comment by jackiehluo** [comment]
@orourkek We have all of the information at nylas.com/pricing—we announced the shift a few months ago in nylas.com/blog/nylas-pro! If you want to keep using N1 for free, you can create your own sync engine and run all of our open-sourced code.

**Comment by orourkek** [comment]
@jackiehluo Sorry to say, but the announcements about Nylas Pro did a horrible job explaining what was going to happen when Pro was released. The announcement email tantalizingly says that you can read the blog post to see "what it means for you", but nowhere in the post or subsequent emails does it mention the fact that non-pro users will not be able to continue using the pre-built binary, or that they have to host their own sync engine.

One can find little help in the READMEs on GitHub, which is where the pricing page sends you for more information about the free tier. There is very little information about building the app (actually none whatsoever in the primary README), and again no mention of having to run your own sync engine. The README clearly states:

> You can download compiled versions of N1 for Windows, Mac OS X, and Linux (.deb) from https://nylas.com/N1.

It makes no mention of the fact that those binaries are pro-only and will not work for non-pro accounts. It continues to say:

> You can also build and run N1 on Fedora

... but makes no effort to point to documentation about that.

Under "Running Locally", the README states:

> By default, the N1 source points to our hosted version of the Nylas Sync Engine—however, the Sync Engine is open source, and you can run it yourself.

OK, so I *can* run it myself, but by default a N1 client built locally will connect to the "hosted version of the Nylas Sync Engine", according to the README. A shocking amount of information in this README is either misleading, incomplete, or wrong.

The incorrect error message text described in this issue is understandable, but terribly disappointing. Based on your response it sounds like Nylas had a concrete plan for how non-pro users were supposed to migrate from the prebuilt binaries to built-from-source, so why was there not an explicit error message shown for this scenario? Why was it not documented? Why was it not included in the Nylas Pro announcement emails or blog post? 

I completely understand the business decisions here and don't feel like I'm entitled to anything from Nylas given that I do not currently have a pro account, but this whole transition seems very haphazard and disorganized. The documentation is sparse, misleading, and in some cases downright wrong. It seems like there was no attention given to the experience of non-pro users, which is really a shame because this is not giving me any motivation whatsoever to become a Pro user.

**Comment by jackiehluo** [comment]
@orourkek We understand—these are all legitimate concerns! For reference, the blog post begins with, "In a few weeks, we are launching a paid version of Nylas N1 and phasing out the current subsidized version." Everything following that is meant to explain why, but we get that it wasn't clear to everyone.

The intent isn't for every user to switch to building the app from source. It's intended for developers for whom it's feasible to clone the repo from GitHub, run their own VPS, and create their own sync engine. For the vast majority of our users, it makes a lot more sense to ask them to upgrade—telling them that they can run their own sync engine isn't super helpful. The instructions for running your own sync engine are linked in the README (https://github.com/nylas/N1/blob/master/CONFIGURATION.md). N1 has to point our hosted sync engine by default (if it points to anything)—the user has to spin up their own sync engine and then point N1 to it, which makes sense.

Let me know if you have any other questions! We're more than happy to clarify where we can.

**Comment by orourkek** [comment]
@jackiehluo All I can say is that Nylas did a very poor job communicating what was happening beyond heavily marketing Nylas Pro. Had I known all of this information before my client suddenly stopped working, I might have paid for Pro!

**Comment by OJFord** [comment]
We shouldn't have to come to an issue tracker to learn this @jackiehluo.

My experience was:
  - I opened N1, it said I had 'Pro' for a year as an early adopter, and wouldn't let me continue 'non-Pro', so I figured sure why not.
  - It expired a month (not a year) later and started throwing errors in my face
  - I thought "I'm not even using any of the Pro stuff [assuming there were new features I couldn't use before Pro] I'll just disable it"
  - The only way to disable 'Pro' seemed to be to sign out, so I signed out
  - Signing out turned out to mean "quit N1"
  - 'Pro' turned out to mean 'Standard'

It's the language that's been used that's caused everyone such problems.

We were told we could "upgrade" to "Pro". The reality was that we could "continue" to "use the same thing" and soon be asked to pay for it.

That's fine - but it was incredibly unclear.

**Comment by jackiehluo** [comment]
@OJFord You're not wrong! We're a small company, and it's not always easy to tell when what we're doing isn't clear to everyone. Messaging is hard, especially for a shift from a free service to a paid one, and we're still finding ways to make sure that our users understand when we make changes, add features, etc. We thought that the newsletter/blog post and new pricing page were enough, and that's obviously not the case for everyone—but we are working on it!

P.S. If you never got the code for the year of Nylas Pro, it's likely because you unsubscribed from our newsletter, so email us at support@nylas.com (ASAP!), and I'll see if I can help!

**Comment by tiagohm** [comment]
> How do we continue using N1 without a pro account?

is it possible?

**Comment by OJFord** [comment]
@jackiehluo You can't expect people to have time to read supplementary things like blog posts and new pricing pages.

When you open N1 and that pop-up appears, instead of saying:

> Upgrade to Pro! 1 Year free!

It should say:

> N1 is no longer free, there's more information <here> - including how to host the sync engine yourself if you're so inclined. You can however sign up and receive 1 year free while you decide.

That's just a suggestion, but the key things are:
  - don't call it an "upgrade", because it manifestly isn't
  - don't call it "Pro", because it implies some "Basic" or "non-Pro" version is available - which people are here asking for - and it isn't

**Comment by xdutaotao** [comment]
@jackiehluo It seems we cannot host nylas-sync-engine server for Exchange Mail server by self building, right?  We just want to sent/receive mails without any mobile usage/sync simpilly, so we need to pay for 'Pro' to achieve it ? no any 'standard' version or 'commnication' version?

**Comment by idomusha** [comment]
Issue here too: 4 days remaining.

**Comment by dalvaren** [comment]
same issue here

**Comment by jk2K** [comment]
any news? has been half a month

**Comment by bengotow** [comment]
Hey folks—a fix for the "Nylas can no longer authenticate" bar shipped in the update Thursday (0.4.47). Cheers—

**Comment by onbjerg** [comment]
So weird. I signed up for the trial today and I added one account. Now my trial has already expired.

**Comment by jackiehluo** [comment]
@onbjerg Most likely because you used N1 in the past—email us at support@nylas.com with your Nylas ID!

**Comment by zezuzaza** [comment]
I also got the same problem. So we have to purchased it?
