### ISSUE TITLE
Never received a coupon code at all

### ISSUE THREAD

**Issue by StarrWulfe** [nylas/N1#2646]
I'm not entirely sure where I should even post this, but after using the beta version of N1 for months, I'm locked out with a "30-day trial period expired" notice.

I was unaware that I needed to look for a coupon code to redeem, and I never received one. 

I did go and create a Pro account on the server on June 16th.  But I've been using N1 since well before then. Why create a coupon redemption system when you already have a database that shows the account creation dates and primary email addresses of those in your server anyway? This should just be automatic IMO, but maybe it takes too much time to crosslink? 

Anyway let me know what can be done about it. 

Thanks

**Comment by sidneicarlos** [comment]
I had the same problem. So I asked for support to remove my data.

**Comment by Shinobi1507** [comment]
sudo apt-get remove nylas -y 

It doesn't matter if you find your code cause they are expired now anyway. Got my code but thought it had been applied automatically, so I was surprised to be greeted with this message. Tried my code, expired. Uninstalled nylas. 

Its great software, but honestly its more money than O365. So let thank sink in for a minute. Few bucks more and it gets you office 365 for 5 computers. https://products.office.com/en-us/buy/compare-microsoft-office-products I get most of us use linux so its not really relevant but I can't justify that much for an EMAIL client. 

I will want the free year if they decide to fix it. Otherwise I'll go back to Thunderbird.

**Comment by bengotow** [comment]
Hey folks! Sorry you didn't receive a coupon code—we sent approximately 50,000 coupon codes to users who were active in May and June, but we're aware of a few people who unsubscribed from our mailing list or flagged Nylas emails as spam and didn't receive them. We made redeeming coupon codes an explicit process because giving folks a free year transparently would just push the need for this communication down the road a year! (A year from now, folks would be cut off and equally surprised.)

It's worth noting that we don't consider apps like Polymail, Mail.app, and Thunderbird to be competitors—if Thunderbird meets your needs it's almost certainly going to be cheaper! N1 ships with features like mail merge, link tracking, read receipts, rich contact info, etc. that our customers typically get through paid Gmail hacks and Chrome extensions.

I hope you'll consider purchasing a subscription!
