### ISSUE TITLE
adding browser functionality

### ISSUE THREAD

**Issue by fergusmeiklejohn** [nylas/N1#2773]
Is there something fundamental preventing us from adding browser functionality to an email client?  We get so many HTML emails inviting an interactive response, but when we interact with them they just launch a browser.  These emails look like interactive webpages but really they're just links.  It's a poor UX.  Every email client I've used is the same in this regard.  Could we build build something different?
Could we add browser functionality to N1?  It would be a radical improvement of the user experience over any other email client (AFAIK) and it would presumably greatly enrich the plugin developer environment.

I've been thinking about this for months and thought I'd throw it out there..  Maybe it's a bad idea or maybe there are issues I'm not seeing like around security for example.  Also rolling our own browser would be a lot of work but could we incorporate another OS browser?

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by grinich** [comment]
The short answer is emphatically *yes!* This would be very cool to do and N1 is an ideal place to experiment with these ideas.

However, this feature isn't something in our current roadmap (next 6 months) since we have lots of other things to build and bugs to fix before then. But I personally would love to see someone prototype this with N1. :)

**Comment by bengotow** [comment]
Going to go ahead and close this because it's not on the current roadmap. Definitely do-able, but doing it well would be quite an undertaking. I also think there are several issues, like the fact that it wouldn't share cookies with your Chrome/Safari session, that might make it more annoying than you imagine. We'd definitely want to prototype it first!
