### ISSUE TITLE
README link to nylas.com/N1 doesn't point to packages

### ISSUE THREAD

**Issue by brainwane** [nylas/N1#2866]
The README.md file says:

> You can download compiled versions of N1 for Windows, Mac OS X, and Linux (.deb) from https://nylas.com/N1.

When I go to that URL it redirects to nylas.com and I don't see where I can download compiled versions such as .deb files. Perhaps this sentence is obsolete?

##### Are there any related issues?

No.

##### What operating system are you using?
Linux Mint Qiana.

##### What version of N1 are you using?
None.

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Reproducible by visiting https://github.com/nylas/N1#download-n1 .

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Not applicable.

**Comment by IvoPereira** [comment]
+1. Here for OSX.

**Comment by jackiehluo** [comment]
Hey! The builds are on nylas.com if you just click the download button!

**Comment by brainwane** [comment]
@jackiehluo Ah, so I have to register at https://billing.nylas.com/register in order to download the builds? Got it. Thanks!

**Comment by r0bbie** [comment]
There doesn't seem to be a "Download" button on the N1 homepage anymore, unless I'm missing it? This coupled with the information at https://nylas.com/pricing/ leads to a lot of confusion. i.e. The "Developer" option states "Build-it-yourself", which I presume is meant to be phrased as an option, but would more likely be read by people as a requirement.

So, to anyone coming across the N1 software for the first time, the website now gives the message that the only way to use N1 freely is to build it yourself. Is this intentional?
