### ISSUE TITLE
Bug: Disappearing buttons

### ISSUE THREAD

**Issue by andrewspear** [nylas/N1#2896]
Several times a day I find that the icons at the top of the messages disappear:

<img width="989" alt="screen shot 2016-10-04 at 4 37 52 pm" src="https://cloud.githubusercontent.com/assets/1787336/19061937/867a2476-8a51-11e6-8ba9-b9f38bef735c.png">

After a restart they're back to normal:

<img width="994" alt="screen shot 2016-10-04 at 4 38 23 pm" src="https://cloud.githubusercontent.com/assets/1787336/19061941/8cf4e958-8a51-11e6-9ce3-cf48e9e074ca.png">

The buttons don't return when changing the theme, a restart is the only way I've found to resolve the problem. I only have one plugin installed: https://github.com/colinking/n1-unsubscribe

_Mac Version 0.4.56-816edde (0.4.56-816edde)_

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I think I've found the relevant exception from our internal logs, I'll see if we can get this fixed in the next release. Just to be sure, next time this happens can you open the Developer Tools in the window (Developer -> Toggle Developer Tools) and copy any errors you see in the console at the bottom? (You may have to press Esc for it to appear).

**Comment by andrewspear** [comment]
It happened again this afternoon, here's the error from the Developer Tools console: http://pastebin.com/FXzZrh5H

**Comment by jackiehluo** [comment]
Aw, it looks like that's happening because the `n1-unsubscribe` plugin is broken. Closing this issue for now—you may need to open one with the developers for that plugin!
