### ISSUE TITLE
Backup config.json?

### ISSUE THREAD

**Issue by eeschimosu** [nylas/N1#2900]
I recently got an error from Nylas saying that my config.json file is corrupted. Anyways it created a new one, and I had to add all my accounts again. That's not nice since I manage about 40 accounts. 

From where can I take the config.json and save it in the cloud to prevent things like that from happening?

**Comment by bengotow** [comment]
Hey! If you're using the latest version of N1, it should display an error allowing you to choose what to do before it overwrites the file. (You may need to update to `0.4.56`). If you want to backup N1's configuration, you could symlink the `~/.nylas/` folder to somewhere else, like Dropbox. Unfortunately you can't symlink just the `config.json` file in that folder, because we update it atomically rather than editing it in place. Hope that helps!

**Comment by eeschimosu** [comment]
Thanks! I'll do as you suggest!
