### ISSUE TITLE
Is this a real email client or not?

### ISSUE THREAD

**Issue by andrewpros** [nylas/N1#2952]
Hi.
It is probably not an issue, but i really don't see any better place to ask this and explain some concerns.

Is Nylas really a standalone email client or not? Cuz it looks like it is not.

I wanted to use the free version, no sure why i have to compile it by myself, so i first downloaded the release windows exe.

After installing, it asks me for Nylas account and i don't get it, why i need and account for an open source free email client?

Shouldn't is asking me to configure e-mail account instead?

Now after that i started to looking the reasons for this, i'm using the bat on daily basis and there is just setup the e-mail accounts.

I found out that Nylas is using an sync engine, also open source and it looks like it is needed to use Nylas, without it it won't work.

On top of that it only provides a rest api.

So let mi get this straight, the bat is a standalone email client that has anything build in, support for all e-mails, exchange formats, protocols etc. but Nylas has this part separated into an sync engine that needs to run also to the client to work?

So the real client is the sync engine? This is the software that logs to e-mail accounts, be it gmail or something else, downloads, sends them etc. ?

And the Nylas N1 i merely a client for sync engine and don;t have any e-mail specific functionality on its own?

I'm right?

This is what i need the account and need to pay for it, cuz you are running the sync engine on a server? So what, all my e-mail are first stored on your company machines, then Nylas is connecting with it using only rest api?

I just try to understand, being myself a programmer, that is just not why i was looking for.

If this is the case then i see why it needs to be commercial, it is free open source but cuz of your choices it is very difficult to use it for free.

The sync engine should be a part o Nylas client for standalone free usage, as an library, and not communicating by rest api but direct connection, like i mean - libraries,  not as a separate server.

I'm sadly suspect that this is done by purpose to make it hard to use for free, but not so long ago advertising it as a free email client, yes, but is is really hard to use, lets face it, a simple user don't have a chance to set it up and use, it is impossible.

Also this way it is just no point in even forking it to make it happen, it is a oblivious problem to track and merge the fork in this situation and of top of that, running it by itself is not secure at all.

Why not make it simple? Like build the exe with standalone usage in mind? User just chooses at the startup what he wants, build in standalone email client without nylas account or the online commercial account.

But then it would be strange that if someone wanted to resign, he could not switch easily to free standalone client, so this would needed to be build in from the start.

Not thats my concerns and it looks like i'm right, is there any plans to change this, make it better?

If not i'm sadly sure that sooner or letter it will be dead, but it could be something great.

**Comment by ArchangeGabriel** [comment]
You’re almost right. The real mail client is the sync engine, and N1 is a client for this sync engine.

They are already a lot of issues/people around being able to bundle the sync-engine on client side. If they are really a bunch of those people with the knowledge and capabilities to do it, a fork may happen with this feature.

The reason Nylas won’t remove the sync-engine is because they need to have a server side for some features (like send later). Whether they went this way to have a business model or not, that’s a different point…

**Comment by andrewpros** [comment]
Well, i'm not against sync engine being a separate thing, i'm more like to integrate it with Nylas client, if it is free and should be a standalone email client then there is really no point in communicating with it by rest api.

I wish they only make it simpler to do that.

**Comment by jackiehluo** [comment]
@andrewpros Hey! Why we use the sync engine is a super valid question that a lot of people have had. The product we're building needs to have this server-side sync engine for a lot of features we'll be starting to build soon—it makes the client much, much more lightweight (https://support.nylas.com/hc/en-us/articles/217518207-Why-does-Nylas-N1-sync-email-via-the-cloud-), which is pretty important in an app that's already doing a lot on its own and needs to optimize for size/performance. We do want to make the open-source version of the app easy to use, which is why we've tried to make it easy with a UI flow in onboarding for connecting a self-hosted sync engine. However, we need the sync engine to be separate from the client, and that does increase complexity, both for us as developers and for people who want to build it on their own—it's an email client optimized for usage in the workplace and power features that rely on a server-side component, not the kind of usage that people already have with standalone mail clients like Airmail and Thunderbird.

**Comment by andrewpros** [comment]
Well i'm using the bat and it is small, very high performance lightweight client that has all the features e-mail client should have and it is standalone, so your arguments are invalid.

The bat is written in a native format so you just can't be faster than that.

And i'm not telling that is should not be separate, but for standalone usage it should be integrated in the client and the user should have a way to switch free local/paid service, instantly.

Unfortunately the code is strongly tied with your paid service and the binary client can't even be used for free. So without the will for changes on your side, nothing will happen.

Simple user has ZERO CHANCE to use it for free, it is too difficult, so to be honest the free version is a pure fiction.

Well, one thing will happen sooner or later, this project will be dead if no viable free version support will come.

**Comment by jackiehluo** [comment]
@andrewpros In the context of our client—we use Electron so that it's cross-platform, and we also built an extensible plugin system. It's certainly possible (and not hard!) to build a lightweight client without a server-side component if simple email functionality is all you want. That's not the priority for this project specifically, so this client just may not be the best choice for you.

**Comment by andrewpros** [comment]
The Bat is a lightweight client without a server-side component and yet i provides very advanced functionality, so again your point is invalid.

Your are missing the point here or deliberatively pretend that you don't know what is the point and that i'm looking for something else.

Nope, i'm looking just for that, BUT despite what the site claim it is impossible to simple use it for free and the clients (windows here) are stripped from options that would allow that, so you are as it looks doing nothing at all to make it simple for free usage.

It is unacceptable to provide free version in which the source code needs to be modified to work, basically forcing everyone to maintain a fork, strip commercial ties, merging etc.

Lets face it, you don't want the free version to work and be popular, sad, another great project wasted by greed.

**Comment by ArchangeGabriel** [comment]
@andrewpros You don’t get it. Whatever really advanced functionality `The Bat` provides, they can’t be ones that rely on having a server side component (unless you have a non-standard SMTP/IMAP server, but that’s not common). So, for the goals they want to achieve with N1, they need a server side. Someone might fork N1 and the sync-engine to build a light version of N1 with only a client side, thought I’m not sure there is much to gain this way and whether starting a new client wouldn’t be a better idea.

Also, if `The Bat` is that great, why don’t you use it instead of N1?

Note that I don’t use N1 at all, because it’s missing key functionalities for me, while I don’t need anything the server side provides I think, so I would very much like a nice client-only mail app with a N1-like UI (the UI and some old rotting bugs are the things that make Thunderbird unsuitable to me, even if it’s currently my best choice available).

**Comment by andrewpros** [comment]
@ArchangeGabriel 

Well i would be happy to check if N1 is any good, but despite their claims as being free, well maybe, but impossible to test and simple use.

AND I GET IT, they and you don't get it that i'm not against server component, just rebuild it to make it simple to integrate it as a part of N1 standalone free version, but if they advertising a free version then MAKE ONE, don't lie to make free false adverts.

The is NO POINT in making a fork that will be constantly out of sync with the original project, they can rebuild it and make it simple, that's the only sane way to make it.

**Comment by ArchangeGabriel** [comment]
@andrewpros They made it. There is free version now, and from my understanding, it might even work without sync-engine (but with less features obviously).

**Comment by andrewpros** [comment]
@ArchangeGabriel Thx for the update, i'm speechless, didn't hope they would ever change their minds based on provided answers, but it looks that they came to reason, thank god.

Unfortunately for now the windows version is not available yet, so i can't test it and check if its now also working as any normal email client.

But the moment it show up i will test it.

**Comment by grinich** [comment]
We'll get the Windows build out soon. We have a very small team.
