### ISSUE TITLE
Send with SMTP accounts configured in gmail

### ISSUE THREAD

**Issue by ivancasasempere** [nylas/N1#308]
In my gmail, i have like 10 email accounts added as SMTP and 5 others in POP3. I receive all emails correctly, but i want to reply with my others SMTP email accounts. It's possible to implement?

**Comment by albertinisg** [comment]
I was looking for the same feature. Would be great to have it!!

**Comment by mbilker** [comment]
If changing the `Send: ` MIME header allows this, then this is implemented in the latest version through Aliases.

**Comment by ivancasasempere** [comment]
Just one more thing! If I'm seeing a mail sent to one of my alias, whould be nide to authomatic the "from" and put this alias, not the default mail.

**Comment by ivancasasempere** [comment]
But... nice work! :dancer:

**Comment by jmfederico** [comment]
I was after something like this, and I still need to change the way it works.
In my case I forward all my @yahoo mail to my @gmail address, and I need to reply from my gmail account using yahoo's smtp servers, otherwise every email I send will be marked as spam.

As far as I can tell, this doesn't happen, and I wouldn't mind coding a plugin in that allows for this to happen, but I honestly don't know where to start, of if it is even possible, since if I understand correctly smtp server is handled by the nylas cloud.

**Comment by bengotow** [comment]
Merging this into #2316 for the remaining bit.
