### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by ArchangeGabriel** [nylas/N1#3196]
Hi,

I’m a bit confused with version numbers: https://github.com/nylas/N1/releases

Is 1.5.0 for the Nylas Pro software while Nylas Mail/Nylas Basic (still not clear about which name is what BTW) is at 1.0.9?

Also, if I build Nylas from the git repo, what do I get?

Thanks!

**Comment by hallamoore** [comment]
Hi there,

Yeah, things are pretty confusing right now! 1.5.0 is for N1, while 1.0.9 is for Nylas Mail.

To delve into more detail, there are two semantic groups going on with our naming: one for application architecture and one for price tiers. For application architecture, N1 refers to the old architecture and Nylas Mail refers to the new architecture. For price tiers, Nylas Pro is the paid plan while Nylas Basic is the free plan. 

It's even more confusing because Nylas Mail doesn't currently have all the Pro features implemented, so our Nylas Pro users are on N1 and our Nylas Basic users are on Nylas Mail, which makes it tempting to equate Nylas Mail with Nylas Basic. But we'll eventually migrate our Nylas Pro users to Nylas Mail too.

If you build from master on the git repo, you'll get N1. I don't believe we have everything in order for developers to be able to build Nylas Mail from source yet, but we pull in the [n1-next](https://github.com/nylas/N1/tree/n1-next) branch when we build it ourselves, so feel free to check that out!

I hope this clears things up! Let me know if you have any other questions.

**Comment by grinich** [comment]
FWIW we are definitely going to have a build-it-all-from-source version of Nylas Mail eventually. There is just some wrangling to do with our repos before that's possible.

**Comment by ArchangeGabriel** [comment]
Thanks both of you for your answers. :) So the distinction between names is more clear to me now, and also answer my question regarding naming of the packages in distros: it should be nylas-mail.

I’ll wait for your work making us able to compile from source then. Keep up the good work! ;)
