### ISSUE TITLE
disable "conversation view off"

### ISSUE THREAD

**Issue by joazif** [nylas/N1#325]
Hi,
is it possible disable conversation view ? 

I think this : 

![disable](https://cloud.githubusercontent.com/assets/15521290/10863662/db81f818-7fd5-11e5-8508-a67db8ac658f.jpg)

**Comment by bengotow** [comment]
Hey @joazif — thanks for reporting this. N1 is built around a threaded conversation model and we don't have any plans to support non-threaded display. If you're interested in working on this, you could probably achieve this with a package but we won't be building it into core.

**Comment by raknerak** [comment]
Actually, I prefer non-threaded display mode. Because it is really not easy to find and follow emails :-1:

**Comment by godrei** [comment]
Same here

**Comment by petemolinero** [comment]
Same. Nylas seems super nice, but not being able to disable conversation view is a dealbreaker for me. To each their own!

**Comment by adam-szabo** [comment]
Ah, bummer. Same here. :(

**Comment by acevedomiguel** [comment]
cannot disabled? T_T awesome product anyway

**Comment by paulzny** [comment]
Why do so many startups do this - develop on assumptions instead of user feedback?  Over and over again, I watch startups accelerate their burn rate, with failure to achieve market success due to lack of true market fit.  Nylas has the potential to be the best mail client on the market.  The one major issue is unthreading conversations.  If Nylas ONLY wants to be a personal email client, then threaded conversations is not a problem.  However, many, like myself, are desperately looking for a good, clean mail client that can be used for work AND personal emails.  For work, being able to place client and employee emails into their corresponding folder, as well as snoozing are insanely valuable to my productivity.  But if conversations between 10 different employees or a mixed bag of clients and employees are grouped together, it makes it impossible for me to organize and categorize the emails, meaning my productivity with my inbox hits a wall.  I LOVE CloudMagic, but it too has fallen short with the dreaded conversation threading.  However, at least they are wise and listening to their audience and implementing the change.  I am interested to see who gain more traction in the market place in the next 180 days, as CloudMagic is implementing the option to unthread conversations within 30 days. All the best of luck to you Nylas, without listening to your audience, you are going to need it.

**Comment by dkraljic** [comment]
I hope this thread is old and the Nylas team has changed their mind on threaded views. I prefer threaded views. However, the current implementation is pushing me away from Nylas. Currently, when conversation view, I end up with every email that was part of that thread repeated inside every email in the thread. Gmail has solved this beautifully. That is by truncating anything prior to the last message. You'll see a little button with ellipses. As it is right now in Nylas I am constant scrolling a long list of replies just to get past one email in the conversation. Worse, the replies are indented, and at some point become one character wide. It is kinda ridiculous. I too feel that Nylas has the potential to be the best email client out there. I even paid for it. Sadly, I am likely to stop because of this poor conversation view.

**Comment by dkraljic** [comment]
Just another quick thought on conversation view. If the last email in the conversation had an indication that it is the last. Maybe in the header to left of the reply button - text that read "last in thread". That way I would not have to scroll down past all of the nested replies in that individual email to check if it is the last. This is not a replacement for truncating all of the nested replies but it would potentially be a "quick" fix for the time being.

**Comment by paulzny** [comment]
No, they did not change their mind, but check out CloudMagic.  They listened to their audience and have adjusted the conversation view, unlike Nylas, Canary, Polymail and others that THINK they know what the audience wants, despite multiple pleas to change it.  


Kind Regards, 

Paul Jerome



-----Original Message-----

**Comment by vinnytroia** [comment]
Conversation view sucks. I'm really pissed that i purchased a license before thinking to look that up. It's literally impossible to see who a message is from since so many names are crammed into a little subject line. Not to mention organizing and finding mail is a huge chore. I am going to be requesting a refund.

**Comment by paulzny** [comment]
Hi Vinny, 


Try Newton (formerly Cloud Magic) or AirMail 3.  Honestly I like the N1 interface better than those two, but both companies actually listen to their audience and made conversation view and option.  Even Google/Gmail made conversation threading an option.  I don't understand why email client providers don't follow.  


Kind Regards, 

Paul Jerome



-----Original Message-----

**Comment by DarthOpto** [comment]
This was a dealbreaker for me as well. Nylas looked nice, but conversation view sucks, and sucks hard. Not being able to turn it off made me uninstall Nylas so glad I didn't pay for this app.

**Comment by ajvogel** [comment]
My problem is more that conversation view doesn't work. It seems like it is based purely on the subject of emails. So I have conversations spanning three years because they have the same subject. Not to mention receiving emails without subjects that all get lumped into one big conversation. We should be able to turn of conversation view, or the very least tweak the time period of emails that get grouped into a conversation.

Unfortunately, I already paid for the app, but I will definitely not review my subscription.
