### ISSUE TITLE
Character input error when use chinese input method

### ISSUE THREAD

**Issue by hangyan** [nylas/N1#332]
<img width="339" alt="screen shot 2015-11-01 at 3 03 09 pm" src="https://cloud.githubusercontent.com/assets/3939015/10867670/c0708056-80a9-11e5-9018-7c3ed28cbedc.png">

**Comment by hangyan** [comment]
This only happens in forward message, reply and new message is ok

**Comment by brettgerry** [comment]
Also, from a user:
"When I type chinese pinyin input in search bar, the input will type twice letters in it."
![image](https://cloud.githubusercontent.com/assets/2729391/10977793/0d3fd868-83a8-11e5-9355-b8800d3cca38.png)

**Comment by emorikawa** [comment]
This has been fixed in c2ce51a and will go out in the next stable release (0.3.24).

The issue was due to the composer not properly handling [composition events](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent). We now treat the full composition lifecycle as a single atomic edit operation.

This issue was related to a variety of other issues including: #62, #384, #332, #89, #211
