### ISSUE TITLE
Floating windows when in Full-Screen mode

### ISSUE THREAD

**Issue by MaestroDarius** [nylas/N1#345]
When in Full-Screen mode, any action requiring a new window will open a full-screened panel. Would be better to have a resizable floating window when, for example, composing a new message.

**Comment by bengotow** [comment]
Hi @MaestroDarius — are you on Mac OS X in full screen mode? I don't think it's possible for the app to open additional windows in that mode, so you'll need to use the inline composer.

**Comment by MaestroDarius** [comment]
So, it's not possible to have a floating "compose new message" windows just as Apple's Mail does, when in Full-Screen mode?

**Comment by jelmervdl** [comment]
Unfortunately the inline composer is not always adequate nor available (e.g. new mail instead of reply.)

This could possibly be implemented by embedding the new message window as an overlay, a bit like Gmail does it, preferably only when N1 is already full-screen.

I think it is perfectly acceptable to implement this in a very limited way, for example using a modal overlay as in Apple Mail before El Capitan. Maybe add the ability to minimise that 'modal' like in Apple Mail in El Capitan, dock it only on fixed positions like Gmail does.
