### ISSUE TITLE
Is it impossible to manual fetch mail in N1 because of using open source sync engine?

### ISSUE THREAD

**Issue by Fortiskrito** [nylas/N1#379]
Fetch mails is done by worker-sync(N1/internal_packages/worker-sync) using NylasAPI.

**Comment by bengotow** [comment]
Yes—the app connects to the Nylas Sync engine via a streaming socket connection. As soon as mail hits the sync engine, it's pushed to the app. There is no meaningful way to "fetch new mail", because the sync engine holds IDLE connections open to Gmail / IMAP, etc. Hope that helps! We've had some sync speed issues in the last week and things should be getting faster soon.
