### ISSUE TITLE
How do I run N1 without registering nylas.com?

### ISSUE THREAD

**Issue by d33tah** [nylas/N1#38]
I got there from some news articles claiming that there is a new open source alternative to Thunderbird. I tried to download a release, but it's not there and when I built the code, it says that I have to get an invitation from nylas.com. Is there a way I can actually run N1 without registering there?

**Comment by fenta23** [comment]
you can build it from source code...

**Comment by itszero** [comment]
I'm using it with a local instance of sync-engine, works great!

Read these two pages should get you started:
- https://github.com/nylas/sync-engine
- https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine

One thing to note: you might want to use your own OAuth key. :smile:

**Comment by galvao** [comment]
@fenta23 I don't think you've read @d33tah's entire question. 

@d33tah: Apparently you can't. What they're doing is a common marketing strategy (Google has done it tons of times), so we have to wait.

**Comment by bengotow** [comment]
Hey @d33tah — N1 runs against the Nylas Sync Engine, which converts tons of different mail protocols into a common REST API. It handles the differences between Exchange Server 2003 and Exchange Server 2007 and lots of other stuff, so that the client can be lightweight and focus on being a great mail client.

The sync engine, like the mail client, is also open source! Our production version of it (running at api.nylas.com) has a fairly intense security setup, but if you'd like to run it yourself you totally can. There are instructions in that repo for spinning it up inside a Vagrant VM:

https://github.com/nylas/sync-engine/blob/master/README.md

Once you've got that running, there are some brief instructions here for changing a few things in the mail client source to point it at your version of the sync engine:

https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine

At the end of the day, it's a lot of setup to get a nice mail client (a whole vagrant VM with a sync engine, maintaining a cache of your mail and serving it via a REST API). We envision most people running against our hosted version of the backend. If there's enough interest, maybe it could be distributed as a docker container :-)

Hope that helps!

**Comment by Nijikokun** [comment]
You can build it, but you still need an invite code... I even coded around the invite window, but the API does a check against invite codes so you'll have to wait for that.

**Comment by janniklorenz** [comment]
WTF, such a great project need's a central server to fetch the mails as cleartext!? Seriously?

I understand the reason of an invite system, course the central server can't handle unlimited requests, but why not make it easy to set up my own sync engine, rather than making the whole thing simply unusable?

**Comment by bengotow** [comment]
Hey! You're welcome to run the sync engine yourself - there are
instructions here:
https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine.
Takes about ~30min to get going I think. Long term, we envision folks using
our hosted version of the sync engine. We plan on adding new features,
APIs, etc (like send later), so tracking master on N1 may mean running
migrations and upgrades to your copy of the sync engine. That said, it'll
always be possible to run the stack yourself and it's definitely the way
around the current invite code system.

Ben

**Comment by xorinzor** [comment]
perhaps if you guys didn't make it so expensive I wouldn't mind paying for it, $84 per year is insane though.

And don't make it look like setting up your own sync engine is easy, because it completely lacks security that way..

Really disappointed in Nylas, thought I finally found the perfect mail client only to figure out after 30 days that's not the case.

**Comment by kazzkiq** [comment]
I have to agree with @xorinzor. N1 is the perfect e-mail client for the unfeasible price.

This may sound like overreaction as in USD or EUR currencies the monthly fee costs no more than maybe two coffees. But in any other country with a *not-so-strong* currency (aka. the rest of the world) the value can get pretty salty.

Sample in BRL (Brazilian currency):

Nylas N1 **monthly** fee:
**U$7-9** (one or two coffees, no big deal)  → **R$22-30** (*lots* of coffees, saaalty)

I know this isn't even the right place to pull price debate, but I just felt I should expose an issue that may also be keeping many *non-US/non-EU* clients out of your scope.

**Comment by christensen143** [comment]
I'd really like to get the open source version of the sync-engine up and running on a digitalocean droplet instead of locally on my machine. Are there any instructions for that? I guess theoretically I could do the same on an Ubuntu droplet with virtualbox but that seems like overkill. I'm going to hack it out one way or the other.

A quick note about those grumbling about the cost. There are different models for funding software projects and very few "paid" software projects become open source. Having access to the code allows us to hack out ways to make it work for what we want. Nylas has done the hard work of making a beautiful interface and figuring out a transport method. If you don't want to do the hard work of figuring out how to make it work for yourself then cough up the dough to use the product. Nothing is ever free. Without some sort of financial support projects like this eventually die. I prefer the donation method for Open Source and I give to projects that provide me a solution that I want or need to keep using. Same goes here.

**Comment by okadri** [comment]
@christensen143 I used this repo to create a Docker container, work like a charm:
https://github.com/nhurel/nylas-sync-engine

**Comment by Razva** [comment]
> You're welcome to run the sync engine yourself - there are instructions here: https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine
That link is gone. Can we still connect the Nylas Mail client to an open-source SyncEngine, without the need to compile our own client?

**Comment by joshuat** [comment]
It looks like those links were moved around, I went through the commit history and found them here:

https://github.com/nylas/nylas-mail/blob/95b68f13686791a5350eb41e32858f05e9f274f2/packages/nylas-mail/CONTRIBUTING.md

https://github.com/nylas/nylas-mail/blob/95b68f13686791a5350eb41e32858f05e9f274f2/packages/nylas-mail/CONFIGURATION.md
