### ISSUE TITLE
Double tone issue, while typing in greek

### ISSUE THREAD

**Issue by stoge** [nylas/N1#384]
Hi,

I am using n1 on MacOS X -Yosemite, and i am having an issue,
When I am typing in greek, when i press the tone key, it works as if I press the key twice.

I am attaching a pic regarding the issue
![screen shot 2015-11-09 at 14 32 04](https://cloud.githubusercontent.com/assets/1492468/11033773/b421de62-86ee-11e5-8e71-ff227589cbb2.png)

**Comment by grinich** [comment]
Hi Stoge-- this should be getting fixed in the next release. Sit tight!

**Comment by stoge** [comment]
Great! Thanks! :D

**Comment by jstejada** [comment]
Merging into duplicate #211

**Comment by emorikawa** [comment]
This has been fixed in c2ce51a and will go out in the next stable release (0.3.24).

The issue was due to the composer not properly handling [composition events](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent). We now treat the full composition lifecycle as a single atomic edit operation.

This issue was related to a variety of other issues including: #62, #384, #332, #89, #211
