### ISSUE TITLE
pre tags not rendering properly

### ISSUE THREAD

**Issue by vetruvet** [nylas/N1#424]
`pre` tags in emails are not rendering properly - newlines are ignored so everything runs on one line.

**Comment by mbilker** [comment]
I have a similar issue. Not all newlines aren't ignored, but some are. Pictures attached.
![2015-11-18-222343_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11261862/b5074100-8e46-11e5-864c-f3d2c8daf2a6.png)
![2015-11-18-224804_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11261863/b5077620-8e46-11e5-9ae9-f1432b162ee0.png)

**Comment by mbilker** [comment]
Here is the offending line: https://github.com/nylas/N1/blob/master/static/email-frame.less#L79

**Comment by mbilker** [comment]
With the contents of the message being `<pre style="white-space:pre">${test}</pre>` I get correct line breaks because the `white-space` CSS property is supposed to emulate the `pre` tag of HTML.c
![2015-11-18-225809_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11262019/1515e988-8e48-11e5-9ecd-87e412083466.png)

**Comment by jstejada** [comment]
thanks @mbilker !
