### ISSUE TITLE
Send Availability Package: no "add availability button" visible in draft

### ISSUE THREAD

**Issue by qaid** [nylas/N1#46]
I'm using the compiled version from the nylas site on Mac OS X, El Capitan.

I've manually installed the Send Availability package, but when I create a draft , I do not see any "add availability" button.

**Comment by bengotow** [comment]
Hi @qaid — thanks for downloading N1. It looks like the problem is that the `package.json` file of the Send Availability package does not register it to appear in the popout composer windows, only in inline replies in the main window. What you need to do is add this hash to the top level of the package.json file:

```
  "windowTypes": {
    "default": true,
    "composer": true
  }
```

I'll go ahead and commit an update to the package.

Also, it looks like the Send Availability package requires a server to be running for recipients of the "availability emails" to click on the times they're available and schedule the meeting. We don't currently have that deployed anywhere, and the references are still to localhost! You can play with the "embed availability" portion of the package, but we'll need to deploy that for the entire thing to work. Stay tuned.

**Comment by qaid** [comment]
Ah ok. Thanks for the update.
Looking forward to the feature's development.
