### ISSUE TITLE
Reloading with Full-window Composer does not close Composer

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#478]
I am developing a settings window for the PGP plugin, and I am investigating the Composer in full-window mode because it uses React and appears to not use an html file to load the page unlike the QuickSchedule plugin.

I thought the Composer window would close if I reload the main N1 window, but this did not happen.

**Comment by bengotow** [comment]
Hey @mbilker! The pop-out composer windows are full application windows that run in their own Electron `renderer` processes, load packages, etc. When you reload a window, it resets it and loads it's "index.html" page again, but it doesn't touch the other windows.

The old preferences window of the app worked a little differently and was attached to the DOM of the main window. That approach was riddled with small issues though because we were forwarding React's events through IPC.

I'd recommend building your settings into the new Preferences interface in 0.3.25. There's a small API for adding sections / tabs to the Preferences UI like this:

```
    PreferencesSectionStore.registerPreferenceSection(new Cfg {
      icon: 'ic-settings-general.png'
      sectionId: 'General'
      displayName: 'General'
      component: require './tabs/preferences-general'
      order: 1
    })
```

If you only have a few simple options, we'll also be following Atom's lead and allowing packages to specify "config schema" in their main file. We haven't linked that up to the preferences UI yet, but we will be soon! (example: https://github.com/atom/tree-view/blob/master/lib/main.coffee#L7)

**Comment by mbilker** [comment]
Ooh. This looks neat. I will be sure to try it out. Thanks you the insight @bengotow
