### ISSUE TITLE
Could not reach the Nylas API error

### ISSUE THREAD

**Issue by santhoshtr** [nylas/N1#54]
After installing in debian using the link given in invitation, I am getting this error 

![screenshot2](https://cloud.githubusercontent.com/assets/161672/10358112/643c0252-6da7-11e5-8768-7a43170e0209.png)

**Comment by blacksky86** [comment]
I'm getting the exact same problem. By looking at it, it's a linux specific problem

Mint 17.2 64bit

**Comment by gepoch** [comment]
Same here.

Linux 3.19.0-30-generic Ubuntu 15.04 x86_64 GNU/Linux

**Comment by geroyche** [comment]
same. ubuntu 14.04 lts x86_64

**Comment by bengotow** [comment]
Hey folks—this is pretty strange. It definitely looks like we weren't able to resolve the server address (in this case, `invite.nylas.com`.) Do you have any proxy configuration setup on your machine? Are you able to `ping invite.nylas.com` from the terminal? I believe there's another open issue about the app not using the system's proxy config, so that may be the issue here as well.

**Comment by geroyche** [comment]
PING omniproxy-1.nylas.com (52.26.120.161) 56(84) bytes of data.
^C
--- omniproxy-1.nylas.com ping statistics ---
19 packets transmitted, 0 received, 100% packet loss, time 18061ms

i'm in a corporate lan with vlans and what not. but there is no explicit proxy setting on my machine

foo@bar:~$ echo $HTTP_PROXY

foo@bar:~$

**Comment by sjug** [comment]
Same issue, I have an invite. Not able to ping invite.nylas.com, just like @geroyche.

**Comment by vonloh** [comment]
Same here

**Comment by vivin** [comment]
Same issue here:

```
ping invite.nylas.com
PING omniproxy-2.nylas.com (52.25.153.17) 56(84) bytes of data.
^C
--- omniproxy-2.nylas.com ping statistics ---
14 packets transmitted, 0 received, 100% packet loss, time 13102ms
```

**Comment by bengotow** [comment]
Hey folks—it looks like our public gateway drops pings, so that may be a red herring. Sorry! The exact request the app is making is to `https://invite.nylas.com/status/`. Is it possible that the app is trying to use the wrong network interface? I'll do some experimentation today and see if we can track this down.

**Comment by vivin** [comment]
Same issue here:

```
$ ping invite.nylas.com
PING omniproxy-2.nylas.com (52.25.153.17) 56(84) bytes of data.
^C
--- omniproxy-2.nylas.com ping statistics ---
14 packets transmitted, 0 received, 100% packet loss, time 13102ms
```

I tried this from a home machine as well, that's not behind any sort of proxy and got the same result:

```
$ ping invite.nylas.com
PING omniproxy-2.nylas.com (52.25.153.17) 56(84) bytes of data.
^C
--- omniproxy-2.nylas.com ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7055ms
```

It looks like your host disallows ICMP packets, which is why pings don't go through. Using traceroute with `-I` and `-T` shows this to be the case:

```
$ sudo traceroute -n -T invite.nylas.com
traceroute to invite.nylas.com (52.25.153.17), 30 hops max, 60 byte packets
 1  10.12.20.1  0.471 ms  0.328 ms  0.541 ms
 2  10.255.255.3  0.749 ms  0.752 ms  0.760 ms
 3  70.166.189.2  1.512 ms  1.497 ms  1.450 ms
 4  70.166.189.9  1.490 ms  1.476 ms  1.475 ms
 5  184.179.26.102  1.467 ms  1.462 ms  1.464 ms
 6  184.183.158.30  1.449 ms  1.257 ms  1.553 ms
 7  174.79.28.30  1.004 ms  1.179 ms  1.142 ms
 8  184.178.203.149  1.815 ms  2.375 ms  1.687 ms
 9  70.169.72.18  1.590 ms 70.169.72.32  2.826 ms 70.169.72.18  2.089 ms
10  54.240.242.141  55.845 ms 205.251.232.68  55.838 ms 54.240.242.77  56.446 ms
11  205.251.232.159  55.162 ms  58.348 ms 205.251.232.153  58.330 ms
12  205.251.232.165  55.017 ms 54.239.48.181  55.588 ms  54.969 ms
13  * * *
14  * * *
15  * * *
16  52.25.153.17  55.409 ms * *
```

vs

```
sudo traceroute -n -I invite.nylas.com
traceroute to invite.nylas.com (52.25.153.17), 30 hops max, 60 byte packets
 1  10.12.20.1  0.382 ms  0.428 ms  0.583 ms
 2  10.255.255.3  1.287 ms  1.283 ms  1.272 ms
 3  70.166.189.2  1.283 ms  1.912 ms  2.584 ms
 4  70.166.189.9  1.916 ms  2.589 ms  2.589 ms
 5  184.179.26.102  3.270 ms  3.280 ms  3.276 ms
 6  184.183.158.30  4.542 ms  4.128 ms  4.110 ms
 7  174.79.28.30  4.556 ms  3.884 ms  3.879 ms
 8  184.178.203.149  4.533 ms  4.538 ms  4.566 ms
 9  70.169.72.18  4.569 ms  4.545 ms  3.892 ms
10  54.240.242.77  58.320 ms  58.336 ms  58.326 ms
11  205.251.232.112  58.296 ms  57.781 ms  57.748 ms
12  205.251.232.147  57.771 ms  57.228 ms  57.676 ms
13  54.239.48.181  57.159 ms  56.998 ms  56.962 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

Not sure why this should affect API connection. But it did start working for me now, albeit intermittently.

And yes, it does look like it is using https:

```
$ ss -tp | grep nyl
ESTAB      0      0             10.12.20.94:36092         52.25.153.17:https    users:(("nylas",26193,60))
```

**Comment by geroyche** [comment]
i can connect to that url in a browser (json response {restricted:true})
fyi: i've got 4 ips set up (eth0 through eth0:2)

**Comment by dcelasun** [comment]
Same here, Arch Linux x64, no proxy, VPN or anything like that. Just a single wired network interface.

**Comment by alons45** [comment]
Same, Ubuntu 15.10

**Comment by EthanBlackburn** [comment]
Heya, we just deployed a patch that has fixed this for a few users. Could you guys try opening N1 again to see if you are prompted for an invite code?

**Comment by geroyche** [comment]
works for me \o/

**Comment by sergiokopplin** [comment]
works for me \o/ [2]

**Comment by alons45** [comment]
Not for me :-1:

**Comment by blacksky86** [comment]
This is also working for me now. Mint 17.2 64bit

**Comment by bengotow** [comment]
Hi folks—we've disabled the invite system, so I'm going to go ahead and close this issue. Enjoy N1!

**Comment by alons45** [comment]
Not working for me, same error, with last .deb installer
![n1](https://cloud.githubusercontent.com/assets/1877511/11578063/1a1fd28c-99f0-11e5-8e60-0045a8bb6e7c.png)

**Comment by arthankamal** [comment]
Yes it was happening for me too. It happened to me because of network restriction. But it was solved once i started using Wi-fi where there hasn't been any restrictions. You can find my two screenshots below.

When i use LAN
![screen shot 2015-12-15 at 5 24 17 pm](https://cloud.githubusercontent.com/assets/10445166/11810037/2a8c25c0-a351-11e5-9d55-9a84bb2d0cd0.png)

When i use Wifi
![screen shot 2015-12-15 at 5 25 51 pm](https://cloud.githubusercontent.com/assets/10445166/11810045/394a26c0-a351-11e5-8b26-0ca34d623a28.png)

**Comment by coworkingon-es** [comment]
Hi,
I am having the same problem on Linux Mint... Any solution to this?
Thanks!

**Comment by coworkingon-es** [comment]
Ok that seem because of former config. Resolved.

**Comment by atularvind** [comment]
Same issue on windows!
