### ISSUE TITLE
Feature Request: Swipe Gestures for Mac OS X

### ISSUE THREAD

**Issue by kevindesai777** [nylas/N1#541]
Swipe to delete and swipe to go back to inbox from the mail would be great. Can be similar to the gestures in the Mail app

**Comment by bengotow** [comment]
Hi — this is currently on the roadmap, feel free to upvote it here if you have a Trello account: trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by IAmFledge** [comment]
+1 - voted on Trello card.
Now trying out Nylas since Mailbox is dying. This is immediately the first thing missing.

**Comment by emorikawa** [comment]
Hey, an update here. This is definitely feature our team wants as well. Unfortunately it's blocked by Electron since they don't support (nor will support anytime soon) Mac Touchpad gestures. See https://github.com/atom/electron/issues/1486 and https://github.com/atom/electron/issues/2683

We attempted to do this just with standard scroll, wheel, and mouse DOM events; however, in order for swipe to work properly you need to know when your fingers leave the trackpad. This event is not dispatched anywhere (not in any mouseup since you haven't clicked anything).

We'll have to patch Electron core or make an extension to manually register with the OSX events. It's coming.

**Comment by jwaldrip** [comment]
Excited for this!

**Comment by jstejada** [comment]
this has landed in the latest release! enjoy!

**Comment by brycedorn** [comment]
:raised_hands: :raised_hands: :raised_hands:

**Comment by sanjeevverma1** [comment]
The default action for swiping right is "Trash"...how do change this action to "Archive" the email?
