### ISSUE TITLE
N1 launch dead slow

### ISSUE THREAD

**Issue by andysaini** [nylas/N1#616]
using the default sync engine, the client takes at least 25 seconds to launch. Is this normal? I'm using archlinux x64.

**Comment by bengotow** [comment]
Yep, unfortunately this is the expected launch performance. Because the app needs to load tons of Javascript files, it's launch speed is almost directly tied to disk read speed. It's snappy on fast SSDs and terribly slow on traditional drives. You can track the conversation about it here: #548 We'll be improving speed in future updates, but it's currently a widespread problem in "desktop Javascript" apps.

**Comment by andysaini** [comment]
I'm using an SSD..
