### ISSUE TITLE
Composer not handling composition events (Difficulty inputting Chinese characters)

### ISSUE THREAD

**Issue by clkao** [nylas/N1#62]
When using the composer with CJK input composition, the text is garbled because the uncommitted buffer is captured by change events, making it unusable.

This is now atom handles the composition events: https://github.com/atom/atom/blob/master/src/text-editor-component.coffee#L239 (in the `listenForIMEEvents` method)

**Comment by bengotow** [comment]
Hi @clkao — sorry to hear this is such a serious issue for CJK input. Looking at those event handlers in Atom, I think we could implement the necessary changes using some existing `UndoManager` methods in the ComposerView class. At some point soon, I think we need to take a pass through the whole app and look at CJK input / right-to-left input, etc. which weren't covered much during our private beta. If you're interested in helping out, we'd love contributions.

**Comment by haydnhkim** [comment]
Hi, Atom 1.2 support CJK typing!
https://twitter.com/atomeditor/status/664941227863740416
I don't konw this news helping for this project. ;_;

**Comment by emorikawa** [comment]
This has been fixed in c2ce51a and will go out in the next stable release (0.3.24).

The issue was due to the composer not properly handling [composition events](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent). We now treat the full composition lifecycle as a single atomic edit operation.

This issue was related to a variety of other issues including: #62, #384, #332, #89, #211

**Comment by clkao** [comment]
verified on master :rocket:
