### ISSUE TITLE
Feature request: Regex in email searchs

### ISSUE THREAD

**Issue by connorjsmith** [nylas/N1#661]
Not sure if this could be implemented as a plugin or not, but I think it'd be a good option to have

**Comment by Savemech** [comment]
That would be great :+1:

**Comment by sergeyklay** [comment]
:+1:

**Comment by grinich** [comment]
Currently search is powered by the backend provider (e.g. Gmail) and a small amount of local filtering. This is a very interesting idea for a plugin!

**Comment by connorjsmith** [comment]
Even if this had to be contained to searching within the body of a single email, I think it'd be a cool addition/plugin

**Comment by lapin-b** [comment]
+1

**Comment by bengotow** [comment]
Hey folks! N1 now supports "Find in Thread" (via Edit > Find > Find in Thread, and a keyboard shortcut). When in Find in Thread, you can search using Regex by making your query like this:

![image](https://cloud.githubusercontent.com/assets/1037212/14541652/f6c722be-0258-11e6-8545-3780eb7139bc.png)


(Notice how the last result is 20, not 20x, because the regex marked the x as optional.)

I'm going to go ahead and close this, because we've implemented client side search in 0.4.25 using SQLite, and it seems unlikely that we'll find a search index / solution that supports regexp queries. I'm not sure a good one exists!
