### ISSUE TITLE
Informative headers

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#689]
What does that blue dot mean? that´s an unread message?
I get that already with the bold...

That blue dot is unnecessary and uninformative...

![screen shot 2015-12-12 at 2 54 54](https://cloud.githubusercontent.com/assets/2094957/11759799/d89de08c-a07b-11e5-8672-6b17d07e0bdb.png)

Unread messages can be bold, no need for colour labels...

**Comment by bengotow** [comment]
Hey! Thanks for the feedback. I'll see if we can add an option for this in the future. Many mail clients use the blue dot to represent unread, while others (like Gmail) use bold. We need to include both so that users feel comfortable regardless of what client they're coming from, so we won't be changing the default.

See Mail.app: http://c1138122.cdn.cloudfiles.rackspacecloud.com/Mail%20Browser%201.png, Mailbox: http://cdn2.vox-cdn.com/uploads/chorus_asset/file/660608/mailbox_for_mac_screen_comp_2.0.png, for examples of clients that use the blue dot.

**Comment by tinybigstudio** [comment]
Sounds good...

The only thing I miss really are controls for " lists of emails" as in delete
all at once

> On Dec 12 2015, at 3:21 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hey! Thanks for the feedback. I'll see if we can add an option for this in
the future. Many mail clients use the blue dot to represent unread, while
others (like Gmail) use bold. We need to include both so that users feel
comfortable regardless of what client they're coming from, so we won't be
changing the default.

>

> See Mail.app:
<http://c1138122.cdn.cloudfiles.rackspacecloud.com/Mail%20Browser%201.png>,
Mailbox: <http://cdn2.vox-
cdn.com/uploads/chorus_asset/file/660608/mailbox_for_mac_screen_comp_2.0.png>,
for examples of clients that use the blue dot.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/689#issuecomment-164105177).![](https://github.com/notifications/beac
on/AB_3bQUCadsyZw3k8TAlRPwQHqZPRm8qks5pO4obgaJpZM4G0CVz.gif)
