### ISSUE TITLE
Closing window in full screen mode results in black screen

### ISSUE THREAD

**Issue by brettgerry** [nylas/N1#69]
To reproduce, View->Enter Full Screen. Then click the 'X' to close the window. The screen will now be black.

**Comment by mbilker** [comment]
Which OS is this under?

**Comment by jackjen** [comment]
I see the same issue under OSX El Capitan.

Same procedure for me,
View menu > Enter Full Screen > Hit the red [x] to close the window, you get a black screen
Exiting full screen restores the app to pre full screen dimensions.

**Comment by brettgerry** [comment]
Yosemite 10.10.5

**Comment by bengotow** [comment]
Hey folks, this has been fixed in d54b7edae036c139b8ab8c753d94b5653f085c0f. When you "close" the main mail window, we actually just hide it so that it can be immediately available if you click a notification, bring the app to the foreground, etc. (Actually preparing the main window and loading plugins takes a while.) This logic was conflicting with `fullscreen` mode—we were hiding the window without exiting fullscreen mode first. Thanks!
