### ISSUE TITLE
Prompt user when closing a New Message window before saving a draft

### ISSUE THREAD

**Issue by fjarrett** [nylas/N1#746]
When a user closes a New Message window in a dirty state, rather than automatically saving a new draft, they should be prompted to make a decision about what to do with the message:

1. **Trash** - _Discard the message and close the window._
2. **Cancel** - _Continue editing the message._
3. **Save** - _Save the message as a draft and close the window._

**Comment by grinich** [comment]
Does OS X Still do this? AFAIK most modern apps just save the state and let you get on with your life.

**Comment by bengotow** [comment]
Hey! N1 only autosaves new drafts if you've made changes. If you want to close the draft without saving, you can click the "Trash" icon in the bottom right instead of the top left X. We may consider adding a notice at some point, but it might be best implemented as a plugin. heers!

![image](https://cloud.githubusercontent.com/assets/1037212/14542020/cb5db5f0-025a-11e6-9fbd-c0e32da3eaa5.png)
