### ISSUE TITLE
Comic Sans headings in preferences

### ISSUE THREAD

**Issue by bmakuh** [nylas/N1#761]
I'm loving N1 and how fast it's iterating. It's really becoming pretty neat. However, I've noticed that the font `Nylas-FaktPro` doesn't load, and so headings in preferences display as Comic Sans for me. I'm using N1 Version 0.3.32-b11131d on OS X 10.11.1.

**Comment by grinich** [comment]
Yikes! @bmakuh can you paste a screenshot?

**Comment by bmakuh** [comment]
![image](https://cloud.githubusercontent.com/assets/563585/11905439/bf77fec8-a583-11e5-9b33-53ba7c7fbaef.png)

**Comment by fjarrett** [comment]
LOLZ

**Comment by bengotow** [comment]
Haha that's... really something. We actually specify Comic Sans as a fallback font deliberately so that font issues are reported, guess it's working :-). This was caused by some bad font css in an early version of the QuickSchedule plugin. If you disable that plugin or reinstall it, it should fix the issue.
