### ISSUE TITLE
Open message in separate window

### ISSUE THREAD

**Issue by lmartins** [nylas/N1#779]
Sometimes I get messages with big images inline that I need to see in full. Not sure if something feasible due to the app nature but would be useful addition I believe. 

Thanks.

**Comment by zlatkobijelic** [comment]
Is this happening in the near future?

**Comment by stevenhuey** [comment]
+1 - it would be great to be able to minimize the main window and compose a new mail message or reply in a separate window.

**Comment by bherila** [comment]
+1 for me too.

**Comment by bengotow** [comment]
Hey folks—we'll be working on this soon. It's tricky to pop the thread out into a new window because N1 is plugin based and loads a /lot/ of JavaScript into each window that is opened. We pre-load a composer window so that it opens very quickly, but doing that comes with a significant memory overhead we'd like to avoid. Stay tuned.

**Comment by stevenhuey** [comment]
Thanks for the update Ben. If you need a hand testing this, I'd be happy to help.

**Comment by molstrangler** [comment]
To add another though to this thread.

My ideal theme (or layout) would be to just have the message list window visible, the email preview and the left side bar not shown (when using the unified mailbox).  You could know need search & new email & menu icons cuz right-click or swipe could be used for individual message actions.

Double clicking on a message creates a new window with the message.

**Comment by koenpunt** [comment]
:+1:

**Comment by molstrangler** [comment]
+1

**Comment by markst** [comment]
+1 - just a thumbnail & allow user to quick view / open in preview.

**Comment by jasonw22** [comment]
👍

**Comment by visualrealityink** [comment]
This needs to be a feature, as it makes it difficult to extract information from one email to insert into another. There should be an option to both email reading, and email composing popup windows, and not overlays they need to be in a totally separate window. I am very surprised that you are charging $9 a month for an application with such a vital feature missing. I am having a Steve Jobs "Why are there no fonts...." moment!

**Comment by molstrangler** [comment]
I've opted for beta releases and I can say the double-click feature is not working for me. The client displays the email inline on the first click. No matter how quickly I try and double-click.

**Comment by hallamoore** [comment]
@molstrangler Are you using the single-panel view? In this view, you can't use the double-click to open the thread, but there should be an icon next to the print icon that you can use instead!

**Comment by molstrangler** [comment]
@hallamoore To me restricting the double click function in a view where you can already see and read the email 'two-panel-mode' seems rather pointless, also the icon already exists in the email to view the email in a separate window.

So why add the double click function?

Also, this same icon is only visible when the email is displayed in the single-panel view. So not very useful when in 'single-panel' mode.  Nylas really needs to understand why people prefer or use one of the two different panel modes available in the email client.

**In the single-panel mode it should be possible to double click the email to open a separate window.**

Also you should add the option for 'single-panel' mode so a _single-click_ on the email will open it in a separate window.  This UX is consistent with why many want to use the 'single-panel' mode.

**Comment by hallamoore** [comment]
@molstrangler The new feature is not so much the double-clicking, but actually just the ability to open messages in a new window at all. The pop-out icon is part of this new feature and did not exist before. We can't add double-clicking in single-panel mode because the single-click action interrupts the event flow. We may consider alternate UI options for this in the future, but for now we just wanted to put the base functionality out there. Thanks for the feedback!

**Comment by bengotow** [comment]
Hey folks - this feature has shipped in 0.4.59. You can double-click threads to pop them out into a new window. You can have as many thread windows open as you need.

We chose to implement this as a double click rather than a single click on threads for consistency with native platform expectations. On Mac OS X and Windows, you almost never open new windows with a single click on documents, conversations or items. (Finder, Mail.app, Messages.app, etc.) I realize most web apps use single click to open items (Gmail, `<a>` tags, etc.), but we strive for N1 to look and feel like a native application.

We'll try to implement double-clicking threads in single-panel mode in the next release. To do it, we'd need to delay single click from sliding the thread into view by 400ms, which we decided wasn't desirable. Will need to revisit that if we want double clicking there.

Enjoy!
