### ISSUE TITLE
Multi account merged list view

### ISSUE THREAD

**Issue by Blackrush** [nylas/N1#8]
One thing I really appreciate using Mail.app is the ability to have a quick glance over all my unread mails of all the accounts I added. Is it a planned feature for N1 ?

**Comment by bengotow** [comment]
Hey @Blackrush —  "unified mailbox view" is definitely on the roadmap. I agree it'd be really nice, especially for Inbox, Unread, and Starred. It'll take some effort to implement because most of the app is account-scoped at the moment.

I've added it as a feature request on our public Trello board. Feel free to upvote it there! https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by Blackrush** [comment]
I voted as advised. Thanks for the quick reply :+1:
