### ISSUE TITLE
[doc] improve documentation about tokens and the self-running sync-engine

### ISSUE THREAD

**Issue by arthurlutz** [nylas/N1#81]
I followed the documentation here : https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine and am not getting to see the emails in the N1 user interface. 

One of the things that seems to be missing (but it might be something else) is the accountTokens that are in the example cson file. I can't find documentation on how to generate those. 

Also, it is not exactly clear what needs to be run in the vagrant vm (only inbox-start and inbox-api ?)

Thanks, this looks really promising.

**Comment by bengotow** [comment]
Hey @arthurlutz — thanks for filing this. The account tokens bit is a little strange, because the open-source sync engine doesn't have any concept of account tokens, but needs the account id in place of the token. So setting up that hash in the `config.cson` file with `"<account id>": "<account id>"` is correct. I'll see if we can improve the docs to make that more clear.

I think we can also add more clarity to the "run the sync engine" bit. I think inbox-start and inbox-api are all you need, but I'll double check.

**Comment by bengotow** [comment]
I've made some improvements to CONTRIBUTING.md in 7787e0bc4b4da40e1d31a5d6b4ef6a8c73bd5132 to address these changes—going to go ahead and close this. Let me know if there's anything else that should be added!
