### ISSUE TITLE
When Sharing A Link It's Cut Off

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#815]
When I share a link via Safari on OSX 10.11.2 the last 1 or 2 characters  of the URL are cut off making the link invalid. Nylas is the only client that does this.

**Comment by bengotow** [comment]
Hey! I'm trying to reproduce this but I haven't found a URL which gets cut off yet. It's very likely that there's a character in the URL you're trying to share which causes it to get sliced. Can you share an example link?

**Comment by bengotow** [comment]
Nevermind - found one! `https://github.com/atom/electron/issues?utf8=✓&q=is%3Aissue+is%3Aopen+123` is an example.

**Comment by bengotow** [comment]
I've fixed this in 47b0ab5c973c23e94b27d42200a190058e92991b. Turns out, this is a pretty hairy problem. Safari is sending this mailto link to the app:

```mailto:?subject=Issues%20%C2%B7%20atom/electron%20%C2%B7%20GitHub&body=https://github.com/atom/electron/issues?utf8=&q=is%253Aissue+is%253Aopen+123%0A%0A```

Unfortunately, the "?" and "&" characters in the body are not properly url-encoded, so standard query string parsing breaks them out into separate parameters. We now parse mailto links on our own and look only for the params we expect (to, cc, bcc, subject, body), considering everything in between to be part of the value.
