### ISSUE TITLE
Override icons in theme

### ISSUE THREAD

**Issue by equinusocio** [nylas/N1#835]
Hi all, i'm designing a new light theme for N1, i would like to know if there a way to override the default icons ( e.g. ```images/thread-list/checkbox-checkmark-activerow@2x.png``` ) by theme package. If there, how i can do it? I tried to put the static images folder under the package ```root``` and inside ```styles``` folder but it did not work.

Thanks for this software ;)

**Comment by mbilker** [comment]
You may need to override the `background-image` to point to your image. So for something like `ThreadList` the declaration is:
```
background-image:url(../static/images/thread-list/icon-attachment-@2x.png);
```

Your theme may use the same `url`, but you need to declare the style override so N1 uses your image and not the internal one.

**Comment by equinusocio** [comment]
This also work if the image is a ``<ìmg>```tag?

**Comment by mbilker** [comment]
@equinusocio that is a little more difficult. I don't know what to do for them actually.

**Comment by equinusocio** [comment]
I've tried with this path ```images/toolbar/toolbar-archive@2x.png``` and seems that it keep picking the original icon from original images folder inside static.

**Comment by mbilker** [comment]
It seems that the `RetinaImg` class handles image path locations through `Utils.imageNamed`.

**Comment by equinusocio** [comment]
@mbilker the problem isn't the retina image but his source path. The package CSS pick always image asset from the app static folder and not from images folder of the package. :+1:

**Comment by bengotow** [comment]
Hey folks! This is a great idea. Almost all the images in the core app are loaded via RetinaImg, and you could theoretically change `imageNamed` to return a different image path. That function is subject to change though, because we're planning to pre-compute the image lookup table when we ship the app rather than doing it at launch. I wouldn't recommend using a Javascript approach here.

One solution is to use /very/ specific CSS selectors to change images. You can actually use the `content` CSS attribute to override an image src (at least in our latest version of Chromium!). Here's an example:

https://jsfiddle.net/e8rsv9z8/1/

Note that for some icons generated with `RetinaImg.Mode.ContentIsMask`, the image is actually a `-webkit-mask-image`, and you'd need to override that instead of the src. Also, when you do your overrides, specify the new image paths as `nylas://<your theme package name>/assets/bla.jpg` (assuming bla.jpg is inside an assets folder in your package). That will take care of all the path mess for you.

Cheers!

**Comment by equinusocio** [comment]
Thanks @bengotow this is what i need!
