### ISSUE TITLE
Tildes ~ don't look right when they are in the middle of a word

### ISSUE THREAD

**Issue by brettgerry** [nylas/N1#89]
Just passing by to report a bug on a OS X with Portuguese language:
Screen recording:
 http://buro.pt/dW6i

They look find then word starts with one, but not when in the middle of the word.

**Comment by frdmn** [comment]
Am I missing something or isn't that just the usual behaviour of [dead keys](https://en.wikipedia.org/wiki/Dead_key)?

**Comment by jaimeiniesta** [comment]
I found the same bug when writing Spanish words with tildes. Yes, we use dead keys to write that, for instance:

> fantástico

To write this `á` I first hit the `´` key, and then the `a`, and it produces the `á`.

But in N1, it duplicates the tilde and produces `´a` or `´á`.

This only seems to happen on the New Message window, just on the body area, but not on the "to" or "cc" fields.

There are certain character combinations where this does not fail, check this screenshot ("hoyá" is nonsense, invented word):

![captura de pantalla 2015-10-21 a las 13 42 37](https://cloud.githubusercontent.com/assets/2629/10635539/c0d6dc2e-77f9-11e5-94d1-dfb2c6137119.png)

**Comment by frdmn** [comment]
@jaimeiniesta Ah, now I get it I think. Thanks for the explanation.

**Comment by grinich** [comment]
This is probably an issue with the font we're using

**Comment by thiagodiniz** [comment]
I have the same problem with OS X El Captain.
@grinich how would be a font problem? Is ther a way to change the font?

**Comment by emorikawa** [comment]
This has been fixed in c2ce51a and will go out in the next stable release (0.3.24).

The issue was due to the composer not properly handling [composition events](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent). We now treat the full composition lifecycle as a single atomic edit operation.

This issue was related to a variety of other issues including: #62, #384, #332, #89, #211
