### ISSUE TITLE
Order sent folder by most recent sent message

### ISSUE THREAD

**Issue by smacking** [nylas/N1#890]
Right now, it seems to me that the order of the Emails Sent is being done by Thread, and not by the Most Recent Sent Message to the Oldest Sent Message, which in my opinion is the standard and the best way to order Sent Messages.

I don't discuss that some people might want the first ordering (by Thread), but it would be great to have a way to choose that. To me, it is really annoying and frustrating to have to scroll down to check if my email was sent or no.

Actually, it took me around 10m to arrive to this conclusion. Until that, I thought my email failed to send... :/

Anyone else finding this to be frustrating?

**Comment by samueldmcdermott** [comment]
Yes, I agree with this entirely. I'd love to have this changed or at least be given a choice.

**Comment by grinich** [comment]
Agreed-- this is a bug

**Comment by MariusMasalar** [comment]
Would really like to see this as well, I'm always bewildered when I come back to N1 and look into the Sent folder.

**Comment by smacking** [comment]
This bug was solved but it's back again. Please fix it, it's really annoying :/ @grinich

**Comment by bengotow** [comment]
This has been fixed by https://github.com/nylas/sync-engine/commit/553c4738e6a6199d0d7ccdccb75e48b9685a20a0 and 703686d3222c5821b80ce40f2076b2ef8bb7f599. Will finally be closed in the next release. Thanks folks—

**Comment by jstejada** [comment]
this has been released! closing issue now

**Comment by cosmomans** [comment]
I seem to still be having the same problem. I just installed Nylas N1 and used it all day. I noticed now that my sent items appear to be empty even though I've sent a few emails from Nylas N1. My emails are hosted by Zoho.com and I can find a copy of the sent emails on the server.

Some help would be greatly appreciated because I really like this software but this is kind of a deal breaker for me :(

Thank you!
