### ISSUE TITLE
If you're out of disk space, N1 may truncate config.cson when trying to save it

### ISSUE THREAD

**Issue by bengotow** [nylas/N1#897]
The following error appears in the console:

```
[10315:0104/122050:ERROR:shared_memory_mac.cc(283)] Creating shared memory in /var/folders/g8/kd9f0jmj26gf1xlq4qj8pm740000gn/T/.org.chromium.Chromium.ViEfss failed: No space left on device
[10315:0104/122051:INFO:CONSOLE(663)] "Uncaught Error: ENOSPC: no space left on device, write", source: fs.js (663)
```

**Comment by grinich** [comment]
@walshie4 @khanshakeeb @Iain-Stevenson @Dids @akizor tracking bug here

**Comment by finalwebsites** [comment]
I had the same issue a few days ago:
- I closed N1
- Dit some updates (Ubuntu 14.04), I guess also some updates to N1
- Did required reboot
- All accounts are reset/gone

Before this issue I had Gmail and IMAP accounts installed. There was no problem to restore the Gmail accounts, but I can't re-install the IMAP accounts because I'm getting an error while doing this:
![selection_989](https://cloud.githubusercontent.com/assets/90638/13552791/a1812cac-e370-11e5-9686-f24411765309.png)

The config file doesn't show the IMAP files anymore, so I guess the config file was truncated or gone after the reboot. My harddisk is for 60% empty.

**Comment by jackiehluo** [comment]
Should be fixed on latest versions! Closing.
