### ISSUE TITLE
Why CoffeeScript but not ES6?

### ISSUE THREAD

**Issue by kitgary** [nylas/N1#9]
I just wonder why don't use ES6 directly? It makes contribution harder.

**Comment by ethryx** [comment]
I was curious about this as well.

**Comment by bengotow** [comment]
Hey folks—this is a great question. If we started today, it'd make a lot more sense to use ES6. CoffeeScript has played an important role in informing the future of JavaScript, but it will most likely become a historical footnote as ES6 becomes standard.

N1 began as a fork of the Atom text editor, which was started in 2012 when ES6 was pretty far out on the horizon. There wasn't native support for ES6 in Electron, Babel was just an idea, and well, CoffeeScript was the language of choice. When we started N1, digging into Atom was the best way to start using Electron (formerly Atom-Shell) and we kept things like the package manager and app bootstrapping code. In the interest of shipping, we stuck with CoffeeScript.

I agree that using CoffeeScript makes contributing to N1 harder. We've had a lot of folks request that we convert the example packages into JavaScript, and we may do that soon. It's also worth mentioning that you can write your own packages for N1 in JavaScript ES6 / ES5 — just because the core is in CoffeeScript doesn't mean your additions need to be!

In a perfect world, someone would write a "CoffeeScript to ES6" transpiler (which I think would be doable?) and we would transition the entire codebase to JavaScript someday.

For anyone interested, there's a great discussion/flamewar on the Atom discussion board about their original choice of CoffeeScript over JavaScript—https://discuss.atom.io/t/why-coffeescript/131.

**Comment by nunofgs** [comment]
I was about to ask the same question. Is there any plan to migrate piece-by-piece towards ES6?

**Comment by digitalmaster** [comment]
Same here.. But makes total sense.. Thanks for explaining. @bengotow

**Comment by colinramsay** [comment]
I would also like to know how to write a plugin in ES6; for example, just renaming to jsx from cjsx doesn't seem to work.

**Comment by jstejada** [comment]
@nunofgs @digitalmaster @colinramsay hey guys we've fixed support for ES6 inside N1 so you can write your packages using ES6 code. Structure is the same, you just need to name your files with any of the following extensions:  `*.es6`, `*.es`, `*.jsx`.

We'll update the examples to ES6 very soon. Ping me if you have any questions.

**Comment by jstejada** [comment]
Also, in case anyone is put off by your text editor not recognizing the filetype, if you use vim you can add this to your `vimrc` (or `~/.vim/ftdetect/es6.vim`):

`au BufRead,BufNewFile *.es6    set filetype=javascript`

In atom you can use this filetype plugin: https://atom.io/packages/file-types. Sublime and others should have similar ones.

**Comment by noahbuscher** [comment]
+1 for an eventual core migration to ES6 😄

**Comment by mbilker** [comment]
@jstejada Thanks for the VIM syntax. I use Atom mostly, but I do like VIM.

**Comment by balupton** [comment]
> In a perfect world, someone would write a "CoffeeScript to ES6" transpiler (which I think would be doable?) and we would transition the entire codebase to JavaScript someday.

Our [Bevry](https://bevry.me) community moved from CoffeeScript to ES6 for [better debugging and performance primarily](https://discuss.bevry.me/t/move-from-coffeescript-to-es6/30) (<- this is actually a very interested read), and in our research for it and conversion we found that an automated tool just won't be adequate for this - in the same way an automated tool can't determine `==` or `===` usage, because the app or libraries may depend on one even if the intent was actually another - things like classes and the emulation of CoffeeScript and the way they are now accomplished in ES6 and the way you orchestrate your app becomes different, and should be different.

To make the conversion easier, this is a list that we did up of common conversions that we performed: https://github.com/bevry/coffeescript-to-es6

**Comment by joepeak** [comment]
+1,hope es6
