### ISSUE TITLE
Enhancement: Use SPDY/HTTP2 to reduce latency and WebSockets for Long-Polling

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#909]
On the Slack chat, `eliz` and I believe the implementation of SPDY/HTTP2 for the API requests (`Requests` tab in the Activity Window) and WebSockets for the Long-Polling connections would be a wise decision. This issue is for the Sync Engine and N1.

`eliz` is having connection issues when loading new messages likely from latency between his connection and Amazon EC2. Ths stems from N1 opening a new connection for every API request in `src/flux/nylas-api.coffee`.

The implementation may take time and will need re-architecture because Node's `request` module does not support SPDY or HTTP2. WebSocket support is already present in widely used Node modules, but the Sync Engine component would take the most effort.

**Comment by bengotow** [comment]
Hey! Thanks for filing this. Our current implementation of the streaming `NylasLongConnection` (both in the app and in the sync engine) is based on Twitter's Streaming protocol and is preferable to WebSockets. WebSockets is great when you need wide browser support and lots of backwards compatibility, but opening a socket connection and holding it open is fast and simple. (We don't care about compatibiltiy with IE8/9, etc. since it's just for Chromium!)

In the past we've talked about sending API requests through the `NylasLongConnection`. You're correct that using an open socket would be slightly faster, because we could avoid the initial handshake. However, when you're reading mail that has just arrived, the app shouldn't be making any API requests since the messages, threads, and their bodies arrive over the socket connection (which is already open). Most of the API requests are for syncing actions back to the server after they've been applied locally. In those cases, latency doesn't really matter.

**Comment by mbilker** [comment]
I do agree with that my new mail is quick to load and I saw no API requests made. I guess the enhancement part of this issue has no place.

The issue still stands with `eliz`, but I suspect it is with upstream provider from him.

**Comment by bengotow** [comment]
Hey folks— I think this was resolved on the Slack channel and probably isn't due to latency in the socket implementation as much as latency on the sync engine side.
