### ISSUE TITLE
Actions when selecting more than one email

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#922]
![screen shot 2016-01-07 at 23 34 12](https://cloud.githubusercontent.com/assets/2094957/12186106/950324e6-b597-11e5-8a0a-c713d3a4eb96.png)

When I select a few emails, the expected behaviour is to apply the provided actions to the all the emails in the selection.

Currently those action are only applied to one line as if the selection was not a group, which is not what the user had chosen.

**Comment by tinybigstudio** [comment]
Actions being favorite, delete and archive.

**Comment by bengotow** [comment]
Hi @tinybigstudio — it sounds like you're clicking the hover actions shown beside that one email? If you use the controls at the top of the thread list when you're in selection mode, those apply actions to the entire selection.

We decided to do it this way because people often build up a selection while triaging their mail, so it's nice to be able to trash / archive individual items while still selecting a bunch to move. We could make it an option in the future though!

**Comment by grinich** [comment]
Yep, these are the inline actions. Look above for the actions that apply to all the selected items! For example: 
![image](https://cloud.githubusercontent.com/assets/92417/12189620/42f0d072-b574-11e5-8a68-50295e12cebc.png)
