### ISSUE TITLE
N1 polling Nylas invite endpoint

### ISSUE THREAD

**Issue by QuantumPhi** [nylas/N1#947]
![polling](https://cloud.githubusercontent.com/assets/5723421/12218885/91a1d662-b6e1-11e5-92e8-a8b78f69a0d5.PNG)

Given that N1 is available to everyone without an invite code, this seems rather pointless, especially given the fact that the endpoint only returns this JSON data:

```javascript
// URL: https://invite.nylas.com/status/
{
  "restricted": false
}
```

Please note that the "Add Account" option (under the hamburger menu) will wait for this request to complete before opening the "Add an Account" dialogue:

![animation](https://cloud.githubusercontent.com/assets/5723421/12218967/4d903212-b6e5-11e5-9772-f5e7251733cc.gif)

Just an observation. Not a critical issue by any means.

EDIT: This procedure could be present at other points in N1; have not checked extensively.

**Comment by bengotow** [comment]
Hey! Thanks for filing this—you're definitely right that N1 still hits the invite endpoint. Even though we've disabled the invite system, we keep the infrastructure in place so that our team can throttle user registrations if necessary. (For example, if/when we get press, we may have to turn it on for a day or two to protect performance for our existing users.)

I'm sure we'll clean it up sometime soon, but for now it's an important safeguard.
