### ISSUE TITLE
manual import mailbox

### ISSUE THREAD

**Issue by Roel1000** [nylas/N1#950]
Should be handy when it's possible to add mailboxes stored on my macbook manually. I have a few and they so far I can see it's not possible to add them.
Besides (and because): After installing N1 it appeared that not all my mail from the inbox of apple mail was imported. I miss a few months of mail.

**Comment by mbilker** [comment]
The mail is actually stored both on the client N1 instance and the hosted Sync Engine. Therefore, importing your local mailbox is hard and parsing the Apple Mail database is hard through `CoreData`.

**Comment by bengotow** [comment]
Hi @Roel1000 —thanks for filing this. The rest of your inbox should appear, but it can take some time for initial sync to complete.

Unfortunately, it'd be challenging to import mailboxes from other mail apps because N1 connects to a cloud sync engine. We'd have to actually upload your mail to the sync engine so that it could be manipulated in N1. We've considered doing this before, but in most cases it'd just be a time saver!

**Comment by jamalawad26** [comment]
Hi @bengotow -- Thanks for having the amazing N1 mail client. I am facing same issue since was using outlook on windows and now back to Linux. I have an email archive of more than 10 GB. Did you guys managed to make a step forward solving this issue?
