### ISSUE TITLE
Very slow rendering performance

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#961]
Reported from intercom:

> I am getting like 12 fps in the program if it is open at all. Not just scrolling, just anything in general. It's practically unusable. W10 64, i5 3570k, GTX980,8GB DDR3.

Using N1 v0.3.36

**Comment by mbilker** [comment]
Could this be related to #675?

**Comment by jstejada** [comment]
Update: 
> Screen resolution is 2560x1440. I tried making the window smaller like you said, no dice. I also tried lowering my screen res and it didn’t help either.

**Comment by CliffordR** [comment]
I am the reporter from the intercom, I also forgot to add: When 
nylas is open (and thus lagging), my screen flickers. I have a 144Hz monitor btw, but even if I switch it to 60Hz it does this. If Nylas isn't the focused window, the flickering and lag go away. No other software  I use does this, but I suspect it may be bad interaction with the display drivers because apparently Nvidia is having trouble with Windows 10.

**Comment by bengotow** [comment]
Hey! We've made a bunch of performance improvements since January, and remaining rendering issues (especially things like screen flickering) are beyond our control, since N1 is built on Chromium. Would love for you to try out N1 again and see if it's any better on your machine!
