### ISSUE TITLE
Find in page

### ISSUE THREAD

**Issue by MisterTea** [nylas/N1#98]
Electron doesn't support "Find in page" which makes finding a specific term in an email not possible.  This is obviously very important for an email client.  Here's a link to a discussion on find-in-page using electron: https://github.com/atom/electron/issues/2037

Apparently we can create a shortcut and use window.find(...).

**Comment by bengotow** [comment]
Hi @MisterTea — thanks for reporting this, I think it'd definitely be a good feature. I think we could implement it with `window.find`, but we might actually want something a bit more fancy, so that things like the sidebar are excluded from the search. I've added it to our open-source roadmap Trello board—feel free to track it and upvote it there!
